# Importing Libraries

In [1]:
import pandas as pd
import os
from pathlib import Path

# Load CSV and Setup Env

In [2]:
PROJECT_DIR=Path("").resolve()
FILE = PROJECT_DIR / "obs_check.csv"

print(f"Project Directory : {PROJECT_DIR} | Exists: {PROJECT_DIR.exists()}")
print(f"FILE : {FILE} | Exists: {FILE.exists()}")

Project Directory : C:\Users\surab\OneDrive\Documents\NCSU\Foodchain project\SpeciesML\EDA | Exists: True
FILE : C:\Users\surab\OneDrive\Documents\NCSU\Foodchain project\SpeciesML\EDA\obs_check.csv | Exists: True

In [3]:
df = pd.read_csv(FILE)
df

,observation_id,obs_match,partner_id,par_match,From Dataset,no_partner_ids
0,10686,No,1766953,No,No,341194952.0
1,414645,No,414707,No,Yes,340433312.0
2,414707,No,414645,No,Yes,340394115.0
3,465679,No,66466718,No,Yes,340261882.0
4,509046,No,66466454,No,Yes,340178684.0
...,...,...,...,...,...,...
12373,347741351,No,347741350,No,No,NaN
12374,347744271,No,347744274,No,No,NaN
12375,347744274,No,347744271,No,No,NaN
12376,347744290,No,347744291,No,No,NaN
12377,347744291,No,347744290,No,No,NaN

# Evaluation

## Count of obs-partner pairs

In [4]:
df["id"] = df["observation_id"].astype(str) + "_" + df["partner_id"].astype(str)
df

,observation_id,obs_match,partner_id,par_match,From Dataset,no_partner_ids,id
0,10686,No,1766953,No,No,341194952.0,10686_1766953
1,414645,No,414707,No,Yes,340433312.0,414645_414707
2,414707,No,414645,No,Yes,340394115.0,414707_414645
3,465679,No,66466718,No,Yes,340261882.0,465679_66466718
4,509046,No,66466454,No,Yes,340178684.0,509046_66466454
...,...,...,...,...,...,...,...
12373,347741351,No,347741350,No,No,NaN,347741351_347741350
12374,347744271,No,347744274,No,No,NaN,347744271_347744274
12375,347744274,No,347744271,No,No,NaN,347744274_347744271
12376,347744290,No,347744291,No,No,NaN,347744290_347744291
12377,347744291,No,347744290,No,No,NaN,347744291_347744290

In [5]:
df["p_id"] =  df["partner_id"].astype(str) + "_" + df["observation_id"].astype(str)
df

,observation_id,obs_match,partner_id,par_match,From Dataset,no_partner_ids,id,p_id
0,10686,No,1766953,No,No,341194952.0,10686_1766953,1766953_10686
1,414645,No,414707,No,Yes,340433312.0,414645_414707,414707_414645
2,414707,No,414645,No,Yes,340394115.0,414707_414645,414645_414707
3,465679,No,66466718,No,Yes,340261882.0,465679_66466718,66466718_465679
4,509046,No,66466454,No,Yes,340178684.0,509046_66466454,66466454_509046
...,...,...,...,...,...,...,...,...
12373,347741351,No,347741350,No,No,NaN,347741351_347741350,347741350_347741351
12374,347744271,No,347744274,No,No,NaN,347744271_347744274,347744274_347744271
12375,347744274,No,347744271,No,No,NaN,347744274_347744271,347744271_347744274
12376,347744290,No,347744291,No,No,NaN,347744290_347744291,347744291_347744290
12377,347744291,No,347744290,No,No,NaN,347744291_347744290,347744290_347744291

In [6]:
dataset = df[df["From Dataset"] == "Yes"]
dataset

,observation_id,obs_match,partner_id,par_match,From Dataset,no_partner_ids,id,p_id
1,414645,No,414707,No,Yes,340433312.0,414645_414707,414707_414645
2,414707,No,414645,No,Yes,340394115.0,414707_414645,414645_414707
3,465679,No,66466718,No,Yes,340261882.0,465679_66466718,66466718_465679
4,509046,No,66466454,No,Yes,340178684.0,509046_66466454,66466454_509046
5,518909,Yes,66466205,No,Yes,340032293.0,518909_66466205,66466205_518909
...,...,...,...,...,...,...,...,...
12047,340891948,No,174225580,Yes,Yes,NaN,340891948_174225580,174225580_340891948
12050,341011035,Yes,341186087,No,Yes,NaN,341011035_341186087,341186087_341011035
12052,341060248,Yes,303790480,Yes,Yes,NaN,341060248_303790480,303790480_341060248
12053,341060278,Yes,303790022,Yes,Yes,NaN,341060278_303790022,303790022_341060278
12055,341067936,Yes,341067932,No,Yes,NaN,341067936_341067932,341067932_341067936

In [ ]:
# dataset.to_csv("check.csv",index=False)

In [7]:
unique_id_count =dataset["id"].nunique()
unique_id_count

6567

In [8]:
unique = dataset["p_id"].nunique()
unique

6567

In [23]:
count = dataset[dataset["p_id"].isin(dataset["id"])]
len(count)

3929

In [24]:
unique_ids =  unique - len(count)
unique_ids

2638

## obs(true) and partner(true)

In [26]:
ot_pt=dataset[(dataset["obs_match"]=="Yes") & (dataset["par_match"]=="Yes")]
ot_pt

,observation_id,obs_match,partner_id,par_match,From Dataset,no_partner_ids,id,p_id
11,673967,Yes,103137514,Yes,Yes,338262521.0,673967_103137514,103137514_673967
31,1059442,Yes,1059454,Yes,Yes,335611213.0,1059442_1059454,1059454_1059442
32,1059454,Yes,1059442,Yes,Yes,334569592.0,1059454_1059442,1059442_1059454
34,1068300,Yes,66419503,Yes,Yes,334290701.0,1068300_66419503,66419503_1068300
57,2425593,Yes,2425738,Yes,Yes,331849813.0,2425593_2425738,2425738_2425593
...,...,...,...,...,...,...,...,...
12018,340337865,Yes,296427700,Yes,Yes,NaN,340337865_296427700,296427700_340337865
12024,340514309,Yes,340514310,Yes,Yes,NaN,340514309_340514310,340514310_340514309
12025,340514310,Yes,340514309,Yes,Yes,NaN,340514310_340514309,340514309_340514310
12052,341060248,Yes,303790480,Yes,Yes,NaN,341060248_303790480,303790480_341060248
12053,341060278,Yes,303790022,Yes,Yes,NaN,341060278_303790022,303790022_341060278

In [29]:
unique_ids_ot_pt = ot_pt["id"].unique()
unique_ids_ot_pt

<StringArray>
[   '673967_103137514',     '1059442_1059454',     '1059454_1059442',
    '1068300_66419503',     '2425593_2425738',    '2468967_28545358',
     '4706757_4706758',     '4706758_4706757',     '4977020_4977021',
     '4977021_4977020',
 ...
 '340147007_340147022', '340147022_340147007', '340271186_340271239',
 '340271239_340271186', '340337296_296427700', '340337865_296427700',
 '340514309_340514310', '340514310_340514309', '341060248_303790480',
 '341060278_303790022']
Length: 1969, dtype: str

In [32]:
count = ot_pt[ot_pt["p_id"].isin(ot_pt["id"])]
len(count)

1907

In [34]:
unique_ot_pt=  len(unique_ids_ot_pt) - len(count)
unique_ot_pt

62

## obs(true) and partner(false)

In [50]:
ot_pf=dataset[(dataset["obs_match"]=="Yes") & (dataset["par_match"]=="No")]
ot_pf

,observation_id,obs_match,partner_id,par_match,From Dataset,no_partner_ids,id,p_id
5,518909,Yes,66466205,No,Yes,340032293.0,518909_66466205,66466205_518909
7,608490,Yes,66465198,No,Yes,339965719.0,608490_66465198,66465198_608490
9,613368,Yes,66464630,No,Yes,338572816.0,613368_66464630,66464630_613368
10,613370,Yes,66464171,No,Yes,338572814.0,613370_66464171,66464171_613370
12,746116,Yes,66463516,No,Yes,338041950.0,746116_66463516,66463516_746116
...,...,...,...,...,...,...,...,...
12040,340848497,Yes,340848415,No,Yes,NaN,340848497_340848415,340848415_340848497
12041,340848514,Yes,340848415,No,Yes,NaN,340848514_340848415,340848415_340848514
12042,340848746,Yes,340848415,No,Yes,NaN,340848746_340848415,340848415_340848746
12050,341011035,Yes,341186087,No,Yes,NaN,341011035_341186087,341186087_341011035
12055,341067936,Yes,341067932,No,Yes,NaN,341067936_341067932,341067932_341067936

In [51]:
ids = ot_pf["observation_id"]
ids

5           518909
7           608490
9           613368
10          613370
12          746116
           ...
12040    340848497
12041    340848514
12042    340848746
12050    341011035
12055    341067936
Name: observation_id, Length: 3087, dtype: int64

In [52]:
ids = ids.drop_duplicates()
len(ids)

3013

## obs(false) and partner(false)

In [53]:
of_pf=dataset[(dataset["obs_match"]=="No") & (dataset["par_match"]=="No")]
of_pf

,observation_id,obs_match,partner_id,par_match,From Dataset,no_partner_ids,id,p_id
1,414645,No,414707,No,Yes,340433312.0,414645_414707,414707_414645
2,414707,No,414645,No,Yes,340394115.0,414707_414645,414645_414707
3,465679,No,66466718,No,Yes,340261882.0,465679_66466718,66466718_465679
4,509046,No,66466454,No,Yes,340178684.0,509046_66466454,66466454_509046
6,526854,No,66465985,No,Yes,339988554.0,526854_66465985,66465985_526854
...,...,...,...,...,...,...,...,...
12014,340326193,No,340326194,No,Yes,NaN,340326193_340326194,340326194_340326193
12015,340326194,No,340326193,No,Yes,NaN,340326194_340326193,340326193_340326194
12026,340542613,No,340542614,No,Yes,NaN,340542613_340542614,340542614_340542613
12028,340722576,No,340722577,No,Yes,NaN,340722576_340722577,340722577_340722576
12029,340722577,No,340722576,No,Yes,NaN,340722577_340722576,340722576_340722577

## obs(false) and partner(true)

In [54]:
of_pt=dataset[(dataset["obs_match"]=="No") & (dataset["par_match"]=="Yes")]
of_pt

,observation_id,obs_match,partner_id,par_match,From Dataset,no_partner_ids,id,p_id
24,894002,No,893936,Yes,Yes,337060870.0,894002_893936,893936_894002
28,1031679,No,1031674,Yes,Yes,336128756.0,1031679_1031674,1031674_1031679
33,1068273,No,66419503,Yes,Yes,334489227.0,1068273_66419503,66419503_1068273
48,1541560,No,66413452,Yes,Yes,333059160.0,1541560_66413452,66413452_1541560
68,3013721,No,10960412,Yes,Yes,326214114.0,3013721_10960412,10960412_3013721
...,...,...,...,...,...,...,...,...
11975,339993293,No,339993526,Yes,Yes,NaN,339993293_339993526,339993526_339993293
11980,340035665,No,340035133,Yes,Yes,NaN,340035665_340035133,340035133_340035665
11991,340115097,No,340114984,Yes,Yes,NaN,340115097_340114984,340114984_340115097
11997,340152977,No,340152756,Yes,Yes,NaN,340152977_340152756,340152756_340152977
12047,340891948,No,174225580,Yes,Yes,NaN,340891948_174225580,174225580_340891948

In [55]:
partner = of_pt["partner_id"]
partner

24          893936
28         1031674
33        66419503
48        66413452
68        10960412
           ...
11975    339993526
11980    340035133
11991    340114984
11997    340152756
12047    174225580
Name: partner_id, Length: 920, dtype: int64

In [56]:
partner = partner.drop_duplicates()

In [57]:
len(partner)

895

In [60]:
t_f_pairs = ot_pf["id"]
t_f_pairs

5            518909_66466205
7            608490_66465198
9            613368_66464630
10           613370_66464171
12           746116_66463516
                ...
12040    340848497_340848415
12041    340848514_340848415
12042    340848746_340848415
12050    341011035_341186087
12055    341067936_341067932
Name: id, Length: 3087, dtype: str

In [61]:
t_f_pairs = pd.concat([t_f_pairs,of_pt["p_id"]])
t_f_pairs

5            518909_66466205
7            608490_66465198
9            613368_66464630
10           613370_66464171
12           746116_66463516
                ...
11975    339993526_339993293
11980    340035133_340035665
11991    340114984_340115097
11997    340152756_340152977
12047    174225580_340891948
Length: 4007, dtype: str

In [62]:
t_f_pairs = t_f_pairs.drop_duplicates()
t_f_pairs

5            518909_66466205
7            608490_66465198
9            613368_66464630
10           613370_66464171
12           746116_66463516
                ...
7608     250685584_250687006
9733     301221238_301345310
9896     137293784_304288240
9897     137293405_304288869
11449    335078640_335308373
Length: 3098, dtype: str

## obs or partner - true

In [76]:
o_p = dataset[((dataset["obs_match"]=="Yes") & (dataset["par_match"] == "No")) | ((dataset["par_match"]=="Yes") & (dataset["obs_match"]=="No"))]
len(o_p)

4007

# Summary

In [80]:
# Given data
total = 6567
data = {
    "Category": [
        "Both True",
        "One True",
        "Both False"
    ],
    "Count": [
        1969,
        4007,
        591
    ],
    "Total": [
        total,
        total,
        total
    ]
}

# Create DataFrame
summary_df = pd.DataFrame(data)

# Add percentage column
summary_df["Percentage"] = (summary_df["Count"] / total) * 100

# Optional: round percentages
summary_df["Percentage"] = summary_df["Percentage"].round(2)

summary_df

     Category  Count  Total  Percentage
0   Both True   1969   6567       29.98
1    One True   4007   6567       61.02
2  Both False    591   6567        9.00