# Importing Libraries and Setup

In [1]:
import os

os.environ["HF_HOME"] = f"/rs1/researchers/a/amallav/models/hf_home"

os.environ["HF_HUB_CACHE"] = os.path.join(os.environ["HF_HOME"], "hub")
os.environ["HF_HUB_OFFLINE"] = "1"   # only after cache is populated

In [2]:
import json #Used later to store the top-k predictions as a JSON string in the final CSV
from pathlib import Path
import pandas as pd
import torch
from bioclip import TreeOfLifeClassifier, Rank #TreeOfLifeClassifier = the classifier that predicts biological taxa; Rank = tells the classifier what taxonomic level you want

/usr/local/usrapps/ftrscape/snair3/env_AiPipeline/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
# os.environ["PROJECT_DIR"] = "/rs1/researchers/a/amallav/"
# print(os.environ["PROJECT_DIR"])
# os.environ["OUTPUTS_DIR"] = "/rs1/researchers/a/amallav/results"
# print(os.environ["OUTPUTS_DIR"])
# os.environ["OUTPUTS_CP_DIR"] = "/rs1/researchers/a/amallav/results/outputs_crop"
# print(os.environ["OUTPUTS_CP_DIR"])
# os.environ["OUTPUTS_BCCP_DIR"] = "/rs1/researchers/a/amallav/results/outputs_bioclip_crop"
# print(os.environ["OUTPUTS_BCCP_DIR"])

In [ ]:
PROJECT_DIR = Path(os.environ.get("PROJECT_DIR", "/rs1/researchers/a/amallav/")).resolve()
OUTPUTS_DIR=Path(os.environ.get("OUTPUTS_DIR", "/rs1/researchers/a/amallav/results")).resolve()

OUTPUTS_CP_DIR = Path(os.environ.get("OUTPUTS_CP_DIR", OUTPUTS_DIR / "outputs_crop_round2")).resolve()

OUTPUTS_BCCP_DIR = Path(os.environ.get("OUTPUTS_BCCP_DIR", OUTPUTS_DIR / "outputs_bioclip_crop2")).resolve()
OUTPUTS_BCCP_DIR.mkdir(parents=True, exist_ok=True)

# CROP_OUT = PROJECT_DIR / "outputs_crop"
META_CSV = OUTPUTS_CP_DIR / "cropped_metadata.csv" #This is the metadata file that tells us what crop files exist.
OUT_CSV = OUTPUTS_BCCP_DIR / "bioclip_species_predictions.csv"
output_csv = OUTPUTS_BCCP_DIR / "predictions.csv"

print("PROJECT_DIR:", PROJECT_DIR)
print("OUTPUTS_DIR:", OUTPUTS_DIR, "| exists:", OUTPUTS_DIR.exists())
print("OUTPUTS_CP_DIR:", OUTPUTS_CP_DIR, "| exists:", OUTPUTS_CP_DIR.exists())
print("OUTPUTS_BCCP_DIR:", OUTPUTS_BCCP_DIR, "| exists:", OUTPUTS_BCCP_DIR.exists())
print("META_CSV    :", META_CSV, "| exists:", META_CSV.exists())
print("OUT_CSV     :", OUT_CSV, "| exists:", OUT_CSV.exists())
print("output_csv     :", output_csv, "| exists:", output_csv.exists())

PROJECT_DIR: /rs1/researchers/a/amallav
OUTPUTS_DIR: /rs1/researchers/a/amallav/results | exists: True
OUTPUTS_CP_DIR: /rs1/researchers/a/amallav/results/outputs_crop | exists: True
OUTPUTS_BCCP_DIR: /rs1/researchers/a/amallav/results/outputs_bioclip_crop | exists: True
META_CSV    : /rs1/researchers/a/amallav/results/outputs_crop/cropped_metadata.csv | exists: True
OUT_CSV     : /rs1/researchers/a/amallav/results/outputs_bioclip_crop/bioclip_species_predictions.csv | exists: False
output_csv     : /rs1/researchers/a/amallav/results/outputs_bioclip_crop/predictions.csv | exists: True

# Load Bioclip

In [5]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
# model_dir = "/share/ftrscape/{}/models/bioclip".format(__import__("os").environ["USER"])

In [7]:
MODEL_STR = "hf-hub:imageomics/bioclip-2"

TOP_K = 5 #top 5 species predictions for each image
BATCH_SIZE = 1 #This controls how many cropped images are processed at once. Might have to tune this parameter

classifier = TreeOfLifeClassifier(
    device=device,
    model_str=MODEL_STR,
)

print("Device   :", device)
print("Model    :", MODEL_STR)
print("Top-k    :", TOP_K)
print("Batch size:", BATCH_SIZE)

Device   : cuda
Model    : hf-hub:imageomics/bioclip-2
Top-k    : 5
Batch size: 1

# Load CSV

In [12]:
assert META_CSV.exists(), f"metadata.csv not found: {META_CSV}"

meta = pd.read_csv(META_CSV)

required_cols = {"crop_file_path", "crop_file"}
missing_cols = required_cols - set(meta.columns)
assert not missing_cols, f"metadata.csv is missing columns: {missing_cols}"

In [13]:
meta

,original_image,image_path,box_num,image_id,crop_file,crop_file_path,x_min,y_min,x_max,y_max
0,obs_10003229_photo_114145431.jpg,/rs1/researchers/a/amallav/image_dataset/obs_1...,1,obs_10003229_photo_114145431,obs_10003229_photo_114145431_box1.jpg,/rs1/researchers/a/amallav/results/outputs_cro...,192,1,1053,987
1,obs_10003229_photo_114145431.jpg,/rs1/researchers/a/amallav/image_dataset/obs_1...,2,obs_10003229_photo_114145431,obs_10003229_photo_114145431_box2.jpg,/rs1/researchers/a/amallav/results/outputs_cro...,277,94,1030,783
2,obs_10003229_photo_114145431.jpg,/rs1/researchers/a/amallav/image_dataset/obs_1...,3,obs_10003229_photo_114145431,obs_10003229_photo_114145431_box3.jpg,/rs1/researchers/a/amallav/results/outputs_cro...,281,95,927,772
3,obs_10003229_photo_114145431.jpg,/rs1/researchers/a/amallav/image_dataset/obs_1...,4,obs_10003229_photo_114145431,obs_10003229_photo_114145431_box4.jpg,/rs1/researchers/a/amallav/results/outputs_cro...,185,6,1055,786
4,obs_10003229_photo_114145431.jpg,/rs1/researchers/a/amallav/image_dataset/obs_1...,5,obs_10003229_photo_114145431,obs_10003229_photo_114145431_box5.jpg,/rs1/researchers/a/amallav/results/outputs_cro...,284,98,901,764
...,...,...,...,...,...,...,...,...,...,...
74744,obs_99990956_photo_166796339.jpg,/rs1/researchers/a/amallav/image_dataset/obs_9...,2,obs_99990956_photo_166796339,obs_99990956_photo_166796339_box2.jpg,/rs1/researchers/a/amallav/results/outputs_cro...,180,46,1681,1733
74745,obs_99990956_photo_166796339.jpg,/rs1/researchers/a/amallav/image_dataset/obs_9...,3,obs_99990956_photo_166796339,obs_99990956_photo_166796339_box3.jpg,/rs1/researchers/a/amallav/results/outputs_cro...,191,613,1599,1723
74746,obs_99990956_photo_166796339.jpg,/rs1/researchers/a/amallav/image_dataset/obs_9...,4,obs_99990956_photo_166796339,obs_99990956_photo_166796339_box4.jpg,/rs1/researchers/a/amallav/results/outputs_cro...,192,585,1598,1719
74747,obs_99990956_photo_166796345.jpg,/rs1/researchers/a/amallav/image_dataset/obs_9...,1,obs_99990956_photo_166796345,obs_99990956_photo_166796345_box1.jpg,/rs1/researchers/a/amallav/results/outputs_cro...,660,94,1644,1436
74748,obs_99990956_photo_166796345.jpg,/rs1/researchers/a/amallav/image_dataset/obs_9...,2,obs_99990956_photo_166796345,obs_99990956_photo_166796345_box2.jpg,/rs1/researchers/a/amallav/results/outputs_cro...,659,87,1646,1451

In [14]:
# #converts paths into absolute paths.
# def resolve_path(p):
#     if pd.isna(p):
#         return None
#     p = str(p).strip()
#     if os.path.isabs(p):
#         return p
#     return str((PROJECT_DIR / p).resolve())

# meta["masked_crop_path"] = meta["masked_crop_path"].apply(resolve_path)

In [15]:
meta = meta[meta["crop_file_path"].notna()].copy() #remove rows where crop path is missing
meta["crop_exists"] = meta["crop_file_path"].apply(os.path.exists)

missing_count = (~meta["crop_exists"]).sum()
if missing_count > 0:
    print(f"Skipping {missing_count} rows because crop file does not exist.")

meta = meta[meta["crop_exists"]].copy()  #only rows where the crop file actually exists.

Skipping 3 rows because crop file does not exist.

In [16]:
keep_cols = ["crop_file", "crop_file_path", "image_id"]
if "box_num" in meta.columns:
    keep_cols.append("box_num")

crop_df = meta[keep_cols].drop_duplicates(subset=["crop_file_path"]).reset_index(drop=True) #creates a clean crop table without deduplicates

print("Total valid cropped images:", len(crop_df))
crop_df.head()

Total valid cropped images: 74746

,crop_file,crop_file_path,image_id,box_num
0,obs_10003229_photo_114145431_box1.jpg,/rs1/researchers/a/amallav/results/outputs_cro...,obs_10003229_photo_114145431,1
1,obs_10003229_photo_114145431_box2.jpg,/rs1/researchers/a/amallav/results/outputs_cro...,obs_10003229_photo_114145431,2
2,obs_10003229_photo_114145431_box3.jpg,/rs1/researchers/a/amallav/results/outputs_cro...,obs_10003229_photo_114145431,3
3,obs_10003229_photo_114145431_box4.jpg,/rs1/researchers/a/amallav/results/outputs_cro...,obs_10003229_photo_114145431,4
4,obs_10003229_photo_114145431_box5.jpg,/rs1/researchers/a/amallav/results/outputs_cro...,obs_10003229_photo_114145431,5

# Run species classification on all cropped images

In [13]:
# test = classifier.predict(
#     images="/gpfs_common/share03/ftrscape/snair3/wew_notebooks/outputs_crop/obs_250956763_photo_448935283_box2_copy.JPG",
#     rank=Rank.SPECIES, #Predict at species level.
#     k=TOP_K, #Return the top 5 predictions for each image.
#     batch_size=BATCH_SIZE, #Process 1 image at a time.
# )
# test_df=pd.DataFrame(test)

# # print("Total prediction rows:", len(pred_df))
# test_df.head()

In [13]:
# crop_paths = crop_df["crop_file_path"].tolist() #Collect all crop image paths into a list.

# predictions = classifier.predict(
#     images=crop_paths, #Pass the cropped image files to the model.
#     rank=Rank.SPECIES, #Predict at species level.
#     k=TOP_K, #Return the top 5 predictions for each image.
#     batch_size=BATCH_SIZE, #Process 1 image at a time.
# )

# pred_df = pd.DataFrame(predictions) #Turns the prediction output into a table.

# print("Total prediction rows:", len(pred_df))
# pred_df.head()

100%|██████████| 318/318 [00:18<00:00, 17.45images/s]

Total prediction rows: 1590

,file_name,kingdom,phylum,class,order,family,genus,species_epithet,species,common_name,score
0,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Echinodermata,Asteroidea,Valvatida,Odontasteridae,Odontaster,penicillatus,Odontaster penicillatus,,0.060668
1,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Echinodermata,Asteroidea,Valvatida,Goniasteridae,Ceramaster,japonicus,Ceramaster japonicus,Bat star,0.060482
2,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Echinodermata,Asteroidea,Valvatida,Goniasteridae,Stellaster,princeps,Stellaster princeps,,0.055059
3,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Echinodermata,Asteroidea,Valvatida,Asteropseidae,Dermasterias,imbricata,Dermasterias imbricata,,0.044492
4,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Echinodermata,Asteroidea,Paxillosida,Astropectinidae,Dipsacaster,pretiosus,Dipsacaster pretiosus,,0.042861

In [14]:



# Create CSV with header only once

if not os.path.exists(output_csv):
    empty_df = pd.DataFrame(columns=[
        "file_name",
        "kingdom",
        "phylum",
        "class",
        "order",
        "family",
        "genus",
        "species_epithet",
        "species",
        "common_name",
        "score",
        "path",
        "id"
    ])
    empty_df.to_csv(output_csv, index=False)


for idx, row in crop_df.iterrows():
    crop_path = row["crop_file_path"]

    # Run prediction for ONE image
    prediction = classifier.predict(
        images=[crop_path],           # single image
        rank=Rank.SPECIES,
        k=TOP_K,
        batch_size=1
    )

    # Convert to DataFrame
    pred_df = pd.DataFrame(prediction)

    # (Optional) keep track of source image
    pred_df["crop_file_path"] = crop_path
    pred_df["crop_index"] = idx

    # Append to CSV (no header after first time)
    pred_df.to_csv(
        output_csv,
        mode="a",
        header=not os.path.getsize(output_csv),
        index=False
    )

    print(f"✅ Processed {crop_path} - {idx + 1}/{len(crop_df)}")

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10003229_photo_114145431_box1.jpg - 1/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10003229_photo_114145431_box2.jpg - 2/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10003229_photo_114145431_box3.jpg - 3/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10003229_photo_114145431_box4.jpg - 4/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10003229_photo_114145431_box5.jpg - 5/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100052837_photo_166933111_box1.jpg - 6/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100052837_photo_166933111_box2.jpg - 7/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100052837_photo_166933111_box3.jpg - 8/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100052837_photo_166933111_box4.jpg - 9/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100052837_photo_166933119_box1.jpg - 10/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100052837_photo_166933119_box2.jpg - 11/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100052837_photo_166933119_box3.jpg - 12/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100052837_photo_166933119_box4.jpg - 13/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100052837_photo_166933119_box5.jpg - 14/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100052837_photo_166933123_box1.jpg - 15/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100053359_photo_166934121_box1.jpg - 16/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100053359_photo_166934128_box1.jpg - 17/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100053594_photo_166934121_box1.jpg - 18/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100053594_photo_166934128_box1.jpg - 19/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100053594_photo_166934128_box2.jpg - 20/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100060648_photo_166948151_box1.jpg - 21/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100125424_photo_167070208_box1.jpg - 22/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100125424_photo_167070213_box1.jpg - 23/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100125750_photo_167070850_box1.jpg - 24/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100125750_photo_167070857_box1.jpg - 25/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100125750_photo_167070857_box2.jpg - 26/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100126056_photo_167071230_box1.jpg - 27/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100126056_photo_167071230_box2.jpg - 28/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100126056_photo_167071230_box3.jpg - 29/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100126056_photo_167071230_box4.jpg - 30/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100126056_photo_167071230_box5.jpg - 31/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.41images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100126348_photo_167071797_box1.jpg - 32/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100126348_photo_167071797_box2.jpg - 33/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100126348_photo_167071805_box1.jpg - 34/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100126348_photo_167071806_box1.jpg - 35/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100157926_photo_167125946_box1.jpg - 36/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100157926_photo_167125946_box2.jpg - 37/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100157926_photo_167125946_box3.jpg - 38/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100157926_photo_167125946_box4.jpg - 39/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100157926_photo_167125946_box5.jpg - 40/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100157926_photo_167125959_box1.jpg - 41/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100157926_photo_167125959_box2.jpg - 42/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100157926_photo_167125959_box3.jpg - 43/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100157926_photo_167125959_box4.jpg - 44/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100157926_photo_167125959_box5.jpg - 45/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100191270_photo_167181731_box1.jpg - 46/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100191271_photo_167181731_box1.jpg - 47/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100191271_photo_167181731_box2.jpg - 48/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213596_photo_167226150_box1.jpg - 49/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213596_photo_167226150_box2.jpg - 50/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213596_photo_167226150_box3.jpg - 51/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213596_photo_167226150_box4.jpg - 52/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213596_photo_167226150_box5.jpg - 53/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213596_photo_167226155_box1.jpg - 54/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213596_photo_167226155_box2.jpg - 55/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213596_photo_167226155_box3.jpg - 56/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213596_photo_167226158_box1.jpg - 57/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213596_photo_167226158_box2.jpg - 58/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213596_photo_167226162_box1.jpg - 59/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213596_photo_167226162_box2.jpg - 60/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213596_photo_167226162_box3.jpg - 61/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213596_photo_167226162_box4.jpg - 62/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213596_photo_167226162_box5.jpg - 63/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213691_photo_167226150_box1.jpg - 64/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213691_photo_167226150_box2.jpg - 65/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213691_photo_167226150_box3.jpg - 66/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213691_photo_167226155_box1.jpg - 67/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213691_photo_167226155_box2.jpg - 68/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213691_photo_167226155_box3.jpg - 69/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 49.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213691_photo_167226155_box4.jpg - 70/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213691_photo_167226155_box5.jpg - 71/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213691_photo_167226158_box1.jpg - 72/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213691_photo_167226162_box1.jpg - 73/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100213691_photo_167226162_box2.jpg - 74/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100218796_photo_167235360_box1.jpg - 75/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100218796_photo_167235370_box1.jpg - 76/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100218796_photo_167235370_box2.jpg - 77/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 49.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100218796_photo_167235378_box1.jpg - 78/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100218796_photo_167235378_box2.jpg - 79/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100314445_photo_167409998_box1.jpg - 80/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100314445_photo_167410014_box1.jpg - 81/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100314445_photo_167410014_box2.jpg - 82/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100314445_photo_167410014_box3.jpg - 83/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100314445_photo_167410014_box4.jpg - 84/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100314445_photo_167410014_box5.jpg - 85/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100314445_photo_167410029_box1.jpg - 86/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100314445_photo_167410029_box2.jpg - 87/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100314445_photo_167410029_box3.jpg - 88/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100414094_photo_167589364_box1.jpg - 89/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100414094_photo_167589364_box2.jpg - 90/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100414094_photo_167589364_box3.jpg - 91/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100414094_photo_167589364_box4.jpg - 92/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100414094_photo_167589364_box5.jpg - 93/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10042362_photo_13817684_box1.jpg - 94/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10042362_photo_13817684_box2.jpg - 95/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10042362_photo_13817684_box3.jpg - 96/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10042362_photo_13817684_box4.jpg - 97/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10042362_photo_13817684_box5.jpg - 98/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10042362_photo_13817685_box1.jpg - 99/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10042362_photo_13817687_box1.jpg - 100/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10042362_photo_13817687_box2.jpg - 101/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10042362_photo_13817687_box3.jpg - 102/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10042362_photo_13817687_box4.jpg - 103/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100565863_photo_167866385_box1.jpg - 104/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922022_box1.jpg - 105/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922022_box2.jpg - 106/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922046_box1.jpg - 107/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922046_box2.jpg - 108/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922046_box3.jpg - 109/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922046_box4.jpg - 110/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922061_box1.jpg - 111/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922061_box2.jpg - 112/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922061_box3.jpg - 113/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922061_box4.jpg - 114/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922061_box5.jpg - 115/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922069_box1.jpg - 116/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922069_box2.jpg - 117/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922069_box3.jpg - 118/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922069_box4.jpg - 119/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922069_box5.jpg - 120/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.31images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922076_box1.jpg - 121/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922076_box2.jpg - 122/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922076_box3.jpg - 123/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922076_box4.jpg - 124/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922076_box5.jpg - 125/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922081_box1.jpg - 126/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922081_box2.jpg - 127/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922081_box3.jpg - 128/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922081_box4.jpg - 129/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922081_box5.jpg - 130/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922088_box1.jpg - 131/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922088_box2.jpg - 132/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922088_box3.jpg - 133/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922097_box1.jpg - 134/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.95images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922097_box2.jpg - 135/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922097_box3.jpg - 136/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922097_box4.jpg - 137/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 46.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598485_photo_167922097_box5.jpg - 138/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598802_photo_167922439_box1.jpg - 139/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598802_photo_167922439_box2.jpg - 140/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598802_photo_167922531_box1.jpg - 141/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598802_photo_167922531_box2.jpg - 142/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598802_photo_167922551_box1.jpg - 143/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598802_photo_167922551_box2.jpg - 144/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598802_photo_167922551_box3.jpg - 145/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598803_photo_167922449_box1.jpg - 146/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598803_photo_167922449_box2.jpg - 147/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598803_photo_167922449_box3.jpg - 148/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598803_photo_167922449_box4.jpg - 149/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598803_photo_167922449_box5.jpg - 150/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598803_photo_167922543_box1.jpg - 151/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598803_photo_167922550_box1.jpg - 152/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598803_photo_167922550_box2.jpg - 153/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100598803_photo_167922550_box3.jpg - 154/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100600106_photo_167925209_box1.jpg - 155/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100600106_photo_167925209_box2.jpg - 156/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100600106_photo_167925209_box3.jpg - 157/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100600106_photo_167925209_box4.jpg - 158/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100600106_photo_167925209_box5.jpg - 159/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100600106_photo_167925218_box1.jpg - 160/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100600106_photo_167925218_box2.jpg - 161/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100600106_photo_167925218_box3.jpg - 162/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100600106_photo_167925218_box4.jpg - 163/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100600106_photo_167925218_box5.jpg - 164/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100600106_photo_167925221_box1.jpg - 165/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 74.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100600106_photo_167925221_box2.jpg - 166/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100600106_photo_167925221_box3.jpg - 167/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100600106_photo_167925221_box4.jpg - 168/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100600106_photo_167925221_box5.jpg - 169/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100627129_photo_167951144_box1.jpg - 170/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100627129_photo_167951144_box2.jpg - 171/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100627129_photo_167951144_box3.jpg - 172/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100627129_photo_167951144_box4.jpg - 173/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100627129_photo_167951144_box5.jpg - 174/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100627129_photo_167965613_box1.jpg - 175/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100627129_photo_167965613_box2.jpg - 176/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100627129_photo_167965613_box3.jpg - 177/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.31images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100627129_photo_167967058_box1.jpg - 178/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100627129_photo_167967070_box1.jpg - 179/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100627169_photo_167964347_box1.jpg - 180/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100627169_photo_167964347_box2.jpg - 181/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100627169_photo_167964351_box1.jpg - 182/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 74.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100627169_photo_167964351_box2.jpg - 183/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100627169_photo_167965404_box1.jpg - 184/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100627169_photo_167965404_box2.jpg - 185/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100627169_photo_167966711_box1.jpg - 186/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100682402_photo_168070638_box1.jpg - 187/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100682402_photo_168070638_box2.jpg - 188/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100682402_photo_168070638_box3.jpg - 189/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100682402_photo_168070638_box4.jpg - 190/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100682402_photo_168070638_box5.jpg - 191/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100682403_photo_168070635_box1.jpg - 192/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100682403_photo_168070635_box2.jpg - 193/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100682403_photo_168070635_box3.jpg - 194/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100682403_photo_168070635_box4.jpg - 195/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100682403_photo_168070635_box5.jpg - 196/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708606_photo_168095355_box1.jpg - 197/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708606_photo_168095355_box2.jpg - 198/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708606_photo_168095355_box3.jpg - 199/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708607_photo_168095395_box1.jpg - 200/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708607_photo_168095395_box2.jpg - 201/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708607_photo_168095395_box3.jpg - 202/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.95images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708607_photo_168095395_box4.jpg - 203/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708607_photo_168095395_box5.jpg - 204/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708626_photo_168097613_box1.jpg - 205/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708626_photo_168097613_box2.jpg - 206/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708626_photo_168097613_box3.jpg - 207/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708626_photo_168097613_box4.jpg - 208/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708626_photo_168097613_box5.jpg - 209/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708626_photo_168097614_box1.jpg - 210/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708626_photo_168097614_box2.jpg - 211/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708626_photo_168097614_box3.jpg - 212/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708626_photo_168097636_box1.jpg - 213/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708626_photo_168097636_box2.jpg - 214/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708626_photo_168097660_box1.jpg - 215/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708626_photo_168097660_box2.jpg - 216/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708626_photo_168097660_box3.jpg - 217/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708626_photo_168097660_box4.jpg - 218/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708626_photo_168097660_box5.jpg - 219/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168099140_box1.jpg - 220/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168099140_box2.jpg - 221/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168099140_box3.jpg - 222/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168099407_box1.jpg - 223/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168099407_box2.jpg - 224/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168099407_box3.jpg - 225/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168099416_box1.jpg - 226/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168099416_box2.jpg - 227/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168099416_box3.jpg - 228/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168099416_box4.jpg - 229/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168099416_box5.jpg - 230/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168099474_box1.jpg - 231/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168099474_box2.jpg - 232/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168099474_box3.jpg - 233/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168099474_box4.jpg - 234/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168099474_box5.jpg - 235/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168099497_box1.jpg - 236/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168099497_box2.jpg - 237/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168099497_box3.jpg - 238/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168099497_box4.jpg - 239/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168099497_box5.jpg - 240/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168099890_box1.jpg - 241/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168099890_box2.jpg - 242/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168100612_box1.jpg - 243/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168100612_box2.jpg - 244/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168100612_box3.jpg - 245/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708632_photo_168100612_box4.jpg - 246/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708634_photo_168099317_box1.jpg - 247/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708634_photo_168099317_box2.jpg - 248/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708634_photo_168099317_box3.jpg - 249/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708634_photo_168099317_box4.jpg - 250/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708634_photo_168099326_box1.jpg - 251/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708634_photo_168099331_box1.jpg - 252/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708634_photo_168099331_box2.jpg - 253/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708634_photo_168099335_box1.jpg - 254/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708634_photo_168099354_box1.jpg - 255/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708634_photo_168099367_box1.jpg - 256/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708634_photo_168099367_box2.jpg - 257/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708634_photo_168099367_box3.jpg - 258/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708634_photo_168099457_box1.jpg - 259/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708634_photo_168099457_box2.jpg - 260/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708634_photo_168099457_box3.jpg - 261/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708634_photo_168099457_box4.jpg - 262/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100708634_photo_168099457_box5.jpg - 263/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786782_photo_168246053_box1.jpg - 264/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786782_photo_168246053_box2.jpg - 265/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786782_photo_168246053_box3.jpg - 266/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786782_photo_168246053_box4.jpg - 267/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786782_photo_168246053_box5.jpg - 268/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786782_photo_168246100_box1.jpg - 269/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786782_photo_168246100_box2.jpg - 270/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786782_photo_168246100_box3.jpg - 271/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786782_photo_168246100_box4.jpg - 272/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786782_photo_168246100_box5.jpg - 273/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786782_photo_168246131_box1.jpg - 274/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786782_photo_168246131_box2.jpg - 275/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786782_photo_168246131_box3.jpg - 276/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786782_photo_168246131_box4.jpg - 277/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786782_photo_168246131_box5.jpg - 278/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786786_photo_168246124_box1.jpg - 279/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786786_photo_168246124_box2.jpg - 280/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786786_photo_168246124_box3.jpg - 281/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786786_photo_168246135_box1.jpg - 282/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786786_photo_168246135_box2.jpg - 283/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786786_photo_168246135_box3.jpg - 284/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786786_photo_168246135_box4.jpg - 285/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786786_photo_168246135_box5.jpg - 286/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786786_photo_168246185_box1.jpg - 287/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786786_photo_168246185_box2.jpg - 288/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786786_photo_168246185_box3.jpg - 289/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786786_photo_168246185_box4.jpg - 290/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786786_photo_168246185_box5.jpg - 291/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786786_photo_168246194_box1.jpg - 292/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786786_photo_168246194_box2.jpg - 293/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786786_photo_168246194_box3.jpg - 294/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786786_photo_168246194_box4.jpg - 295/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786786_photo_168246227_box1.jpg - 296/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786786_photo_168246227_box2.jpg - 297/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786786_photo_168246227_box3.jpg - 298/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786786_photo_168246227_box4.jpg - 299/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100786786_photo_168246227_box5.jpg - 300/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876503_photo_168403487_box1.jpg - 301/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876503_photo_168403487_box2.jpg - 302/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876503_photo_168403487_box3.jpg - 303/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876503_photo_168403487_box4.jpg - 304/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876503_photo_168403487_box5.jpg - 305/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876503_photo_168403499_box1.jpg - 306/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876503_photo_168403499_box2.jpg - 307/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876503_photo_168403499_box3.jpg - 308/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876503_photo_168403499_box4.jpg - 309/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876503_photo_168403499_box5.jpg - 310/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876503_photo_168403510_box1.jpg - 311/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876503_photo_168403510_box2.jpg - 312/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876503_photo_168403510_box3.jpg - 313/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876503_photo_168403510_box4.jpg - 314/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876503_photo_168403510_box5.jpg - 315/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876506_photo_168403521_box1.jpg - 316/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876506_photo_168403528_box1.jpg - 317/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876506_photo_168403528_box2.jpg - 318/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876506_photo_168403528_box3.jpg - 319/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876506_photo_168403528_box4.jpg - 320/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876506_photo_168403538_box1.jpg - 321/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876506_photo_168403538_box2.jpg - 322/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876506_photo_168403538_box3.jpg - 323/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876506_photo_168403538_box4.jpg - 324/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876506_photo_168403552_box1.jpg - 325/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876506_photo_168403552_box2.jpg - 326/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100876506_photo_168403552_box3.jpg - 327/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100952210_photo_168541359_box1.jpg - 328/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100952316_photo_168541530_box1.jpg - 329/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100952316_photo_168541530_box2.jpg - 330/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100952316_photo_168541530_box3.jpg - 331/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100952316_photo_168541536_box1.jpg - 332/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100952316_photo_168541536_box2.jpg - 333/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100952316_photo_168541544_box1.jpg - 334/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100952316_photo_168541544_box2.jpg - 335/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_100952316_photo_168541544_box3.jpg - 336/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101073652_photo_168757717_box1.jpg - 337/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101073652_photo_168757717_box2.jpg - 338/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101073652_photo_168757717_box3.jpg - 339/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101074371_photo_168759122_box1.jpg - 340/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101074371_photo_168759122_box2.jpg - 341/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101074371_photo_168759122_box3.jpg - 342/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101074371_photo_168759122_box4.jpg - 343/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101074371_photo_168759122_box5.jpg - 344/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101074371_photo_168759127_box1.jpg - 345/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101074371_photo_168759127_box2.jpg - 346/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101074747_photo_168759696_box1.jpg - 347/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 46.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101074747_photo_168759696_box2.jpg - 348/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101074747_photo_168759696_box3.jpg - 349/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101074747_photo_168759696_box4.jpg - 350/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101074747_photo_168759696_box5.jpg - 351/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101074747_photo_168759703_box1.jpg - 352/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101074747_photo_168759703_box2.jpg - 353/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101074747_photo_168759703_box3.jpg - 354/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101074747_photo_168759703_box4.jpg - 355/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101074747_photo_168759703_box5.jpg - 356/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101074747_photo_168759708_box1.jpg - 357/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101074747_photo_168759708_box2.jpg - 358/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101074747_photo_168759708_box3.jpg - 359/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101074747_photo_168759708_box4.jpg - 360/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101074747_photo_168759708_box5.jpg - 361/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101078740_photo_168766885_box1.jpg - 362/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.31images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101078740_photo_168766885_box2.jpg - 363/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101078740_photo_168766885_box3.jpg - 364/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101078740_photo_168766885_box4.jpg - 365/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101078740_photo_168766897_box1.jpg - 366/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101078740_photo_168766897_box2.jpg - 367/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101078740_photo_168766897_box3.jpg - 368/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101078740_photo_168766897_box4.jpg - 369/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101078740_photo_168766897_box5.jpg - 370/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101078740_photo_168767240_box1.jpg - 371/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101078740_photo_168767240_box2.jpg - 372/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101078740_photo_168767240_box3.jpg - 373/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101078740_photo_168767240_box4.jpg - 374/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101078740_photo_168767240_box5.jpg - 375/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101078740_photo_168767247_box1.jpg - 376/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101078740_photo_168767247_box2.jpg - 377/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 74.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101078740_photo_168767247_box3.jpg - 378/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101078740_photo_168767247_box4.jpg - 379/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101078740_photo_168767247_box5.jpg - 380/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101255856_photo_169080756_box1.jpg - 381/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 49.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101255856_photo_169080756_box2.jpg - 382/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101255856_photo_169080773_box1.jpg - 383/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101255856_photo_169080783_box1.jpg - 384/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101255856_photo_169080790_box1.jpg - 385/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101255856_photo_169080790_box2.jpg - 386/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101255856_photo_169080794_box1.jpg - 387/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101255862_photo_169080802_box1.jpg - 388/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101255862_photo_169080806_box1.jpg - 389/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101255862_photo_169080806_box2.jpg - 390/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101261887_photo_169093147_box1.jpg - 391/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362060_box1.jpg - 392/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362060_box2.jpg - 393/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362060_box3.jpg - 394/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362060_box4.jpg - 395/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362060_box5.jpg - 396/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362080_box1.jpg - 397/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362080_box2.jpg - 398/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362080_box3.jpg - 399/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362080_box4.jpg - 400/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362080_box5.jpg - 401/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362091_box1.jpg - 402/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362091_box2.jpg - 403/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362091_box3.jpg - 404/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362091_box4.jpg - 405/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362091_box5.jpg - 406/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362104_box1.jpg - 407/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362104_box2.jpg - 408/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362104_box3.jpg - 409/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362104_box4.jpg - 410/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362104_box5.jpg - 411/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.41images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362114_box1.jpg - 412/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362114_box2.jpg - 413/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 46.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362114_box3.jpg - 414/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362114_box4.jpg - 415/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412590_photo_169362114_box5.jpg - 416/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412591_photo_169362122_box1.jpg - 417/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412591_photo_169362122_box2.jpg - 418/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412591_photo_169362140_box1.jpg - 419/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412591_photo_169362140_box2.jpg - 420/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412591_photo_169362140_box3.jpg - 421/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412591_photo_169362140_box4.jpg - 422/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412591_photo_169362140_box5.jpg - 423/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412591_photo_169362144_box1.jpg - 424/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412591_photo_169362144_box2.jpg - 425/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412591_photo_169362144_box3.jpg - 426/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412591_photo_169362144_box4.jpg - 427/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412591_photo_169362144_box5.jpg - 428/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412591_photo_169362157_box1.jpg - 429/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412591_photo_169362157_box2.jpg - 430/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412591_photo_169362157_box3.jpg - 431/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412591_photo_169362157_box4.jpg - 432/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101412591_photo_169362157_box5.jpg - 433/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101430193_photo_169392001_box1.jpg - 434/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101447157_photo_169427831_box1.jpg - 435/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101447157_photo_169427831_box2.jpg - 436/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101447157_photo_169427839_box1.jpg - 437/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101447157_photo_169427839_box2.jpg - 438/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10150273_photo_14005914_box1.jpg - 439/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10150273_photo_14005914_box2.jpg - 440/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10150273_photo_14005914_box3.jpg - 441/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10150273_photo_14005914_box4.jpg - 442/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10150273_photo_14005914_box5.jpg - 443/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101526283_photo_169560315_box1.jpg - 444/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101526283_photo_169560322_box1.jpg - 445/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101526283_photo_169560322_box2.jpg - 446/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101526283_photo_169560332_box1.jpg - 447/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101526283_photo_169560332_box2.jpg - 448/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101526283_photo_169560335_box1.jpg - 449/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101526283_photo_169560335_box2.jpg - 450/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101526283_photo_169560352_box1.jpg - 451/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101526283_photo_169560352_box2.jpg - 452/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101526283_photo_169560567_box1.jpg - 453/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101526283_photo_169560567_box2.jpg - 454/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101526283_photo_169560567_box3.jpg - 455/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101526283_photo_169560567_box4.jpg - 456/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101526283_photo_169560567_box5.jpg - 457/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101530597_photo_169579514_box1.jpg - 458/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101530597_photo_169579514_box2.jpg - 459/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101530597_photo_169579514_box3.jpg - 460/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101530597_photo_169579514_box4.jpg - 461/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101530597_photo_169579514_box5.jpg - 462/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101530597_photo_169579515_box1.jpg - 463/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101530597_photo_169579515_box2.jpg - 464/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101530597_photo_169579515_box3.jpg - 465/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.95images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101530597_photo_169579515_box4.jpg - 466/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101530597_photo_169579515_box5.jpg - 467/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101530597_photo_169579519_box1.jpg - 468/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101530597_photo_169579519_box2.jpg - 469/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101530597_photo_169579519_box3.jpg - 470/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.41images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101530597_photo_169579519_box4.jpg - 471/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101530597_photo_169579519_box5.jpg - 472/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101530597_photo_169579952_box1.jpg - 473/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101530597_photo_169579952_box2.jpg - 474/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101530597_photo_169579952_box3.jpg - 475/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10155097_photo_14012620_box1.jpg - 476/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10155097_photo_14012620_box2.jpg - 477/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10155097_photo_14012620_box3.jpg - 478/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101592881_photo_169684775_box1.jpg - 479/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101592881_photo_169684775_box2.jpg - 480/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101969101_photo_170363661_box1.jpg - 481/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417243_box1.jpg - 482/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417243_box2.jpg - 483/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417243_box3.jpg - 484/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417245_box1.jpg - 485/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 49.95images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417245_box2.jpg - 486/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417255_box1.jpg - 487/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417257_box1.jpg - 488/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417257_box2.jpg - 489/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417270_box1.jpg - 490/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417270_box2.jpg - 491/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417270_box3.jpg - 492/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417270_box4.jpg - 493/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417271_box1.jpg - 494/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417271_box2.jpg - 495/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 74.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417271_box3.jpg - 496/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 74.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417271_box4.jpg - 497/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417271_box5.jpg - 498/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417299_box1.jpg - 499/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417299_box2.jpg - 500/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417314_box1.jpg - 501/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417314_box2.jpg - 502/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417314_box3.jpg - 503/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417314_box4.jpg - 504/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417318_box1.jpg - 505/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417318_box2.jpg - 506/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 49.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417318_box3.jpg - 507/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 46.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417335_box1.jpg - 508/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417335_box2.jpg - 509/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417335_box3.jpg - 510/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417347_box1.jpg - 511/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 46.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417352_box1.jpg - 512/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417352_box2.jpg - 513/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417356_box1.jpg - 514/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.31images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417356_box2.jpg - 515/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417364_box1.jpg - 516/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417364_box2.jpg - 517/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101996533_photo_170417364_box3.jpg - 518/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422009_box1.jpg - 519/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422009_box2.jpg - 520/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422011_box1.jpg - 521/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 77.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422011_box2.jpg - 522/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 63.31images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422011_box3.jpg - 523/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422029_box1.jpg - 524/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422029_box2.jpg - 525/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422033_box1.jpg - 526/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422033_box2.jpg - 527/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422034_box1.jpg - 528/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422034_box2.jpg - 529/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422042_box1.jpg - 530/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422042_box2.jpg - 531/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422043_box1.jpg - 532/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422043_box2.jpg - 533/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422050_box1.jpg - 534/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422050_box2.jpg - 535/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422050_box3.jpg - 536/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422053_box1.jpg - 537/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422057_box1.jpg - 538/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422057_box2.jpg - 539/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422057_box3.jpg - 540/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 75.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422057_box4.jpg - 541/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422060_box1.jpg - 542/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422064_box1.jpg - 543/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422064_box2.jpg - 544/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422072_box1.jpg - 545/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422072_box2.jpg - 546/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422072_box3.jpg - 547/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422073_box1.jpg - 548/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422073_box2.jpg - 549/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422073_box3.jpg - 550/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422080_box1.jpg - 551/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422080_box2.jpg - 552/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422080_box3.jpg - 553/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422082_box1.jpg - 554/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422082_box2.jpg - 555/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422082_box3.jpg - 556/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422085_box1.jpg - 557/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422087_box1.jpg - 558/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422087_box2.jpg - 559/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422087_box3.jpg - 560/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422087_box4.jpg - 561/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422087_box5.jpg - 562/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422090_box1.jpg - 563/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422090_box2.jpg - 564/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422090_box3.jpg - 565/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 49.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422093_box1.jpg - 566/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422093_box2.jpg - 567/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422093_box3.jpg - 568/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422492_box1.jpg - 569/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422498_box1.jpg - 570/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 49.41images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422503_box1.jpg - 571/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_101998671_photo_170422503_box2.jpg - 572/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102008783_photo_170441160_box1.jpg - 573/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102008783_photo_170441160_box2.jpg - 574/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102008783_photo_170441160_box3.jpg - 575/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102008783_photo_170441160_box4.jpg - 576/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102008783_photo_170441160_box5.jpg - 577/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102008783_photo_170441215_box1.jpg - 578/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.95images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102008783_photo_170441221_box1.jpg - 579/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102008783_photo_170441221_box2.jpg - 580/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102008783_photo_170441221_box3.jpg - 581/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102008783_photo_170441221_box4.jpg - 582/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102008783_photo_170441221_box5.jpg - 583/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021841_photo_170463907_box1.jpg - 584/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021841_photo_170463907_box2.jpg - 585/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021841_photo_170463907_box3.jpg - 586/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021841_photo_170463922_box1.jpg - 587/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021841_photo_170463922_box2.jpg - 588/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021841_photo_170463922_box3.jpg - 589/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021841_photo_170463922_box4.jpg - 590/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021841_photo_170463957_box1.jpg - 591/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021841_photo_170463957_box2.jpg - 592/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021841_photo_170463957_box3.jpg - 593/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021841_photo_170463957_box4.jpg - 594/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021841_photo_170463990_box1.jpg - 595/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021841_photo_170463990_box2.jpg - 596/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021841_photo_170463990_box3.jpg - 597/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021841_photo_170463990_box4.jpg - 598/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.41images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021841_photo_170463998_box1.jpg - 599/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021841_photo_170463998_box2.jpg - 600/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021841_photo_170464003_box1.jpg - 601/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021841_photo_170464003_box2.jpg - 602/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021843_photo_170464019_box1.jpg - 603/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021843_photo_170464023_box1.jpg - 604/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021843_photo_170464023_box2.jpg - 605/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021843_photo_170464033_box1.jpg - 606/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021843_photo_170464033_box2.jpg - 607/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102021843_photo_170464033_box3.jpg - 608/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616221_box1.jpg - 609/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616221_box2.jpg - 610/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616221_box3.jpg - 611/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616221_box4.jpg - 612/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616221_box5.jpg - 613/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616275_box1.jpg - 614/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616275_box2.jpg - 615/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616344_box1.jpg - 616/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616344_box2.jpg - 617/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616357_box1.jpg - 618/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616357_box2.jpg - 619/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616357_box3.jpg - 620/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616366_box1.jpg - 621/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616366_box2.jpg - 622/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.95images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616366_box3.jpg - 623/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616366_box4.jpg - 624/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616432_box1.jpg - 625/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616432_box2.jpg - 626/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616432_box3.jpg - 627/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616458_box1.jpg - 628/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616458_box2.jpg - 629/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616458_box3.jpg - 630/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616458_box4.jpg - 631/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616458_box5.jpg - 632/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102103780_photo_170616522_box1.jpg - 633/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102328947_photo_171027264_box1.jpg - 634/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102328947_photo_171027264_box2.jpg - 635/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102328947_photo_171027264_box3.jpg - 636/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102328947_photo_171027264_box4.jpg - 637/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102328947_photo_171027264_box5.jpg - 638/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10248122_photo_14174796_box1.jpg - 639/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10248122_photo_14174796_box2.jpg - 640/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10248122_photo_14174796_box3.jpg - 641/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 63.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10248122_photo_14174796_box4.jpg - 642/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10248122_photo_14174796_box5.jpg - 643/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102544205_photo_171439940_box1.jpg - 644/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102691689_photo_171703427_box1.jpg - 645/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102691691_photo_171703626_box1.jpg - 646/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102691691_photo_171703626_box2.jpg - 647/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102691691_photo_171703626_box3.jpg - 648/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102691691_photo_171703626_box4.jpg - 649/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102691691_photo_171703626_box5.jpg - 650/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750306_box1.jpg - 651/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750306_box2.jpg - 652/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750306_box3.jpg - 653/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750306_box4.jpg - 654/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750306_box5.jpg - 655/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.95images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750341_box1.jpg - 656/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750341_box2.jpg - 657/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750341_box3.jpg - 658/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750341_box4.jpg - 659/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750341_box5.jpg - 660/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750343_box1.jpg - 661/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750343_box2.jpg - 662/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750343_box3.jpg - 663/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750343_box4.jpg - 664/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750343_box5.jpg - 665/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750344_box1.jpg - 666/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750344_box2.jpg - 667/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750344_box3.jpg - 668/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750344_box4.jpg - 669/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750344_box5.jpg - 670/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750346_box1.jpg - 671/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750346_box2.jpg - 672/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750346_box3.jpg - 673/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750346_box4.jpg - 674/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750346_box5.jpg - 675/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750347_box1.jpg - 676/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750347_box2.jpg - 677/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750347_box3.jpg - 678/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750347_box4.jpg - 679/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750347_box5.jpg - 680/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750348_box1.jpg - 681/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750348_box2.jpg - 682/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750348_box3.jpg - 683/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750348_box4.jpg - 684/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750349_box1.jpg - 685/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750349_box2.jpg - 686/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750349_box3.jpg - 687/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750349_box4.jpg - 688/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.95images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750349_box5.jpg - 689/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750352_box1.jpg - 690/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750352_box2.jpg - 691/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750352_box3.jpg - 692/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750352_box4.jpg - 693/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 49.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750352_box5.jpg - 694/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750353_box1.jpg - 695/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750353_box2.jpg - 696/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750353_box3.jpg - 697/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750353_box4.jpg - 698/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750354_box1.jpg - 699/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750354_box2.jpg - 700/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750354_box3.jpg - 701/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750354_box4.jpg - 702/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102708208_photo_171750354_box5.jpg - 703/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102720406_photo_171771958_box1.jpg - 704/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102720406_photo_171771958_box2.jpg - 705/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102720406_photo_171772415_box1.jpg - 706/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102797000_photo_171915764_box1.jpg - 707/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102797000_photo_171915764_box2.jpg - 708/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102797000_photo_171915764_box3.jpg - 709/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102797000_photo_171915764_box4.jpg - 710/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102797000_photo_171915764_box5.jpg - 711/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102797000_photo_171916896_box1.jpg - 712/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102797000_photo_171916896_box2.jpg - 713/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102797000_photo_171916896_box3.jpg - 714/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102797000_photo_171916896_box4.jpg - 715/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102797000_photo_171916896_box5.jpg - 716/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102836588_photo_171987202_box1.jpg - 717/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102836588_photo_171987202_box2.jpg - 718/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102836588_photo_171987202_box3.jpg - 719/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102836588_photo_171987208_box1.jpg - 720/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102836588_photo_171987208_box2.jpg - 721/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102836588_photo_171987208_box3.jpg - 722/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102907353_photo_172121626_box1.jpg - 723/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 49.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102907353_photo_172121626_box2.jpg - 724/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102907353_photo_172121626_box3.jpg - 725/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 76.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102907353_photo_172121626_box4.jpg - 726/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102907353_photo_172121636_box1.jpg - 727/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 74.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102907353_photo_172121636_box2.jpg - 728/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102907353_photo_172121636_box3.jpg - 729/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102907353_photo_172121647_box1.jpg - 730/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102907353_photo_172121647_box2.jpg - 731/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102907353_photo_172121659_box1.jpg - 732/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102907353_photo_172121659_box2.jpg - 733/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 74.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102907353_photo_172121659_box3.jpg - 734/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102907353_photo_172121659_box4.jpg - 735/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102907398_photo_172121726_box1.jpg - 736/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102907398_photo_172121726_box2.jpg - 737/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102907398_photo_172121741_box1.jpg - 738/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102907398_photo_172121751_box1.jpg - 739/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_102907398_photo_172121763_box1.jpg - 740/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103017971_photo_172325764_box1.jpg - 741/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103017971_photo_172325764_box2.jpg - 742/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103017971_photo_172325764_box3.jpg - 743/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103017971_photo_172325764_box4.jpg - 744/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103017971_photo_172325764_box5.jpg - 745/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103042339_photo_172373105_box1.jpg - 746/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103042339_photo_172373105_box2.jpg - 747/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103042339_photo_172373105_box3.jpg - 748/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103042339_photo_172373105_box4.jpg - 749/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103042339_photo_172373105_box5.jpg - 750/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103042339_photo_172373108_box1.jpg - 751/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103042339_photo_172373108_box2.jpg - 752/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103042339_photo_172373108_box3.jpg - 753/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103042339_photo_172373108_box4.jpg - 754/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103042339_photo_172373108_box5.jpg - 755/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10309167_photo_14282194_box1.jpg - 756/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10309167_photo_14282194_box2.jpg - 757/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10309167_photo_14282205_box1.jpg - 758/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10309167_photo_14282205_box2.jpg - 759/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10309167_photo_14282205_box3.jpg - 760/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10309167_photo_14282205_box4.jpg - 761/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10309167_photo_14282205_box5.jpg - 762/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10309167_photo_14282211_box1.jpg - 763/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10309167_photo_14282211_box2.jpg - 764/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10309167_photo_14282211_box3.jpg - 765/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10309167_photo_14282214_box1.jpg - 766/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103092874_photo_172469527_box1.jpg - 767/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103092874_photo_172469527_box2.jpg - 768/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103092874_photo_172469527_box3.jpg - 769/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103092874_photo_172469527_box4.jpg - 770/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103092874_photo_172469527_box5.jpg - 771/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103092936_photo_172469527_box1.jpg - 772/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103092936_photo_172469527_box2.jpg - 773/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103092936_photo_172469527_box3.jpg - 774/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103092936_photo_172469527_box4.jpg - 775/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103096282_photo_172476046_box1.jpg - 776/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103096282_photo_172476046_box2.jpg - 777/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103096282_photo_172476046_box3.jpg - 778/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103096282_photo_172476046_box4.jpg - 779/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103096282_photo_172476046_box5.jpg - 780/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103096282_photo_172476773_box1.jpg - 781/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103096282_photo_172476773_box2.jpg - 782/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103096282_photo_172476773_box3.jpg - 783/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103096628_photo_172476046_box1.jpg - 784/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103096628_photo_172476046_box2.jpg - 785/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 49.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103096628_photo_172476046_box3.jpg - 786/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103096628_photo_172476046_box4.jpg - 787/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103096628_photo_172476046_box5.jpg - 788/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103137514_photo_172553931_box1.jpg - 789/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031674_photo_12158042_box1.jpg - 790/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031674_photo_12158042_box2.jpg - 791/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031674_photo_12158042_box3.jpg - 792/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031674_photo_1294252_box1.jpg - 793/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031674_photo_1294252_box2.jpg - 794/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031674_photo_1294252_box3.jpg - 795/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031674_photo_1294252_box4.jpg - 796/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031674_photo_1294252_box5.jpg - 797/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031674_photo_1294253_box1.jpg - 798/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031674_photo_1294253_box2.jpg - 799/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031674_photo_1294253_box3.jpg - 800/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031674_photo_1294253_box4.jpg - 801/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031674_photo_1294253_box5.jpg - 802/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031679_photo_1294271_box1.jpg - 803/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031679_photo_1294271_box2.jpg - 804/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031679_photo_1294271_box3.jpg - 805/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.31images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031679_photo_1294271_box4.jpg - 806/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031679_photo_1294271_box5.jpg - 807/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031679_photo_26880735_box1.jpg - 808/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031679_photo_26880735_box2.jpg - 809/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031679_photo_26880735_box3.jpg - 810/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.95images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031679_photo_26880735_box4.jpg - 811/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103168851_photo_172609760_box1.jpg - 812/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103168851_photo_172609771_box1.jpg - 813/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103168851_photo_172609771_box2.jpg - 814/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103168851_photo_172609771_box3.jpg - 815/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103168851_photo_172609771_box4.jpg - 816/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103168851_photo_172609771_box5.jpg - 817/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031728_photo_26928439_box1.jpg - 818/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031728_photo_26928439_box2.jpg - 819/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031728_photo_26928439_box3.jpg - 820/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031728_photo_26928439_box4.jpg - 821/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031728_photo_26928439_box5.jpg - 822/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1031728_photo_447010704_box1.jpg - 823/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10317797_photo_14298032_box1.jpg - 824/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10317797_photo_14298032_box2.jpg - 825/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10317797_photo_14298043_box1.jpg - 826/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10317797_photo_14298043_box2.jpg - 827/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10317797_photo_14298043_box3.jpg - 828/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10317798_photo_14298104_box1.jpg - 829/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10317798_photo_14298135_box1.jpg - 830/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10317798_photo_14298135_box2.jpg - 831/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.41images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103189582_photo_172649459_box1.jpg - 832/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103218458_photo_172701297_box1.jpg - 833/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103218458_photo_172701297_box2.jpg - 834/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103218458_photo_172701315_box1.jpg - 835/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103218458_photo_172701315_box2.jpg - 836/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103218458_photo_172701340_box1.jpg - 837/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103218458_photo_172701340_box2.jpg - 838/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103218458_photo_172701357_box1.jpg - 839/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103218458_photo_172701357_box2.jpg - 840/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103218458_photo_172701391_box1.jpg - 841/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103218458_photo_172701401_box1.jpg - 842/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103218458_photo_172701401_box2.jpg - 843/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103218458_photo_172701401_box3.jpg - 844/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103218458_photo_172701409_box1.jpg - 845/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103245591_photo_172751378_box1.jpg - 846/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103245591_photo_172751402_box1.jpg - 847/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103245591_photo_172751404_box1.jpg - 848/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 49.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103245591_photo_172751406_box1.jpg - 849/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103245591_photo_172751408_box1.jpg - 850/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 74.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103245591_photo_172751408_box2.jpg - 851/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103281799_photo_172817043_box1.jpg - 852/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103333626_photo_172917322_box1.jpg - 853/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103333626_photo_172917322_box2.jpg - 854/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103333626_photo_172917322_box3.jpg - 855/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103333743_photo_172917639_box1.jpg - 856/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103333835_photo_172917677_box1.jpg - 857/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103333835_photo_172917677_box2.jpg - 858/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103342389_photo_172933933_box1.jpg - 859/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103342389_photo_172933933_box2.jpg - 860/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103342389_photo_172933933_box3.jpg - 861/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103342389_photo_172933934_box1.jpg - 862/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103342389_photo_172933934_box2.jpg - 863/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103342389_photo_172933938_box1.jpg - 864/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103342389_photo_172933938_box2.jpg - 865/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103342389_photo_172933943_box1.jpg - 866/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103342389_photo_172933943_box2.jpg - 867/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103370496_photo_172986688_box1.jpg - 868/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103370496_photo_172986688_box2.jpg - 869/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103370496_photo_172986700_box1.jpg - 870/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103370496_photo_172986700_box2.jpg - 871/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103370497_photo_172986684_box1.jpg - 872/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103370497_photo_172986684_box2.jpg - 873/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103370497_photo_172986694_box1.jpg - 874/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103370497_photo_172986698_box1.jpg - 875/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103370497_photo_172986698_box2.jpg - 876/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103395903_photo_173030410_box1.jpg - 877/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103395903_photo_173030410_box2.jpg - 878/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103395903_photo_173030410_box3.jpg - 879/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103395903_photo_173030410_box4.jpg - 880/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103395903_photo_173030422_box1.jpg - 881/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103395903_photo_173030422_box2.jpg - 882/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103395903_photo_173030422_box3.jpg - 883/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103395903_photo_173030425_box1.jpg - 884/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103395903_photo_173030434_box1.jpg - 885/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103395903_photo_173030434_box2.jpg - 886/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103395903_photo_173030434_box3.jpg - 887/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103395903_photo_173030434_box4.jpg - 888/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103395903_photo_173030439_box1.jpg - 889/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103395903_photo_173030439_box2.jpg - 890/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103395903_photo_173030439_box3.jpg - 891/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103395903_photo_173030439_box4.jpg - 892/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103403764_photo_173052489_box1.jpg - 893/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103403764_photo_173052489_box2.jpg - 894/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103403764_photo_173052511_box1.jpg - 895/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103403764_photo_173052511_box2.jpg - 896/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103403764_photo_173052511_box3.jpg - 897/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103403764_photo_173052511_box4.jpg - 898/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103403764_photo_173052511_box5.jpg - 899/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103418665_photo_173076439_box1.jpg - 900/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103418665_photo_173076439_box2.jpg - 901/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103418665_photo_173076439_box3.jpg - 902/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103418665_photo_173076439_box4.jpg - 903/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103418665_photo_173076439_box5.jpg - 904/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103418665_photo_173076452_box1.jpg - 905/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103418665_photo_173076452_box2.jpg - 906/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103418665_photo_173076452_box3.jpg - 907/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103418665_photo_173076452_box4.jpg - 908/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103418665_photo_173076452_box5.jpg - 909/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103443657_photo_173128724_box1.jpg - 910/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103443657_photo_173128724_box2.jpg - 911/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103443657_photo_173128742_box1.jpg - 912/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103443657_photo_173128742_box2.jpg - 913/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103443657_photo_173128760_box1.jpg - 914/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103443657_photo_173128760_box2.jpg - 915/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103443657_photo_173128760_box3.jpg - 916/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173272813_box1.jpg - 917/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173272882_box1.jpg - 918/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173272882_box2.jpg - 919/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173272882_box3.jpg - 920/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173272882_box4.jpg - 921/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173272886_box1.jpg - 922/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173272886_box2.jpg - 923/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173272886_box3.jpg - 924/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173272928_box1.jpg - 925/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173272928_box2.jpg - 926/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173272928_box3.jpg - 927/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173273020_box1.jpg - 928/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173273020_box2.jpg - 929/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173273020_box3.jpg - 930/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173273066_box1.jpg - 931/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173273066_box2.jpg - 932/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173273089_box1.jpg - 933/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173273089_box2.jpg - 934/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173273089_box3.jpg - 935/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173273089_box4.jpg - 936/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173273095_box1.jpg - 937/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173273095_box2.jpg - 938/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173273095_box3.jpg - 939/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173273159_box1.jpg - 940/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173273159_box2.jpg - 941/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173273212_box1.jpg - 942/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173273239_box1.jpg - 943/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173273306_box1.jpg - 944/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173273306_box2.jpg - 945/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173273306_box3.jpg - 946/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173273306_box4.jpg - 947/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103519418_photo_173273337_box1.jpg - 948/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103528868_photo_173293748_box1.jpg - 949/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103528868_photo_173293748_box2.jpg - 950/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103528868_photo_173293748_box3.jpg - 951/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103528868_photo_173293748_box4.jpg - 952/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103528868_photo_173293748_box5.jpg - 953/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103528899_photo_173293859_box1.jpg - 954/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103528899_photo_173293859_box2.jpg - 955/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103528899_photo_173293859_box3.jpg - 956/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103528899_photo_173293859_box4.jpg - 957/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103528899_photo_173293859_box5.jpg - 958/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103555046_photo_173343242_box1.jpg - 959/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103555046_photo_173343242_box2.jpg - 960/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103598981_photo_173428489_box1.jpg - 961/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103598981_photo_173428489_box2.jpg - 962/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103598981_photo_173428489_box3.jpg - 963/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103598981_photo_173428489_box4.jpg - 964/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103598981_photo_173428489_box5.jpg - 965/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103608326_photo_173446116_box1.jpg - 966/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103608326_photo_173446116_box2.jpg - 967/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103608326_photo_173446125_box1.jpg - 968/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103608326_photo_173446125_box2.jpg - 969/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103608326_photo_173446125_box3.jpg - 970/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103608326_photo_173446125_box4.jpg - 971/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103608326_photo_173446125_box5.jpg - 972/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103608326_photo_173446129_box1.jpg - 973/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103608326_photo_173446129_box2.jpg - 974/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103608326_photo_173446129_box3.jpg - 975/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103608326_photo_173446129_box4.jpg - 976/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.31images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103608326_photo_173446129_box5.jpg - 977/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103625069_photo_173479244_box1.jpg - 978/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.31images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103625069_photo_173479244_box2.jpg - 979/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103625069_photo_173479244_box3.jpg - 980/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103662869_photo_173549658_box1.jpg - 981/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103662869_photo_173549658_box2.jpg - 982/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103662869_photo_173549658_box3.jpg - 983/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103662869_photo_173549680_box1.jpg - 984/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103662869_photo_173549680_box2.jpg - 985/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103662869_photo_173549680_box3.jpg - 986/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103662871_photo_173549873_box1.jpg - 987/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103662871_photo_173549873_box2.jpg - 988/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103662871_photo_173549873_box3.jpg - 989/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103662871_photo_173549873_box4.jpg - 990/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 46.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103662871_photo_173549895_box1.jpg - 991/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103662871_photo_173549895_box2.jpg - 992/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103662871_photo_173549895_box3.jpg - 993/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688007_photo_173585104_box1.jpg - 994/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688007_photo_173585104_box2.jpg - 995/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688007_photo_173585104_box3.jpg - 996/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688007_photo_173585104_box4.jpg - 997/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688007_photo_173585104_box5.jpg - 998/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688007_photo_173585138_box1.jpg - 999/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688007_photo_173585138_box2.jpg - 1000/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688007_photo_173585138_box3.jpg - 1001/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688007_photo_173585138_box4.jpg - 1002/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688007_photo_173585157_box1.jpg - 1003/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688007_photo_173585157_box2.jpg - 1004/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688007_photo_173585162_box1.jpg - 1005/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688007_photo_173585162_box2.jpg - 1006/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688007_photo_173585162_box3.jpg - 1007/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688007_photo_173585162_box4.jpg - 1008/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688007_photo_173585165_box1.jpg - 1009/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688007_photo_173585165_box2.jpg - 1010/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688007_photo_173585165_box3.jpg - 1011/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688007_photo_173585165_box4.jpg - 1012/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688007_photo_173585184_box1.jpg - 1013/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688007_photo_173585184_box2.jpg - 1014/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688007_photo_173585184_box3.jpg - 1015/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.41images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688007_photo_173585188_box1.jpg - 1016/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 46.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688007_photo_173585188_box2.jpg - 1017/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688009_photo_173585086_box1.jpg - 1018/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688009_photo_173585086_box2.jpg - 1019/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.95images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688009_photo_173585095_box1.jpg - 1020/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688009_photo_173585109_box1.jpg - 1021/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688009_photo_173585109_box2.jpg - 1022/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688009_photo_173585142_box1.jpg - 1023/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688009_photo_173585142_box2.jpg - 1024/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688052_photo_173587217_box1.jpg - 1025/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688052_photo_173587217_box2.jpg - 1026/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688052_photo_173587217_box3.jpg - 1027/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688052_photo_173587217_box4.jpg - 1028/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688052_photo_173587217_box5.jpg - 1029/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688052_photo_173587240_box1.jpg - 1030/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688052_photo_173587240_box2.jpg - 1031/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688052_photo_173587262_box1.jpg - 1032/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688052_photo_173587262_box2.jpg - 1033/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688066_photo_173587501_box1.jpg - 1034/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688066_photo_173587501_box2.jpg - 1035/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688066_photo_173587527_box1.jpg - 1036/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688066_photo_173587534_box1.jpg - 1037/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688066_photo_173587552_box1.jpg - 1038/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688066_photo_173587553_box1.jpg - 1039/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688066_photo_173587553_box2.jpg - 1040/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688066_photo_173587557_box1.jpg - 1041/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688066_photo_173587566_box1.jpg - 1042/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688066_photo_173587566_box2.jpg - 1043/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688066_photo_173587568_box1.jpg - 1044/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688066_photo_173587573_box1.jpg - 1045/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688066_photo_173587582_box1.jpg - 1046/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688066_photo_173587582_box2.jpg - 1047/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688066_photo_173587587_box1.jpg - 1048/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688066_photo_173587587_box2.jpg - 1049/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688066_photo_173587589_box1.jpg - 1050/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688115_photo_173589492_box1.jpg - 1051/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688115_photo_173589492_box2.jpg - 1052/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688115_photo_173589492_box3.jpg - 1053/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688115_photo_173589492_box4.jpg - 1054/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688115_photo_173589513_box1.jpg - 1055/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688115_photo_173589513_box2.jpg - 1056/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688115_photo_173589531_box1.jpg - 1057/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688115_photo_173589531_box2.jpg - 1058/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688115_photo_173589531_box3.jpg - 1059/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688115_photo_173589610_box1.jpg - 1060/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688115_photo_173589612_box1.jpg - 1061/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688115_photo_173589612_box2.jpg - 1062/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688115_photo_173589612_box3.jpg - 1063/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688115_photo_173589612_box4.jpg - 1064/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688115_photo_173589612_box5.jpg - 1065/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688115_photo_173589629_box1.jpg - 1066/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688115_photo_173589629_box2.jpg - 1067/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688115_photo_173589629_box3.jpg - 1068/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688115_photo_173589638_box1.jpg - 1069/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688120_photo_173589744_box1.jpg - 1070/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688120_photo_173589774_box1.jpg - 1071/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688120_photo_173589774_box2.jpg - 1072/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688120_photo_173589775_box1.jpg - 1073/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688120_photo_173589807_box1.jpg - 1074/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688120_photo_173589817_box1.jpg - 1075/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688120_photo_173589817_box2.jpg - 1076/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688120_photo_173589848_box1.jpg - 1077/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688129_photo_173590063_box1.jpg - 1078/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688129_photo_173590063_box2.jpg - 1079/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688129_photo_173590087_box1.jpg - 1080/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103688129_photo_173590087_box2.jpg - 1081/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103691933_photo_173604663_box1.jpg - 1082/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103691933_photo_173604663_box2.jpg - 1083/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103691933_photo_173604663_box3.jpg - 1084/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103752625_photo_173723223_box1.jpg - 1085/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103752625_photo_173723223_box2.jpg - 1086/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103752625_photo_173723226_box1.jpg - 1087/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103752625_photo_173723226_box2.jpg - 1088/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103752625_photo_173723231_box1.jpg - 1089/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103752625_photo_173723231_box2.jpg - 1090/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103821408_photo_173858002_box1.jpg - 1091/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103821408_photo_173858002_box2.jpg - 1092/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103821408_photo_173858002_box3.jpg - 1093/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103821408_photo_173858002_box4.jpg - 1094/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103821408_photo_173858002_box5.jpg - 1095/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103821408_photo_173858006_box1.jpg - 1096/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103821408_photo_173858006_box2.jpg - 1097/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103821408_photo_173858006_box3.jpg - 1098/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103821408_photo_173858006_box4.jpg - 1099/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103821408_photo_173858006_box5.jpg - 1100/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103821408_photo_173858017_box1.jpg - 1101/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103821408_photo_173858017_box2.jpg - 1102/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103821408_photo_173858017_box3.jpg - 1103/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103821408_photo_173858017_box4.jpg - 1104/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103821408_photo_173858017_box5.jpg - 1105/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103821408_photo_173858035_box1.jpg - 1106/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 46.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103821408_photo_173858035_box2.jpg - 1107/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103821408_photo_173858035_box3.jpg - 1108/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103821408_photo_173858035_box4.jpg - 1109/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103821408_photo_173858035_box5.jpg - 1110/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103838721_photo_173882299_box1.jpg - 1111/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103838721_photo_173882312_box1.jpg - 1112/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103838721_photo_173882319_box1.jpg - 1113/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103838721_photo_173882321_box1.jpg - 1114/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103838721_photo_173882341_box1.jpg - 1115/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103838721_photo_173882341_box2.jpg - 1116/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103838738_photo_173882866_box1.jpg - 1117/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103838738_photo_173882866_box2.jpg - 1118/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103838738_photo_173882866_box3.jpg - 1119/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103838738_photo_173882866_box4.jpg - 1120/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 49.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103838738_photo_173882866_box5.jpg - 1121/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103838738_photo_173882894_box1.jpg - 1122/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103838738_photo_173882894_box2.jpg - 1123/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103838738_photo_173882894_box3.jpg - 1124/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103838738_photo_173882901_box1.jpg - 1125/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103838738_photo_173882901_box2.jpg - 1126/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103838738_photo_173882901_box3.jpg - 1127/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103838738_photo_173882901_box4.jpg - 1128/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103838738_photo_173882901_box5.jpg - 1129/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103838738_photo_173882926_box1.jpg - 1130/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103838738_photo_173882926_box2.jpg - 1131/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103838738_photo_173882926_box3.jpg - 1132/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103838738_photo_173882926_box4.jpg - 1133/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103838738_photo_173882926_box5.jpg - 1134/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103887856_photo_173988396_box1.jpg - 1135/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103889648_photo_173991361_box1.jpg - 1136/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103889648_photo_173991361_box2.jpg - 1137/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103889648_photo_173991361_box3.jpg - 1138/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103889649_photo_173991397_box1.jpg - 1139/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103889649_photo_173991397_box2.jpg - 1140/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_103889649_photo_173991397_box3.jpg - 1141/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104002079_photo_174200400_box1.jpg - 1142/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104002079_photo_174200409_box1.jpg - 1143/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104002079_photo_174200409_box2.jpg - 1144/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104002079_photo_174200416_box1.jpg - 1145/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104002079_photo_174200416_box2.jpg - 1146/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104002079_photo_174200416_box3.jpg - 1147/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 63.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104002079_photo_174200426_box1.jpg - 1148/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104002079_photo_174200426_box2.jpg - 1149/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104002079_photo_174200426_box3.jpg - 1150/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 63.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104002079_photo_174200434_box1.jpg - 1151/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104002079_photo_174200434_box2.jpg - 1152/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057955_photo_174295678_box1.jpg - 1153/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057955_photo_174295678_box2.jpg - 1154/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057955_photo_174295678_box3.jpg - 1155/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057958_photo_174295774_box1.jpg - 1156/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057958_photo_174295774_box2.jpg - 1157/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057958_photo_174295774_box3.jpg - 1158/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057958_photo_174295774_box4.jpg - 1159/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057958_photo_174295774_box5.jpg - 1160/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057958_photo_174295811_box1.jpg - 1161/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057958_photo_174295811_box2.jpg - 1162/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057958_photo_174295811_box3.jpg - 1163/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057958_photo_174295811_box4.jpg - 1164/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057958_photo_174295828_box1.jpg - 1165/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057958_photo_174295828_box2.jpg - 1166/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057958_photo_174295828_box3.jpg - 1167/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057958_photo_174295828_box4.jpg - 1168/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057958_photo_174295828_box5.jpg - 1169/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057958_photo_174295858_box1.jpg - 1170/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057958_photo_174295858_box2.jpg - 1171/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057961_photo_174296448_box1.jpg - 1172/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057961_photo_174296448_box2.jpg - 1173/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057961_photo_174296474_box1.jpg - 1174/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296717_box1.jpg - 1175/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296717_box2.jpg - 1176/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296731_box1.jpg - 1177/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296731_box2.jpg - 1178/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296731_box3.jpg - 1179/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296731_box4.jpg - 1180/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296756_box1.jpg - 1181/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296756_box2.jpg - 1182/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296756_box3.jpg - 1183/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296798_box1.jpg - 1184/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296798_box2.jpg - 1185/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296798_box3.jpg - 1186/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296798_box4.jpg - 1187/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296800_box1.jpg - 1188/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296800_box2.jpg - 1189/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296800_box3.jpg - 1190/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296837_box1.jpg - 1191/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296857_box1.jpg - 1192/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296857_box2.jpg - 1193/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296857_box3.jpg - 1194/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296857_box4.jpg - 1195/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296857_box5.jpg - 1196/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296863_box1.jpg - 1197/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296863_box2.jpg - 1198/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296863_box3.jpg - 1199/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296863_box4.jpg - 1200/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296863_box5.jpg - 1201/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296911_box1.jpg - 1202/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296911_box2.jpg - 1203/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104057971_photo_174296911_box3.jpg - 1204/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104115722_photo_174417609_box1.jpg - 1205/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104115722_photo_174417609_box2.jpg - 1206/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104115722_photo_174417609_box3.jpg - 1207/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104115722_photo_174417609_box4.jpg - 1208/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104115722_photo_174417609_box5.jpg - 1209/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104115722_photo_174417618_box1.jpg - 1210/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104115722_photo_174417618_box2.jpg - 1211/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104115722_photo_174417618_box3.jpg - 1212/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104115722_photo_174417618_box4.jpg - 1213/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104115722_photo_174417618_box5.jpg - 1214/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104115722_photo_174417630_box1.jpg - 1215/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104115722_photo_174417630_box2.jpg - 1216/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104115722_photo_174417630_box3.jpg - 1217/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104115722_photo_174417630_box4.jpg - 1218/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104115722_photo_174417630_box5.jpg - 1219/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104187098_photo_174555651_box1.jpg - 1220/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104187098_photo_174555651_box2.jpg - 1221/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104205671_photo_174590599_box1.jpg - 1222/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104205671_photo_174590599_box2.jpg - 1223/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104205671_photo_174590653_box1.jpg - 1224/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104205671_photo_174590653_box2.jpg - 1225/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104205671_photo_174590653_box3.jpg - 1226/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104205671_photo_174590653_box4.jpg - 1227/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104205671_photo_174590653_box5.jpg - 1228/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104205671_photo_174590655_box1.jpg - 1229/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 75.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104205671_photo_174590655_box2.jpg - 1230/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 74.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104205671_photo_174590655_box3.jpg - 1231/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104205671_photo_174590655_box4.jpg - 1232/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104205671_photo_174590655_box5.jpg - 1233/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104383277_photo_174890903_box1.jpg - 1234/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104383277_photo_174890903_box2.jpg - 1235/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104383277_photo_174890903_box3.jpg - 1236/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416194_photo_174952134_box1.jpg - 1237/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416194_photo_174952134_box2.jpg - 1238/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416194_photo_174952134_box3.jpg - 1239/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416194_photo_174952134_box4.jpg - 1240/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416194_photo_174952134_box5.jpg - 1241/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416194_photo_174952174_box1.jpg - 1242/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416194_photo_174952174_box2.jpg - 1243/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416194_photo_174952174_box3.jpg - 1244/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416194_photo_174952174_box4.jpg - 1245/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416194_photo_174952174_box5.jpg - 1246/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416194_photo_174952199_box1.jpg - 1247/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416194_photo_174952199_box2.jpg - 1248/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.95images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416194_photo_174952199_box3.jpg - 1249/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416194_photo_174952199_box4.jpg - 1250/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416194_photo_174952199_box5.jpg - 1251/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416194_photo_174952241_box1.jpg - 1252/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416194_photo_174952241_box2.jpg - 1253/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416194_photo_174952241_box3.jpg - 1254/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416194_photo_174952241_box4.jpg - 1255/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416196_photo_174952303_box1.jpg - 1256/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416196_photo_174952303_box2.jpg - 1257/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416196_photo_174952303_box3.jpg - 1258/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416196_photo_174952303_box4.jpg - 1259/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416196_photo_174952303_box5.jpg - 1260/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416196_photo_174952329_box1.jpg - 1261/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416196_photo_174952329_box2.jpg - 1262/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416196_photo_174952329_box3.jpg - 1263/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416196_photo_174952329_box4.jpg - 1264/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416196_photo_174952329_box5.jpg - 1265/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416196_photo_174952355_box1.jpg - 1266/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416196_photo_174952355_box2.jpg - 1267/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416196_photo_174952355_box3.jpg - 1268/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416196_photo_174952355_box4.jpg - 1269/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416196_photo_174952442_box1.jpg - 1270/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416196_photo_174952442_box2.jpg - 1271/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416196_photo_174952442_box3.jpg - 1272/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104416196_photo_174952442_box4.jpg - 1273/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10443482_photo_14514903_box1.jpg - 1274/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10443482_photo_14514903_box2.jpg - 1275/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011125_box1.jpg - 1276/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011125_box2.jpg - 1277/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011125_box3.jpg - 1278/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011125_box4.jpg - 1279/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011125_box5.jpg - 1280/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011130_box1.jpg - 1281/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011130_box2.jpg - 1282/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011130_box3.jpg - 1283/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011130_box4.jpg - 1284/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011130_box5.jpg - 1285/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011142_box1.jpg - 1286/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011142_box2.jpg - 1287/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011142_box3.jpg - 1288/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011142_box4.jpg - 1289/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011142_box5.jpg - 1290/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011150_box1.jpg - 1291/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011150_box2.jpg - 1292/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011150_box3.jpg - 1293/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011150_box4.jpg - 1294/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.41images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011150_box5.jpg - 1295/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011156_box1.jpg - 1296/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011156_box2.jpg - 1297/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011156_box3.jpg - 1298/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011156_box4.jpg - 1299/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104446825_photo_175011156_box5.jpg - 1300/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470091_photo_175051479_box1.jpg - 1301/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470091_photo_175051481_box1.jpg - 1302/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470091_photo_175051481_box2.jpg - 1303/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470091_photo_175051519_box1.jpg - 1304/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470091_photo_175051531_box1.jpg - 1305/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470091_photo_175051531_box2.jpg - 1306/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470091_photo_175051546_box1.jpg - 1307/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470091_photo_175051546_box2.jpg - 1308/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470091_photo_175051575_box1.jpg - 1309/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.31images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470091_photo_175051575_box2.jpg - 1310/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470095_photo_175051484_box1.jpg - 1311/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470095_photo_175051484_box2.jpg - 1312/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470095_photo_175051484_box3.jpg - 1313/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.31images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470095_photo_175051484_box4.jpg - 1314/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470095_photo_175051484_box5.jpg - 1315/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470095_photo_175051505_box1.jpg - 1316/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470095_photo_175051505_box2.jpg - 1317/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470095_photo_175051544_box1.jpg - 1318/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470095_photo_175051544_box2.jpg - 1319/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470095_photo_175051559_box1.jpg - 1320/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470095_photo_175051559_box2.jpg - 1321/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470095_photo_175051572_box1.jpg - 1322/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470095_photo_175051572_box2.jpg - 1323/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470095_photo_175051592_box1.jpg - 1324/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470095_photo_175051609_box1.jpg - 1325/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470095_photo_175051609_box2.jpg - 1326/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470095_photo_175051609_box3.jpg - 1327/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.31images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470095_photo_175051609_box4.jpg - 1328/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470095_photo_175051622_box1.jpg - 1329/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470095_photo_175051639_box1.jpg - 1330/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104470095_photo_175051639_box2.jpg - 1331/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101858_box1.jpg - 1332/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101871_box1.jpg - 1333/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101871_box2.jpg - 1334/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101878_box1.jpg - 1335/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101892_box1.jpg - 1336/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101892_box2.jpg - 1337/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101892_box3.jpg - 1338/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101892_box4.jpg - 1339/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.41images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101898_box1.jpg - 1340/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 63.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101898_box2.jpg - 1341/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101898_box3.jpg - 1342/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101905_box1.jpg - 1343/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101905_box2.jpg - 1344/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101905_box3.jpg - 1345/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.41images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101910_box1.jpg - 1346/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101910_box2.jpg - 1347/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101920_box1.jpg - 1348/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101920_box2.jpg - 1349/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101920_box3.jpg - 1350/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101924_box1.jpg - 1351/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101924_box2.jpg - 1352/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101932_box1.jpg - 1353/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101932_box2.jpg - 1354/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101932_box3.jpg - 1355/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101939_box1.jpg - 1356/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101942_box1.jpg - 1357/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101951_box1.jpg - 1358/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101959_box1.jpg - 1359/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496022_photo_175101964_box1.jpg - 1360/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496023_photo_175102959_box1.jpg - 1361/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496023_photo_175102963_box1.jpg - 1362/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496023_photo_175102971_box1.jpg - 1363/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496023_photo_175102971_box2.jpg - 1364/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496023_photo_175102978_box1.jpg - 1365/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496023_photo_175102978_box2.jpg - 1366/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104496023_photo_175102987_box1.jpg - 1367/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155371_box1.jpg - 1368/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155371_box2.jpg - 1369/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155371_box3.jpg - 1370/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155371_box4.jpg - 1371/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155386_box1.jpg - 1372/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155386_box2.jpg - 1373/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 63.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155386_box3.jpg - 1374/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155386_box4.jpg - 1375/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155386_box5.jpg - 1376/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155392_box1.jpg - 1377/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155392_box2.jpg - 1378/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155442_box1.jpg - 1379/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155442_box2.jpg - 1380/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155442_box3.jpg - 1381/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155442_box4.jpg - 1382/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155442_box5.jpg - 1383/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155476_box1.jpg - 1384/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155476_box2.jpg - 1385/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155476_box3.jpg - 1386/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155476_box4.jpg - 1387/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155500_box1.jpg - 1388/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155500_box2.jpg - 1389/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155500_box3.jpg - 1390/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155500_box4.jpg - 1391/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524357_photo_175155500_box5.jpg - 1392/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524367_photo_175155600_box1.jpg - 1393/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524367_photo_175155606_box1.jpg - 1394/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524367_photo_175155632_box1.jpg - 1395/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524367_photo_175155635_box1.jpg - 1396/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524367_photo_175155635_box2.jpg - 1397/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524367_photo_175155635_box3.jpg - 1398/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524367_photo_175155638_box1.jpg - 1399/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524367_photo_175155670_box1.jpg - 1400/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524367_photo_175155675_box1.jpg - 1401/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524367_photo_175155675_box2.jpg - 1402/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524371_photo_175155933_box1.jpg - 1403/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524371_photo_175155938_box1.jpg - 1404/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524371_photo_175155959_box1.jpg - 1405/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524371_photo_175155972_box1.jpg - 1406/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524371_photo_175155973_box1.jpg - 1407/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524371_photo_175155976_box1.jpg - 1408/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104524371_photo_175155998_box1.jpg - 1409/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532181_photo_175169961_box1.jpg - 1410/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532181_photo_175169961_box2.jpg - 1411/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532181_photo_175169974_box1.jpg - 1412/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532181_photo_175169974_box2.jpg - 1413/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532181_photo_175169974_box3.jpg - 1414/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532181_photo_175169974_box4.jpg - 1415/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532181_photo_175170029_box1.jpg - 1416/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532181_photo_175170029_box2.jpg - 1417/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532181_photo_175170029_box3.jpg - 1418/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532181_photo_175170096_box1.jpg - 1419/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532181_photo_175170096_box2.jpg - 1420/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.31images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532181_photo_175170096_box3.jpg - 1421/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532181_photo_175170135_box1.jpg - 1422/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532181_photo_175170135_box2.jpg - 1423/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532181_photo_175170135_box3.jpg - 1424/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532181_photo_175170135_box4.jpg - 1425/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532188_photo_175170533_box1.jpg - 1426/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532188_photo_175170551_box1.jpg - 1427/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532188_photo_175170572_box1.jpg - 1428/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532188_photo_175170586_box1.jpg - 1429/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532188_photo_175170586_box2.jpg - 1430/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532188_photo_175170602_box1.jpg - 1431/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532188_photo_175170602_box2.jpg - 1432/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532188_photo_175170602_box3.jpg - 1433/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532188_photo_175170617_box1.jpg - 1434/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532188_photo_175170617_box2.jpg - 1435/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.41images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532188_photo_175170617_box3.jpg - 1436/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532188_photo_175170641_box1.jpg - 1437/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532188_photo_175170650_box1.jpg - 1438/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532188_photo_175170650_box2.jpg - 1439/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532188_photo_175170652_box1.jpg - 1440/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532188_photo_175170652_box2.jpg - 1441/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104532188_photo_175170652_box3.jpg - 1442/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104569394_photo_175246215_box1.jpg - 1443/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104569394_photo_175246215_box2.jpg - 1444/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104569394_photo_175246215_box3.jpg - 1445/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104569394_photo_175246217_box1.jpg - 1446/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.31images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104581250_photo_175354371_box1.jpg - 1447/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104581250_photo_175354371_box2.jpg - 1448/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104581250_photo_175354371_box3.jpg - 1449/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104581250_photo_175354371_box4.jpg - 1450/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104581250_photo_175354371_box5.jpg - 1451/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104581250_photo_175470968_box1.jpg - 1452/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 49.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104581250_photo_175470968_box2.jpg - 1453/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 74.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104581250_photo_175470968_box3.jpg - 1454/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104581250_photo_175633171_box1.jpg - 1455/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104581250_photo_175633171_box2.jpg - 1456/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104581250_photo_175633171_box3.jpg - 1457/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104581250_photo_175633171_box4.jpg - 1458/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104600463_photo_175304254_box1.jpg - 1459/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104600463_photo_175304271_box1.jpg - 1460/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104600463_photo_175304271_box2.jpg - 1461/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104600463_photo_175304285_box1.jpg - 1462/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104600463_photo_175304285_box2.jpg - 1463/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104600463_photo_175304302_box1.jpg - 1464/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104601764_photo_175305483_box1.jpg - 1465/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104601764_photo_175305495_box1.jpg - 1466/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104671399_photo_175437595_box1.jpg - 1467/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104671399_photo_175437607_box1.jpg - 1468/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104671399_photo_175437607_box2.jpg - 1469/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104671399_photo_175437614_box1.jpg - 1470/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104671399_photo_175437629_box1.jpg - 1471/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104671399_photo_175437629_box2.jpg - 1472/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104671399_photo_175437629_box3.jpg - 1473/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104671399_photo_175437634_box1.jpg - 1474/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104671399_photo_175437634_box2.jpg - 1475/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104671399_photo_175437652_box1.jpg - 1476/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104671399_photo_175437657_box1.jpg - 1477/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104671399_photo_175437665_box1.jpg - 1478/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104679526_photo_175453741_box1.jpg - 1479/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104679526_photo_175453741_box2.jpg - 1480/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104679526_photo_175453788_box1.jpg - 1481/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104679526_photo_175453788_box2.jpg - 1482/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104679526_photo_175453788_box3.jpg - 1483/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104679526_photo_175453788_box4.jpg - 1484/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104685233_photo_175465159_box1.jpg - 1485/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104685233_photo_175465159_box2.jpg - 1486/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104698372_photo_175491735_box1.jpg - 1487/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104698372_photo_175491735_box2.jpg - 1488/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104698372_photo_175491735_box3.jpg - 1489/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104698372_photo_175491735_box4.jpg - 1490/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.31images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104698372_photo_175491735_box5.jpg - 1491/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104726684_photo_175544281_box1.jpg - 1492/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104726684_photo_175544281_box2.jpg - 1493/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104736465_photo_175564399_box1.jpg - 1494/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104736465_photo_175564399_box2.jpg - 1495/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104736465_photo_175564399_box3.jpg - 1496/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104736465_photo_175564399_box4.jpg - 1497/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104736465_photo_175564609_box1.jpg - 1498/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104736465_photo_175564609_box2.jpg - 1499/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104736465_photo_175564609_box3.jpg - 1500/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104736465_photo_175564624_box1.jpg - 1501/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104736465_photo_175564624_box2.jpg - 1502/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104736465_photo_175564624_box3.jpg - 1503/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104736465_photo_175564624_box4.jpg - 1504/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104736465_photo_175564654_box1.jpg - 1505/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104736465_photo_175564654_box2.jpg - 1506/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104736465_photo_175564654_box3.jpg - 1507/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104736465_photo_175564654_box4.jpg - 1508/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104736465_photo_175564654_box5.jpg - 1509/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104736465_photo_175564709_box1.jpg - 1510/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104736465_photo_175564709_box2.jpg - 1511/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104736465_photo_175564709_box3.jpg - 1512/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104736465_photo_175564709_box4.jpg - 1513/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650416_box1.jpg - 1514/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650416_box2.jpg - 1515/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650416_box3.jpg - 1516/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650416_box4.jpg - 1517/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650416_box5.jpg - 1518/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650543_box1.jpg - 1519/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650543_box2.jpg - 1520/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650543_box3.jpg - 1521/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650543_box4.jpg - 1522/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650543_box5.jpg - 1523/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650569_box1.jpg - 1524/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650569_box2.jpg - 1525/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650569_box3.jpg - 1526/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650569_box4.jpg - 1527/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650569_box5.jpg - 1528/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650595_box1.jpg - 1529/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650595_box2.jpg - 1530/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650595_box3.jpg - 1531/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650595_box4.jpg - 1532/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650595_box5.jpg - 1533/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650713_box1.jpg - 1534/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650713_box2.jpg - 1535/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650713_box3.jpg - 1536/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650713_box4.jpg - 1537/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104780983_photo_175650713_box5.jpg - 1538/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923206_photo_175918944_box1.jpg - 1539/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923206_photo_175918944_box2.jpg - 1540/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923206_photo_175918944_box3.jpg - 1541/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923206_photo_175918944_box4.jpg - 1542/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923206_photo_175918947_box1.jpg - 1543/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923206_photo_175918947_box2.jpg - 1544/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923206_photo_175918947_box3.jpg - 1545/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923206_photo_175918947_box4.jpg - 1546/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923206_photo_175918947_box5.jpg - 1547/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923206_photo_175918995_box1.jpg - 1548/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923206_photo_175918995_box2.jpg - 1549/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923206_photo_175918995_box3.jpg - 1550/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923206_photo_175918995_box4.jpg - 1551/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923206_photo_175918995_box5.jpg - 1552/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918868_box1.jpg - 1553/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918868_box2.jpg - 1554/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918868_box3.jpg - 1555/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918868_box4.jpg - 1556/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918868_box5.jpg - 1557/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918877_box1.jpg - 1558/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918877_box2.jpg - 1559/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918877_box3.jpg - 1560/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918877_box4.jpg - 1561/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918877_box5.jpg - 1562/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918894_box1.jpg - 1563/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918894_box2.jpg - 1564/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918894_box3.jpg - 1565/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918894_box4.jpg - 1566/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918894_box5.jpg - 1567/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918899_box1.jpg - 1568/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918899_box2.jpg - 1569/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918899_box3.jpg - 1570/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918899_box4.jpg - 1571/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918899_box5.jpg - 1572/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918909_box1.jpg - 1573/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918909_box2.jpg - 1574/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918909_box3.jpg - 1575/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918909_box4.jpg - 1576/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918909_box5.jpg - 1577/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918915_box1.jpg - 1578/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918915_box2.jpg - 1579/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918915_box3.jpg - 1580/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918915_box4.jpg - 1581/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918918_box1.jpg - 1582/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918918_box2.jpg - 1583/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918950_box1.jpg - 1584/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918950_box2.jpg - 1585/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918950_box3.jpg - 1586/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918950_box4.jpg - 1587/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918950_box5.jpg - 1588/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918973_box1.jpg - 1589/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918973_box2.jpg - 1590/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918974_box1.jpg - 1591/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918974_box2.jpg - 1592/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918974_box3.jpg - 1593/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918974_box4.jpg - 1594/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918974_box5.jpg - 1595/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918976_box1.jpg - 1596/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918976_box2.jpg - 1597/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918976_box3.jpg - 1598/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918976_box4.jpg - 1599/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175918976_box5.jpg - 1600/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175919012_box1.jpg - 1601/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175919012_box2.jpg - 1602/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175919012_box3.jpg - 1603/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175919012_box4.jpg - 1604/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923207_photo_175919012_box5.jpg - 1605/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923220_photo_175919413_box1.jpg - 1606/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923220_photo_175919413_box2.jpg - 1607/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923220_photo_175919448_box1.jpg - 1608/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923220_photo_175919456_box1.jpg - 1609/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923221_photo_175919414_box1.jpg - 1610/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923221_photo_175919478_box1.jpg - 1611/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923221_photo_175919492_box1.jpg - 1612/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104923221_photo_175919510_box1.jpg - 1613/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936633_box1.jpg - 1614/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936633_box2.jpg - 1615/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936633_box3.jpg - 1616/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936633_box4.jpg - 1617/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936633_box5.jpg - 1618/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936679_box1.jpg - 1619/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936679_box2.jpg - 1620/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 63.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936679_box3.jpg - 1621/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936679_box4.jpg - 1622/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936679_box5.jpg - 1623/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936713_box1.jpg - 1624/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936746_box1.jpg - 1625/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936746_box2.jpg - 1626/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936771_box1.jpg - 1627/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936771_box2.jpg - 1628/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936771_box3.jpg - 1629/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936771_box4.jpg - 1630/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936771_box5.jpg - 1631/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936797_box1.jpg - 1632/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936797_box2.jpg - 1633/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936829_box1.jpg - 1634/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936829_box2.jpg - 1635/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936844_box1.jpg - 1636/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936844_box2.jpg - 1637/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936844_box3.jpg - 1638/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936844_box4.jpg - 1639/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936870_box1.jpg - 1640/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936870_box2.jpg - 1641/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936870_box3.jpg - 1642/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936870_box4.jpg - 1643/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936870_box5.jpg - 1644/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936895_box1.jpg - 1645/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936895_box2.jpg - 1646/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936895_box3.jpg - 1647/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936895_box4.jpg - 1648/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936928_box1.jpg - 1649/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936928_box2.jpg - 1650/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936928_box3.jpg - 1651/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936928_box4.jpg - 1652/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936950_box1.jpg - 1653/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936950_box2.jpg - 1654/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936950_box3.jpg - 1655/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936986_box1.jpg - 1656/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936986_box2.jpg - 1657/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175936986_box3.jpg - 1658/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175937027_box1.jpg - 1659/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175937027_box2.jpg - 1660/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175937027_box3.jpg - 1661/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175937027_box4.jpg - 1662/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175937027_box5.jpg - 1663/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175937058_box1.jpg - 1664/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175937058_box2.jpg - 1665/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175937087_box1.jpg - 1666/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175937087_box2.jpg - 1667/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175937128_box1.jpg - 1668/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175937148_box1.jpg - 1669/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175937148_box2.jpg - 1670/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175937180_box1.jpg - 1671/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175937180_box2.jpg - 1672/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175937180_box3.jpg - 1673/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175937180_box4.jpg - 1674/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175937180_box5.jpg - 1675/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175937207_box1.jpg - 1676/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104930165_photo_175937207_box2.jpg - 1677/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10494726_photo_14595329_box1.jpg - 1678/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104947968_photo_175971649_box1.jpg - 1679/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104947968_photo_175971649_box2.jpg - 1680/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104947968_photo_175971676_box1.jpg - 1681/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104948524_photo_175971649_box1.jpg - 1682/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104948524_photo_175971649_box2.jpg - 1683/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104948524_photo_175971649_box3.jpg - 1684/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104948524_photo_175971649_box4.jpg - 1685/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104948524_photo_175971748_box1.jpg - 1686/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104948524_photo_175971748_box2.jpg - 1687/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104948524_photo_175971748_box3.jpg - 1688/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104948524_photo_175971748_box4.jpg - 1689/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104948524_photo_175971748_box5.jpg - 1690/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987129_photo_176036512_box1.jpg - 1691/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987129_photo_176036512_box2.jpg - 1692/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987129_photo_176036512_box3.jpg - 1693/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987129_photo_176036512_box4.jpg - 1694/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987129_photo_176036512_box5.jpg - 1695/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987129_photo_176036520_box1.jpg - 1696/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987129_photo_176036520_box2.jpg - 1697/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987129_photo_176036522_box1.jpg - 1698/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987129_photo_176036522_box2.jpg - 1699/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987129_photo_176036522_box3.jpg - 1700/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987129_photo_176036533_box1.jpg - 1701/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987129_photo_176036559_box1.jpg - 1702/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 49.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036529_box1.jpg - 1703/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 46.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036529_box2.jpg - 1704/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036529_box3.jpg - 1705/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036539_box1.jpg - 1706/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036556_box1.jpg - 1707/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036556_box2.jpg - 1708/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.95images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036556_box3.jpg - 1709/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036556_box4.jpg - 1710/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036556_box5.jpg - 1711/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036563_box1.jpg - 1712/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036563_box2.jpg - 1713/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036563_box3.jpg - 1714/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036563_box4.jpg - 1715/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036563_box5.jpg - 1716/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.31images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036583_box1.jpg - 1717/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036583_box2.jpg - 1718/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036583_box3.jpg - 1719/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036583_box4.jpg - 1720/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036583_box5.jpg - 1721/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036590_box1.jpg - 1722/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036590_box2.jpg - 1723/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036590_box3.jpg - 1724/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036594_box1.jpg - 1725/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036608_box1.jpg - 1726/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036608_box2.jpg - 1727/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036608_box3.jpg - 1728/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036608_box4.jpg - 1729/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036608_box5.jpg - 1730/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036615_box1.jpg - 1731/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036615_box2.jpg - 1732/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987130_photo_176036615_box3.jpg - 1733/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987149_photo_176037326_box1.jpg - 1734/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987149_photo_176037326_box2.jpg - 1735/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987149_photo_176037332_box1.jpg - 1736/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987149_photo_176037332_box2.jpg - 1737/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987149_photo_176037340_box1.jpg - 1738/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987149_photo_176037340_box2.jpg - 1739/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987149_photo_176037349_box1.jpg - 1740/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987149_photo_176037349_box2.jpg - 1741/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987157_photo_176037556_box1.jpg - 1742/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987157_photo_176037564_box1.jpg - 1743/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987157_photo_176037564_box2.jpg - 1744/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987157_photo_176037565_box1.jpg - 1745/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987157_photo_176037565_box2.jpg - 1746/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987157_photo_176037574_box1.jpg - 1747/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987157_photo_176037582_box1.jpg - 1748/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_104987157_photo_176037582_box2.jpg - 1749/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105019680_photo_176108882_box1.jpg - 1750/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105019680_photo_176108889_box1.jpg - 1751/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105097060_photo_176257821_box1.jpg - 1752/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105097060_photo_176257821_box2.jpg - 1753/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 75.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105097060_photo_176257821_box3.jpg - 1754/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105097060_photo_176257821_box4.jpg - 1755/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105097060_photo_176257821_box5.jpg - 1756/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105157467_photo_176375218_box1.jpg - 1757/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105157467_photo_176375218_box2.jpg - 1758/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105157467_photo_176375218_box3.jpg - 1759/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105157468_photo_176375221_box1.jpg - 1760/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105157468_photo_176375221_box2.jpg - 1761/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105157468_photo_176375221_box3.jpg - 1762/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105157468_photo_176375221_box4.jpg - 1763/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105157468_photo_176375221_box5.jpg - 1764/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105169294_photo_176397128_box1.jpg - 1765/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105169294_photo_176411789_box1.jpg - 1766/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105251032_photo_176553779_box1.jpg - 1767/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105251032_photo_176554217_box1.jpg - 1768/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 63.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105251040_photo_176554216_box1.jpg - 1769/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105266808_photo_176584517_box1.jpg - 1770/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105266808_photo_176584517_box2.jpg - 1771/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105266808_photo_176584517_box3.jpg - 1772/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105266808_photo_176584517_box4.jpg - 1773/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105266808_photo_176584517_box5.jpg - 1774/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105266808_photo_176584536_box1.jpg - 1775/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105266808_photo_176584536_box2.jpg - 1776/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105329540_photo_176704709_box1.jpg - 1777/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105373534_photo_176787844_box1.jpg - 1778/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105373534_photo_176787844_box2.jpg - 1779/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105384113_photo_176788527_box1.jpg - 1780/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105384113_photo_176788527_box2.jpg - 1781/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105384113_photo_176788581_box1.jpg - 1782/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105384113_photo_176788581_box2.jpg - 1783/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105384126_photo_176788794_box1.jpg - 1784/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105384126_photo_176788794_box2.jpg - 1785/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105384126_photo_176788818_box1.jpg - 1786/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105384126_photo_176788818_box2.jpg - 1787/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105384126_photo_176788838_box1.jpg - 1788/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105384126_photo_176788838_box2.jpg - 1789/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105384126_photo_176788892_box1.jpg - 1790/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105384126_photo_176788892_box2.jpg - 1791/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105384126_photo_176788924_box1.jpg - 1792/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105384126_photo_176788938_box1.jpg - 1793/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105384126_photo_176788980_box1.jpg - 1794/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105417298_photo_176870837_box1.jpg - 1795/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105417298_photo_176870837_box2.jpg - 1796/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105417298_photo_176870837_box3.jpg - 1797/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105417298_photo_176870837_box4.jpg - 1798/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105417298_photo_176870837_box5.jpg - 1799/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105417298_photo_176870841_box1.jpg - 1800/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105417298_photo_176870841_box2.jpg - 1801/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 49.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105417298_photo_176870841_box3.jpg - 1802/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105417298_photo_176870841_box4.jpg - 1803/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105417298_photo_176870841_box5.jpg - 1804/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105486552_photo_177001423_box1.jpg - 1805/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105486552_photo_177001423_box2.jpg - 1806/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105486552_photo_177001423_box3.jpg - 1807/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105486552_photo_177001423_box4.jpg - 1808/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105486552_photo_177001423_box5.jpg - 1809/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105486552_photo_177001437_box1.jpg - 1810/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105486552_photo_177001437_box2.jpg - 1811/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105486552_photo_177001437_box3.jpg - 1812/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105486552_photo_177001437_box4.jpg - 1813/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105486552_photo_177001437_box5.jpg - 1814/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105492260_photo_177013014_box1.jpg - 1815/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 63.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105492260_photo_177013014_box2.jpg - 1816/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105492260_photo_177013014_box3.jpg - 1817/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105492260_photo_177013014_box4.jpg - 1818/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 75.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105492260_photo_177013014_box5.jpg - 1819/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105492260_photo_177013051_box1.jpg - 1820/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105492260_photo_177013051_box2.jpg - 1821/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105492260_photo_177013052_box1.jpg - 1822/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105492260_photo_177013052_box2.jpg - 1823/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105504379_photo_177035221_box1.jpg - 1824/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105515506_photo_177057669_box1.jpg - 1825/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105515506_photo_177057669_box2.jpg - 1826/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105515506_photo_177057669_box3.jpg - 1827/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105534578_photo_177094191_box1.jpg - 1828/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105534578_photo_177094191_box2.jpg - 1829/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105534578_photo_177094191_box3.jpg - 1830/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105534578_photo_177094191_box4.jpg - 1831/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105534578_photo_177094208_box1.jpg - 1832/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105534578_photo_177094208_box2.jpg - 1833/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568331_photo_177151186_box1.jpg - 1834/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568331_photo_177151186_box2.jpg - 1835/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568331_photo_177151186_box3.jpg - 1836/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568331_photo_177151186_box4.jpg - 1837/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568331_photo_177151212_box1.jpg - 1838/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.95images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568331_photo_177151212_box2.jpg - 1839/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568331_photo_177151212_box3.jpg - 1840/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568331_photo_177151282_box1.jpg - 1841/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568331_photo_177151282_box2.jpg - 1842/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568331_photo_177151333_box1.jpg - 1843/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568331_photo_177151333_box2.jpg - 1844/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568331_photo_177151333_box3.jpg - 1845/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568331_photo_177151333_box4.jpg - 1846/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568331_photo_177151333_box5.jpg - 1847/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568332_photo_177151242_box1.jpg - 1848/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568332_photo_177151242_box2.jpg - 1849/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568332_photo_177151242_box3.jpg - 1850/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568332_photo_177151242_box4.jpg - 1851/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568332_photo_177151242_box5.jpg - 1852/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568332_photo_177151254_box1.jpg - 1853/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568332_photo_177151254_box2.jpg - 1854/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568332_photo_177151272_box1.jpg - 1855/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568332_photo_177151272_box2.jpg - 1856/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568332_photo_177151272_box3.jpg - 1857/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568332_photo_177151272_box4.jpg - 1858/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568332_photo_177151272_box5.jpg - 1859/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568332_photo_177151304_box1.jpg - 1860/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568332_photo_177151304_box2.jpg - 1861/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568332_photo_177151304_box3.jpg - 1862/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568332_photo_177151304_box4.jpg - 1863/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568332_photo_177151304_box5.jpg - 1864/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568332_photo_177151328_box1.jpg - 1865/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568332_photo_177151328_box2.jpg - 1866/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568332_photo_177151328_box3.jpg - 1867/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568332_photo_177151328_box4.jpg - 1868/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568332_photo_177151328_box5.jpg - 1869/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568332_photo_177151356_box1.jpg - 1870/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105568332_photo_177151356_box2.jpg - 1871/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599462_photo_177215921_box1.jpg - 1872/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599462_photo_177215947_box1.jpg - 1873/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599462_photo_177215947_box2.jpg - 1874/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599462_photo_177215968_box1.jpg - 1875/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.95images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599462_photo_177215968_box2.jpg - 1876/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599462_photo_177215968_box3.jpg - 1877/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599462_photo_177220060_box1.jpg - 1878/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599462_photo_177220060_box2.jpg - 1879/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215839_box1.jpg - 1880/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 46.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215839_box2.jpg - 1881/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215839_box3.jpg - 1882/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215851_box1.jpg - 1883/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215851_box2.jpg - 1884/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215851_box3.jpg - 1885/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215857_box1.jpg - 1886/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.95images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215857_box2.jpg - 1887/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215857_box3.jpg - 1888/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215857_box4.jpg - 1889/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215857_box5.jpg - 1890/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215866_box1.jpg - 1891/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215866_box2.jpg - 1892/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215869_box1.jpg - 1893/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215869_box2.jpg - 1894/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215869_box3.jpg - 1895/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215869_box4.jpg - 1896/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215869_box5.jpg - 1897/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215873_box1.jpg - 1898/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215873_box2.jpg - 1899/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215873_box3.jpg - 1900/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215874_box1.jpg - 1901/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215874_box2.jpg - 1902/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215884_box1.jpg - 1903/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215884_box2.jpg - 1904/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.95images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215888_box1.jpg - 1905/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105599463_photo_177215888_box2.jpg - 1906/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105605357_photo_177227247_box1.jpg - 1907/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105605357_photo_177227247_box2.jpg - 1908/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105605357_photo_177227247_box3.jpg - 1909/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105605357_photo_177227266_box1.jpg - 1910/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105605357_photo_177227266_box2.jpg - 1911/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105605357_photo_177227266_box3.jpg - 1912/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105605357_photo_177227266_box4.jpg - 1913/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105605357_photo_177227266_box5.jpg - 1914/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105605357_photo_177227276_box1.jpg - 1915/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105605357_photo_177227276_box2.jpg - 1916/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105605357_photo_177227276_box3.jpg - 1917/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105605357_photo_177227276_box4.jpg - 1918/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105605357_photo_177227276_box5.jpg - 1919/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105667217_photo_177344397_box1.jpg - 1920/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105667217_photo_177344397_box2.jpg - 1921/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105667217_photo_177344397_box3.jpg - 1922/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105667217_photo_177344397_box4.jpg - 1923/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105667234_photo_177344461_box1.jpg - 1924/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105690986_photo_177387488_box1.jpg - 1925/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105690986_photo_177387493_box1.jpg - 1926/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105690986_photo_177387501_box1.jpg - 1927/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105690986_photo_177387501_box2.jpg - 1928/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105712471_photo_177432415_box1.jpg - 1929/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105712471_photo_177432415_box2.jpg - 1930/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105712471_photo_177432415_box3.jpg - 1931/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 49.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105712471_photo_177432420_box1.jpg - 1932/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105712471_photo_177432427_box1.jpg - 1933/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105712471_photo_177432430_box1.jpg - 1934/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105712471_photo_177432435_box1.jpg - 1935/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105712471_photo_177432435_box2.jpg - 1936/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105712471_photo_177432435_box3.jpg - 1937/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105712471_photo_177432435_box4.jpg - 1938/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456726_box1.jpg - 1939/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 63.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456726_box2.jpg - 1940/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456726_box3.jpg - 1941/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456726_box4.jpg - 1942/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456737_box1.jpg - 1943/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456737_box2.jpg - 1944/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456746_box1.jpg - 1945/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456746_box2.jpg - 1946/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456746_box3.jpg - 1947/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456746_box4.jpg - 1948/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456746_box5.jpg - 1949/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456769_box1.jpg - 1950/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456769_box2.jpg - 1951/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456769_box3.jpg - 1952/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456769_box4.jpg - 1953/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456769_box5.jpg - 1954/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456797_box1.jpg - 1955/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456797_box2.jpg - 1956/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456797_box3.jpg - 1957/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456797_box4.jpg - 1958/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456797_box5.jpg - 1959/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456806_box1.jpg - 1960/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456806_box2.jpg - 1961/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456806_box3.jpg - 1962/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456806_box4.jpg - 1963/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456826_box1.jpg - 1964/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456826_box2.jpg - 1965/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456826_box3.jpg - 1966/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456826_box4.jpg - 1967/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456826_box5.jpg - 1968/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456848_box1.jpg - 1969/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456848_box2.jpg - 1970/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456848_box3.jpg - 1971/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456856_box1.jpg - 1972/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456856_box2.jpg - 1973/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456856_box3.jpg - 1974/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456878_box1.jpg - 1975/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456878_box2.jpg - 1976/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456878_box3.jpg - 1977/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456878_box4.jpg - 1978/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456878_box5.jpg - 1979/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456895_box1.jpg - 1980/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456895_box2.jpg - 1981/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456895_box3.jpg - 1982/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456895_box4.jpg - 1983/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456895_box5.jpg - 1984/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456906_box1.jpg - 1985/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456906_box2.jpg - 1986/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456918_box1.jpg - 1987/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456918_box2.jpg - 1988/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456918_box3.jpg - 1989/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456918_box4.jpg - 1990/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 63.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456918_box5.jpg - 1991/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456943_box1.jpg - 1992/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456943_box2.jpg - 1993/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456949_box1.jpg - 1994/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456949_box2.jpg - 1995/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456950_box1.jpg - 1996/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456950_box2.jpg - 1997/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456975_box1.jpg - 1998/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456975_box2.jpg - 1999/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456975_box3.jpg - 2000/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456976_box1.jpg - 2001/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456976_box2.jpg - 2002/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456976_box3.jpg - 2003/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456976_box4.jpg - 2004/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456987_box1.jpg - 2005/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456987_box2.jpg - 2006/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456987_box3.jpg - 2007/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 74.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456987_box4.jpg - 2008/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456988_box1.jpg - 2009/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456988_box2.jpg - 2010/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456988_box3.jpg - 2011/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456988_box4.jpg - 2012/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 63.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105728452_photo_177456988_box5.jpg - 2013/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565021_box1.jpg - 2014/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565021_box2.jpg - 2015/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565021_box3.jpg - 2016/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565021_box4.jpg - 2017/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565021_box5.jpg - 2018/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565042_box1.jpg - 2019/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565042_box2.jpg - 2020/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565042_box3.jpg - 2021/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565042_box4.jpg - 2022/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565042_box5.jpg - 2023/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565063_box1.jpg - 2024/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565063_box2.jpg - 2025/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565063_box3.jpg - 2026/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565063_box4.jpg - 2027/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565063_box5.jpg - 2028/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565069_box1.jpg - 2029/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565069_box2.jpg - 2030/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565069_box3.jpg - 2031/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565139_box1.jpg - 2032/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565139_box2.jpg - 2033/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565139_box3.jpg - 2034/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565139_box4.jpg - 2035/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565139_box5.jpg - 2036/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565168_box1.jpg - 2037/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565168_box2.jpg - 2038/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565168_box3.jpg - 2039/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565168_box4.jpg - 2040/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565168_box5.jpg - 2041/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565225_box1.jpg - 2042/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565225_box2.jpg - 2043/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565225_box3.jpg - 2044/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565225_box4.jpg - 2045/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565225_box5.jpg - 2046/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565248_box1.jpg - 2047/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565248_box2.jpg - 2048/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565261_box1.jpg - 2049/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565261_box2.jpg - 2050/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565261_box3.jpg - 2051/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565261_box4.jpg - 2052/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785145_photo_177565261_box5.jpg - 2053/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785147_photo_177565008_box1.jpg - 2054/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785147_photo_177565008_box2.jpg - 2055/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785147_photo_177565008_box3.jpg - 2056/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785147_photo_177565008_box4.jpg - 2057/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785147_photo_177565046_box1.jpg - 2058/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785147_photo_177565081_box1.jpg - 2059/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785147_photo_177565081_box2.jpg - 2060/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785147_photo_177565112_box1.jpg - 2061/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785147_photo_177565112_box2.jpg - 2062/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785147_photo_177565124_box1.jpg - 2063/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785147_photo_177565124_box2.jpg - 2064/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785147_photo_177565205_box1.jpg - 2065/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785147_photo_177565206_box1.jpg - 2066/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785147_photo_177565206_box2.jpg - 2067/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785147_photo_177565232_box1.jpg - 2068/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785147_photo_177565232_box2.jpg - 2069/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785147_photo_177565232_box3.jpg - 2070/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785182_photo_177566438_box1.jpg - 2071/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785182_photo_177566450_box1.jpg - 2072/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105785182_photo_177566455_box1.jpg - 2073/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105816510_photo_177633148_box1.jpg - 2074/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105816510_photo_177633148_box2.jpg - 2075/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105816510_photo_177633148_box3.jpg - 2076/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105816510_photo_177633148_box4.jpg - 2077/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105816510_photo_177633148_box5.jpg - 2078/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105816510_photo_177633156_box1.jpg - 2079/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105816510_photo_177633156_box2.jpg - 2080/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105816510_photo_177633156_box3.jpg - 2081/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105816510_photo_177633156_box4.jpg - 2082/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105816510_photo_177633156_box5.jpg - 2083/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105839831_photo_177678170_box1.jpg - 2084/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105839831_photo_177678176_box1.jpg - 2085/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105839831_photo_177678176_box2.jpg - 2086/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105839831_photo_177678179_box1.jpg - 2087/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105839831_photo_177678186_box1.jpg - 2088/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105839831_photo_177678186_box2.jpg - 2089/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105901413_photo_177796635_box1.jpg - 2090/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105901413_photo_177796635_box2.jpg - 2091/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105901413_photo_177796635_box3.jpg - 2092/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105901413_photo_177796635_box4.jpg - 2093/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105901413_photo_177796635_box5.jpg - 2094/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105901414_photo_177796635_box1.jpg - 2095/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105901414_photo_177796635_box2.jpg - 2096/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105901414_photo_177796635_box3.jpg - 2097/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105914555_photo_177817582_box1.jpg - 2098/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105914555_photo_177817582_box2.jpg - 2099/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105914555_photo_177817582_box3.jpg - 2100/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105914555_photo_177817590_box1.jpg - 2101/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105914555_photo_177817590_box2.jpg - 2102/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105914555_photo_177817590_box3.jpg - 2103/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105914555_photo_177817590_box4.jpg - 2104/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_105914555_photo_177817590_box5.jpg - 2105/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1059442_photo_1328444_box1.jpg - 2106/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1059442_photo_1328444_box2.jpg - 2107/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1059442_photo_1328444_box3.jpg - 2108/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1059442_photo_1328444_box4.jpg - 2109/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1059454_photo_1328462_box1.jpg - 2110/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1059454_photo_1328462_box2.jpg - 2111/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1059454_photo_1328462_box3.jpg - 2112/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1059454_photo_1328462_box4.jpg - 2113/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106003833_photo_95777380_box1.jpg - 2114/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106003833_photo_95777380_box2.jpg - 2115/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106003833_photo_95777380_box3.jpg - 2116/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106003833_photo_95777380_box4.jpg - 2117/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106003833_photo_95777394_box1.jpg - 2118/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106003833_photo_95777394_box2.jpg - 2119/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106003833_photo_95777413_box1.jpg - 2120/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106004036_photo_90173754_box1.jpg - 2121/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106004036_photo_90173754_box2.jpg - 2122/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106004036_photo_90173754_box3.jpg - 2123/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106004036_photo_90173779_box1.jpg - 2124/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106004036_photo_90173779_box2.jpg - 2125/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106004036_photo_90173779_box3.jpg - 2126/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106004036_photo_90173779_box4.jpg - 2127/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106004036_photo_90173789_box1.jpg - 2128/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106004036_photo_90173789_box2.jpg - 2129/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106004036_photo_90173789_box3.jpg - 2130/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106004036_photo_90173789_box4.jpg - 2131/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106004036_photo_90173793_box1.jpg - 2132/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106004036_photo_90173793_box2.jpg - 2133/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106004036_photo_90173793_box3.jpg - 2134/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106004036_photo_90173793_box4.jpg - 2135/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106004036_photo_90173793_box5.jpg - 2136/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106004036_photo_90173868_box1.jpg - 2137/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106004036_photo_90173868_box2.jpg - 2138/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106004036_photo_90173868_box3.jpg - 2139/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106016049_photo_178011329_box1.jpg - 2140/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106016049_photo_178011329_box2.jpg - 2141/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106016050_photo_178011326_box1.jpg - 2142/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106016050_photo_178018037_box1.jpg - 2143/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106016050_photo_178018040_box1.jpg - 2144/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106016050_photo_178018040_box2.jpg - 2145/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106021353_photo_178019437_box1.jpg - 2146/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106021353_photo_178019437_box2.jpg - 2147/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106021353_photo_178019437_box3.jpg - 2148/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106021353_photo_178019437_box4.jpg - 2149/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106021353_photo_178019437_box5.jpg - 2150/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106021353_photo_178019466_box1.jpg - 2151/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106021353_photo_178019476_box1.jpg - 2152/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106021353_photo_178019480_box1.jpg - 2153/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106021353_photo_178019480_box2.jpg - 2154/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106021353_photo_178019480_box3.jpg - 2155/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106021353_photo_178019480_box4.jpg - 2156/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106021353_photo_178019480_box5.jpg - 2157/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106021353_photo_178019492_box1.jpg - 2158/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106021353_photo_178019492_box2.jpg - 2159/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106021353_photo_178019492_box3.jpg - 2160/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106021353_photo_178019492_box4.jpg - 2161/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106048085_photo_178070669_box1.jpg - 2162/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106055728_photo_178085400_box1.jpg - 2163/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106055728_photo_178085400_box2.jpg - 2164/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106055728_photo_178085400_box3.jpg - 2165/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106055728_photo_178085400_box4.jpg - 2166/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106055728_photo_178085400_box5.jpg - 2167/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106056644_photo_178087069_box1.jpg - 2168/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106056644_photo_178087471_box1.jpg - 2169/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106056644_photo_178087471_box2.jpg - 2170/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106056644_photo_178087471_box3.jpg - 2171/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106056644_photo_178087471_box4.jpg - 2172/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106056644_photo_178087471_box5.jpg - 2173/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106056644_photo_178087528_box1.jpg - 2174/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106056644_photo_178087528_box2.jpg - 2175/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106056644_photo_178087528_box3.jpg - 2176/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106056644_photo_178087567_box1.jpg - 2177/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106056644_photo_178087567_box2.jpg - 2178/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106056644_photo_178087567_box3.jpg - 2179/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106056644_photo_178087567_box4.jpg - 2180/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106056644_photo_178087633_box1.jpg - 2181/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106056644_photo_178087633_box2.jpg - 2182/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106056644_photo_178087633_box3.jpg - 2183/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106056644_photo_178087633_box4.jpg - 2184/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106056644_photo_178087633_box5.jpg - 2185/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106056644_photo_178087662_box1.jpg - 2186/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106056644_photo_178087662_box2.jpg - 2187/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106056644_photo_178087662_box3.jpg - 2188/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106056644_photo_178087662_box4.jpg - 2189/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106125874_photo_178214527_box1.jpg - 2190/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106125874_photo_178214539_box1.jpg - 2191/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106125874_photo_178214544_box1.jpg - 2192/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106125874_photo_178214551_box1.jpg - 2193/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106125874_photo_178214551_box2.jpg - 2194/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106125874_photo_178214552_box1.jpg - 2195/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106125874_photo_178214560_box1.jpg - 2196/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106125874_photo_178214560_box2.jpg - 2197/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106125874_photo_178214560_box3.jpg - 2198/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106125874_photo_178214562_box1.jpg - 2199/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106125874_photo_178214567_box1.jpg - 2200/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106125874_photo_178214570_box1.jpg - 2201/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106125874_photo_178214571_box1.jpg - 2202/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106125874_photo_178222071_box1.jpg - 2203/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106125874_photo_178222071_box2.jpg - 2204/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106125894_photo_178220529_box1.jpg - 2205/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106125894_photo_178220529_box2.jpg - 2206/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106126380_photo_178222044_box1.jpg - 2207/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106126380_photo_178222044_box2.jpg - 2208/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106126380_photo_178222044_box3.jpg - 2209/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106126380_photo_178222044_box4.jpg - 2210/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106126380_photo_178222048_box1.jpg - 2211/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106126380_photo_178222048_box2.jpg - 2212/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106126380_photo_178222056_box1.jpg - 2213/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106126380_photo_178222056_box2.jpg - 2214/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106126380_photo_178222057_box1.jpg - 2215/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106126380_photo_178222057_box2.jpg - 2216/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106161373_photo_178289837_box1.jpg - 2217/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106161373_photo_178289837_box2.jpg - 2218/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106161373_photo_178289837_box3.jpg - 2219/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106161373_photo_178289957_box1.jpg - 2220/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106161373_photo_178289957_box2.jpg - 2221/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106161373_photo_178289973_box1.jpg - 2222/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106161373_photo_178289973_box2.jpg - 2223/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106161373_photo_178289973_box3.jpg - 2224/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106161373_photo_178289973_box4.jpg - 2225/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106161373_photo_178289973_box5.jpg - 2226/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106173873_photo_178313488_box1.jpg - 2227/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106173873_photo_178313502_box1.jpg - 2228/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106173873_photo_178313502_box2.jpg - 2229/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106173873_photo_178313508_box1.jpg - 2230/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106173873_photo_178313508_box2.jpg - 2231/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.95images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106173873_photo_178313517_box1.jpg - 2232/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106173873_photo_178313517_box2.jpg - 2233/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106219205_photo_178400267_box1.jpg - 2234/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106219205_photo_178400267_box2.jpg - 2235/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106219205_photo_178400267_box3.jpg - 2236/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106219205_photo_178400267_box4.jpg - 2237/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106219205_photo_178400267_box5.jpg - 2238/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106219266_photo_178400362_box1.jpg - 2239/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106219266_photo_178400362_box2.jpg - 2240/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106244924_photo_178446512_box1.jpg - 2241/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106244924_photo_178446512_box2.jpg - 2242/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106244924_photo_178446524_box1.jpg - 2243/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106244924_photo_178446524_box2.jpg - 2244/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106244924_photo_178446524_box3.jpg - 2245/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106244924_photo_178446524_box4.jpg - 2246/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 63.31images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106244924_photo_178446524_box5.jpg - 2247/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106244924_photo_178446532_box1.jpg - 2248/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106244924_photo_178446540_box1.jpg - 2249/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106251745_photo_178453930_box1.jpg - 2250/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106251745_photo_178453931_box1.jpg - 2251/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106251745_photo_178453935_box1.jpg - 2252/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106251745_photo_178453935_box2.jpg - 2253/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106251745_photo_178453980_box1.jpg - 2254/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106251745_photo_178453983_box1.jpg - 2255/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106251745_photo_178453983_box2.jpg - 2256/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106251745_photo_178454031_box1.jpg - 2257/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106251777_photo_178455312_box1.jpg - 2258/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106251777_photo_178455315_box1.jpg - 2259/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106251777_photo_178455342_box1.jpg - 2260/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106251790_photo_178455565_box1.jpg - 2261/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106251790_photo_178455565_box2.jpg - 2262/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106251790_photo_178455584_box1.jpg - 2263/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106251790_photo_178455610_box1.jpg - 2264/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106251790_photo_178455647_box1.jpg - 2265/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106251790_photo_178455647_box2.jpg - 2266/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106251790_photo_178455647_box3.jpg - 2267/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106251790_photo_178455647_box4.jpg - 2268/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106320112_photo_178580949_box1.jpg - 2269/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106320112_photo_178580949_box2.jpg - 2270/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106320112_photo_178580949_box3.jpg - 2271/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106320112_photo_178580949_box4.jpg - 2272/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106320112_photo_178580957_box1.jpg - 2273/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106320112_photo_178580960_box1.jpg - 2274/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106320112_photo_178580968_box1.jpg - 2275/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106320112_photo_178580968_box2.jpg - 2276/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106320112_photo_178580968_box3.jpg - 2277/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106320112_photo_178580968_box4.jpg - 2278/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106320112_photo_178580968_box5.jpg - 2279/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106367954_photo_178671484_box1.jpg - 2280/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106367954_photo_178671491_box1.jpg - 2281/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106367954_photo_178671491_box2.jpg - 2282/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106367954_photo_178671491_box3.jpg - 2283/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106367954_photo_178671491_box4.jpg - 2284/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106382195_photo_178696122_box1.jpg - 2285/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106382195_photo_178696122_box2.jpg - 2286/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106382195_photo_178696126_box1.jpg - 2287/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106382195_photo_178696126_box2.jpg - 2288/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106382195_photo_178696129_box1.jpg - 2289/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106437775_photo_178799112_box1.jpg - 2290/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817177_box1.jpg - 2291/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817177_box2.jpg - 2292/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817177_box3.jpg - 2293/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817192_box1.jpg - 2294/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817192_box2.jpg - 2295/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817192_box3.jpg - 2296/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817193_box1.jpg - 2297/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817193_box2.jpg - 2298/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817195_box1.jpg - 2299/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817195_box2.jpg - 2300/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817195_box3.jpg - 2301/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817226_box1.jpg - 2302/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817226_box2.jpg - 2303/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817226_box3.jpg - 2304/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817228_box1.jpg - 2305/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817228_box2.jpg - 2306/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817228_box3.jpg - 2307/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817231_box1.jpg - 2308/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817231_box2.jpg - 2309/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817256_box1.jpg - 2310/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817264_box1.jpg - 2311/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817264_box2.jpg - 2312/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817264_box3.jpg - 2313/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817295_box1.jpg - 2314/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817295_box2.jpg - 2315/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817295_box3.jpg - 2316/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450543_photo_178817295_box4.jpg - 2317/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818181_box1.jpg - 2318/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818204_box1.jpg - 2319/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818204_box2.jpg - 2320/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818235_box1.jpg - 2321/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818235_box2.jpg - 2322/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818235_box3.jpg - 2323/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818235_box4.jpg - 2324/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818257_box1.jpg - 2325/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818257_box2.jpg - 2326/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818257_box3.jpg - 2327/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818257_box4.jpg - 2328/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818257_box5.jpg - 2329/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818263_box1.jpg - 2330/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818263_box2.jpg - 2331/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818263_box3.jpg - 2332/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818263_box4.jpg - 2333/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818263_box5.jpg - 2334/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818298_box1.jpg - 2335/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818303_box1.jpg - 2336/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818303_box2.jpg - 2337/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818303_box3.jpg - 2338/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818303_box4.jpg - 2339/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818321_box1.jpg - 2340/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818321_box2.jpg - 2341/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818321_box3.jpg - 2342/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818331_box1.jpg - 2343/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818331_box2.jpg - 2344/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818331_box3.jpg - 2345/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818331_box4.jpg - 2346/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818331_box5.jpg - 2347/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818360_box1.jpg - 2348/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 63.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818360_box2.jpg - 2349/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818365_box1.jpg - 2350/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818397_box1.jpg - 2351/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818397_box2.jpg - 2352/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818409_box1.jpg - 2353/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818409_box2.jpg - 2354/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818409_box3.jpg - 2355/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818409_box4.jpg - 2356/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818438_box1.jpg - 2357/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818455_box1.jpg - 2358/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818455_box2.jpg - 2359/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818455_box3.jpg - 2360/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818486_box1.jpg - 2361/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818486_box2.jpg - 2362/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450563_photo_178818486_box3.jpg - 2363/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450578_photo_178819309_box1.jpg - 2364/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450578_photo_178819309_box2.jpg - 2365/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450578_photo_178819309_box3.jpg - 2366/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450578_photo_178819334_box1.jpg - 2367/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450578_photo_178819358_box1.jpg - 2368/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106450578_photo_178819397_box1.jpg - 2369/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106550271_photo_179011725_box1.jpg - 2370/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106550724_photo_179012753_box1.jpg - 2371/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106550724_photo_179012753_box2.jpg - 2372/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106550724_photo_179012753_box3.jpg - 2373/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106630809_photo_179152912_box1.jpg - 2374/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106630809_photo_179152912_box2.jpg - 2375/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106630809_photo_179152912_box3.jpg - 2376/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106630809_photo_179152912_box4.jpg - 2377/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106630809_photo_179152997_box1.jpg - 2378/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106630809_photo_179152997_box2.jpg - 2379/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106630809_photo_179152997_box3.jpg - 2380/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106630813_photo_179152699_box1.jpg - 2381/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106630813_photo_179152699_box2.jpg - 2382/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106630813_photo_179152699_box3.jpg - 2383/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106630813_photo_179152699_box4.jpg - 2384/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106630813_photo_179152699_box5.jpg - 2385/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106630813_photo_179152912_box1.jpg - 2386/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106630813_photo_179152912_box2.jpg - 2387/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106630813_photo_179152912_box3.jpg - 2388/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106630813_photo_179152912_box4.jpg - 2389/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106630813_photo_179152912_box5.jpg - 2390/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106630813_photo_179152997_box1.jpg - 2391/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106630813_photo_179152997_box2.jpg - 2392/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106630813_photo_179152997_box3.jpg - 2393/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106630813_photo_179152997_box4.jpg - 2394/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106630813_photo_179152997_box5.jpg - 2395/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106631239_photo_179161390_box1.jpg - 2396/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106631239_photo_179161390_box2.jpg - 2397/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106631239_photo_179161390_box3.jpg - 2398/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106631239_photo_179161390_box4.jpg - 2399/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106631239_photo_179161415_box1.jpg - 2400/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106631239_photo_179161415_box2.jpg - 2401/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106631239_photo_179161415_box3.jpg - 2402/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106631239_photo_179161415_box4.jpg - 2403/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106631239_photo_179161415_box5.jpg - 2404/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106631239_photo_179161435_box1.jpg - 2405/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106631239_photo_179161435_box2.jpg - 2406/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106631239_photo_179161435_box3.jpg - 2407/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106631239_photo_179161435_box4.jpg - 2408/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106631239_photo_179161435_box5.jpg - 2409/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106631239_photo_179161436_box1.jpg - 2410/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106631239_photo_179161436_box2.jpg - 2411/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106631239_photo_179161436_box3.jpg - 2412/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106631239_photo_179161436_box4.jpg - 2413/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106631239_photo_179161450_box1.jpg - 2414/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106631239_photo_179161450_box2.jpg - 2415/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106631239_photo_179161450_box3.jpg - 2416/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106631239_photo_179161454_box1.jpg - 2417/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218268_box1.jpg - 2418/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218268_box2.jpg - 2419/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218268_box3.jpg - 2420/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218268_box4.jpg - 2421/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218268_box5.jpg - 2422/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218273_box1.jpg - 2423/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218273_box2.jpg - 2424/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218273_box3.jpg - 2425/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218273_box4.jpg - 2426/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218275_box1.jpg - 2427/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218278_box1.jpg - 2428/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218278_box2.jpg - 2429/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218278_box3.jpg - 2430/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.41images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218278_box4.jpg - 2431/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218278_box5.jpg - 2432/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218291_box1.jpg - 2433/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218291_box2.jpg - 2434/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218291_box3.jpg - 2435/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218291_box4.jpg - 2436/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218291_box5.jpg - 2437/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218294_box1.jpg - 2438/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218294_box2.jpg - 2439/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218294_box3.jpg - 2440/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218294_box4.jpg - 2441/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218299_box1.jpg - 2442/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218299_box2.jpg - 2443/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218299_box3.jpg - 2444/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218299_box4.jpg - 2445/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218299_box5.jpg - 2446/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218306_box1.jpg - 2447/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218306_box2.jpg - 2448/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 46.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218316_box1.jpg - 2449/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218316_box2.jpg - 2450/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218316_box3.jpg - 2451/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218316_box4.jpg - 2452/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 46.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218321_box1.jpg - 2453/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218321_box2.jpg - 2454/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218331_box1.jpg - 2455/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218331_box2.jpg - 2456/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218331_box3.jpg - 2457/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218331_box4.jpg - 2458/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.41images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218331_box5.jpg - 2459/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218338_box1.jpg - 2460/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218338_box2.jpg - 2461/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218338_box3.jpg - 2462/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218338_box4.jpg - 2463/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657672_photo_179218338_box5.jpg - 2464/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657673_photo_179218268_box1.jpg - 2465/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657673_photo_179218268_box2.jpg - 2466/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657673_photo_179218275_box1.jpg - 2467/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657673_photo_179218275_box2.jpg - 2468/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657673_photo_179218278_box1.jpg - 2469/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657673_photo_179218291_box1.jpg - 2470/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657673_photo_179218294_box1.jpg - 2471/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106657673_photo_179218299_box1.jpg - 2472/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106666137_photo_179236356_box1.jpg - 2473/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106666137_photo_179236356_box2.jpg - 2474/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106666137_photo_179236356_box3.jpg - 2475/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106666137_photo_179236356_box4.jpg - 2476/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106666137_photo_179236356_box5.jpg - 2477/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106666137_photo_179236414_box1.jpg - 2478/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106666137_photo_179236414_box2.jpg - 2479/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106666137_photo_179236414_box3.jpg - 2480/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106666137_photo_179236414_box4.jpg - 2481/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106666137_photo_179236414_box5.jpg - 2482/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106666137_photo_179236415_box1.jpg - 2483/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106666137_photo_179236415_box2.jpg - 2484/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106666137_photo_179236415_box3.jpg - 2485/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.41images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106666137_photo_179236415_box4.jpg - 2486/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106666137_photo_179236415_box5.jpg - 2487/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752835_photo_179396417_box1.jpg - 2488/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752835_photo_179396439_box1.jpg - 2489/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752835_photo_179396442_box1.jpg - 2490/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752835_photo_179396442_box2.jpg - 2491/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398334_box1.jpg - 2492/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398334_box2.jpg - 2493/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398334_box3.jpg - 2494/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398334_box4.jpg - 2495/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398334_box5.jpg - 2496/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398338_box1.jpg - 2497/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398338_box2.jpg - 2498/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398338_box3.jpg - 2499/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398338_box4.jpg - 2500/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398338_box5.jpg - 2501/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398356_box1.jpg - 2502/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398356_box2.jpg - 2503/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398364_box1.jpg - 2504/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398364_box2.jpg - 2505/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398364_box3.jpg - 2506/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398385_box1.jpg - 2507/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398385_box2.jpg - 2508/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398385_box3.jpg - 2509/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398385_box4.jpg - 2510/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398385_box5.jpg - 2511/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398406_box1.jpg - 2512/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398406_box2.jpg - 2513/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398421_box1.jpg - 2514/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398421_box2.jpg - 2515/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398441_box1.jpg - 2516/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398441_box2.jpg - 2517/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398441_box3.jpg - 2518/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398441_box4.jpg - 2519/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398455_box1.jpg - 2520/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106752887_photo_179398455_box2.jpg - 2521/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1068273_photo_1339178_box1.jpg - 2522/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1068273_photo_1339178_box2.jpg - 2523/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1068273_photo_1402268_box1.jpg - 2524/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1068273_photo_1402268_box2.jpg - 2525/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1068273_photo_1402268_box3.jpg - 2526/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1068273_photo_1402268_box4.jpg - 2527/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1068273_photo_1402268_box5.jpg - 2528/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1068300_photo_1339207_box1.jpg - 2529/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1068300_photo_1339207_box2.jpg - 2530/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1068300_photo_1339207_box3.jpg - 2531/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1068463_photo_1339369_box1.jpg - 2532/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1068463_photo_1339369_box2.jpg - 2533/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1068463_photo_1339369_box3.jpg - 2534/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1068463_photo_1339369_box4.jpg - 2535/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1068463_photo_1339370_box1.jpg - 2536/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1068463_photo_1339370_box2.jpg - 2537/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1068463_photo_1339370_box3.jpg - 2538/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_1068463_photo_1339370_box4.jpg - 2539/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106906483_photo_179689911_box1.jpg - 2540/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106906483_photo_179689911_box2.jpg - 2541/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106906483_photo_179689911_box3.jpg - 2542/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106906483_photo_179689919_box1.jpg - 2543/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106906483_photo_179689925_box1.jpg - 2544/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106906483_photo_179689931_box1.jpg - 2545/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106906483_photo_179689931_box2.jpg - 2546/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106906483_photo_179689931_box3.jpg - 2547/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106906483_photo_179689931_box4.jpg - 2548/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106906483_photo_179689938_box1.jpg - 2549/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106906483_photo_179689938_box2.jpg - 2550/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106906483_photo_179689938_box3.jpg - 2551/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106906483_photo_179689938_box4.jpg - 2552/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106906483_photo_179689938_box5.jpg - 2553/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106906483_photo_179689945_box1.jpg - 2554/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106906483_photo_179689945_box2.jpg - 2555/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106906483_photo_179689945_box3.jpg - 2556/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106906483_photo_179689945_box4.jpg - 2557/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_106906483_photo_179689945_box5.jpg - 2558/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107061147_photo_179988110_box1.jpg - 2559/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107061147_photo_179988110_box2.jpg - 2560/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107061147_photo_179988110_box3.jpg - 2561/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107061147_photo_179988110_box4.jpg - 2562/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107079816_photo_180024835_box1.jpg - 2563/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107079816_photo_180024835_box2.jpg - 2564/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 49.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107079816_photo_180024835_box3.jpg - 2565/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107079816_photo_180024835_box4.jpg - 2566/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107079816_photo_180024835_box5.jpg - 2567/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107079816_photo_180025222_box1.jpg - 2568/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107079816_photo_180025222_box2.jpg - 2569/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107079816_photo_180025222_box3.jpg - 2570/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107079816_photo_180025222_box4.jpg - 2571/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107079816_photo_180025222_box5.jpg - 2572/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107171888_photo_180200082_box1.jpg - 2573/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107171888_photo_180200082_box2.jpg - 2574/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107171888_photo_180200082_box3.jpg - 2575/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107171888_photo_180200082_box4.jpg - 2576/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107171888_photo_180200082_box5.jpg - 2577/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107171906_photo_180200105_box1.jpg - 2578/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107171906_photo_180200105_box2.jpg - 2579/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180364628_box1.jpg - 2580/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180364628_box2.jpg - 2581/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180364628_box3.jpg - 2582/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180364628_box4.jpg - 2583/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180364628_box5.jpg - 2584/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180364666_box1.jpg - 2585/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180364666_box2.jpg - 2586/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180364666_box3.jpg - 2587/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180364699_box1.jpg - 2588/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180364699_box2.jpg - 2589/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180364699_box3.jpg - 2590/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180364699_box4.jpg - 2591/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180364736_box1.jpg - 2592/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180364736_box2.jpg - 2593/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180364736_box3.jpg - 2594/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180364778_box1.jpg - 2595/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180364818_box1.jpg - 2596/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.41images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180364818_box2.jpg - 2597/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180364818_box3.jpg - 2598/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180364859_box1.jpg - 2599/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180364859_box2.jpg - 2600/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180365151_box1.jpg - 2601/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180365151_box2.jpg - 2602/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180365151_box3.jpg - 2603/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180365151_box4.jpg - 2604/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180365151_box5.jpg - 2605/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265023_photo_180365168_box1.jpg - 2606/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265028_photo_180366534_box1.jpg - 2607/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265028_photo_180366534_box2.jpg - 2608/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265028_photo_180366534_box3.jpg - 2609/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265028_photo_180366656_box1.jpg - 2610/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265028_photo_180366687_box1.jpg - 2611/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265028_photo_180366687_box2.jpg - 2612/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107265028_photo_180366708_box1.jpg - 2613/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107319959_photo_180475251_box1.jpg - 2614/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107319959_photo_180475256_box1.jpg - 2615/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107319959_photo_180475265_box1.jpg - 2616/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107325072_photo_180482460_box1.jpg - 2617/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107325072_photo_180482460_box2.jpg - 2618/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107359856_photo_180549112_box1.jpg - 2619/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 63.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107359856_photo_180549112_box2.jpg - 2620/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107359856_photo_180549112_box3.jpg - 2621/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107359856_photo_180549115_box1.jpg - 2622/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107359856_photo_180549118_box1.jpg - 2623/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.41images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107359856_photo_180549118_box2.jpg - 2624/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107359856_photo_180549118_box3.jpg - 2625/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107359856_photo_180549118_box4.jpg - 2626/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107401326_photo_180628788_box1.jpg - 2627/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107401326_photo_180628803_box1.jpg - 2628/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107401326_photo_180628815_box1.jpg - 2629/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180678921_box1.jpg - 2630/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180678921_box2.jpg - 2631/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180678921_box3.jpg - 2632/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180678921_box4.jpg - 2633/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180678921_box5.jpg - 2634/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180678935_box1.jpg - 2635/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180678935_box2.jpg - 2636/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180678935_box3.jpg - 2637/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180678935_box4.jpg - 2638/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180678935_box5.jpg - 2639/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180678959_box1.jpg - 2640/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180678959_box2.jpg - 2641/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180678959_box3.jpg - 2642/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180678959_box4.jpg - 2643/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180678959_box5.jpg - 2644/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180678996_box1.jpg - 2645/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180678996_box2.jpg - 2646/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180678996_box3.jpg - 2647/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180678996_box4.jpg - 2648/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180678996_box5.jpg - 2649/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180679008_box1.jpg - 2650/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180679008_box2.jpg - 2651/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180679008_box3.jpg - 2652/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180679008_box4.jpg - 2653/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180679008_box5.jpg - 2654/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180679022_box1.jpg - 2655/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180679022_box2.jpg - 2656/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180679022_box3.jpg - 2657/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180679022_box4.jpg - 2658/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180679022_box5.jpg - 2659/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180679080_box1.jpg - 2660/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180679080_box2.jpg - 2661/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180679080_box3.jpg - 2662/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180679080_box4.jpg - 2663/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107429877_photo_180679080_box5.jpg - 2664/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107433431_photo_180689859_box1.jpg - 2665/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107433431_photo_180689859_box2.jpg - 2666/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107433431_photo_180689863_box1.jpg - 2667/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107439734_photo_180701809_box1.jpg - 2668/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107439734_photo_180701809_box2.jpg - 2669/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107439734_photo_180701809_box3.jpg - 2670/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107439734_photo_180701822_box1.jpg - 2671/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107439734_photo_180701836_box1.jpg - 2672/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107540786_photo_180892379_box1.jpg - 2673/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107540786_photo_180892379_box2.jpg - 2674/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107540786_photo_180892379_box3.jpg - 2675/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107540786_photo_180892379_box4.jpg - 2676/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107540786_photo_180892379_box5.jpg - 2677/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107540786_photo_180892385_box1.jpg - 2678/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107540786_photo_180892385_box2.jpg - 2679/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107540786_photo_180892385_box3.jpg - 2680/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107540786_photo_180892385_box4.jpg - 2681/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107540786_photo_180892385_box5.jpg - 2682/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107540786_photo_180892389_box1.jpg - 2683/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107540786_photo_180892389_box2.jpg - 2684/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107540786_photo_180892389_box3.jpg - 2685/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107540786_photo_180892389_box4.jpg - 2686/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107540786_photo_180892389_box5.jpg - 2687/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107540786_photo_180892392_box1.jpg - 2688/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107540786_photo_180892392_box2.jpg - 2689/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107540786_photo_180892392_box3.jpg - 2690/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107540786_photo_180892392_box4.jpg - 2691/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107540786_photo_180892392_box5.jpg - 2692/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107547488_photo_180903431_box1.jpg - 2693/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107547488_photo_180903431_box2.jpg - 2694/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107547488_photo_180903431_box3.jpg - 2695/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107547488_photo_180903431_box4.jpg - 2696/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107547488_photo_180903431_box5.jpg - 2697/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107547488_photo_180903444_box1.jpg - 2698/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107547488_photo_180903444_box2.jpg - 2699/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107547488_photo_180903444_box3.jpg - 2700/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107599835_photo_181001876_box1.jpg - 2701/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107599835_photo_181001876_box2.jpg - 2702/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107599835_photo_181001876_box3.jpg - 2703/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107599835_photo_181001876_box4.jpg - 2704/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107599835_photo_181001876_box5.jpg - 2705/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107599835_photo_181001890_box1.jpg - 2706/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107599835_photo_181001890_box2.jpg - 2707/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107599835_photo_181001890_box3.jpg - 2708/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107599835_photo_181001890_box4.jpg - 2709/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107599835_photo_181001890_box5.jpg - 2710/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107633162_photo_181066657_box1.jpg - 2711/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107633162_photo_181066657_box2.jpg - 2712/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107633162_photo_181066657_box3.jpg - 2713/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107633162_photo_181066670_box1.jpg - 2714/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107633162_photo_181066670_box2.jpg - 2715/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107633162_photo_181066670_box3.jpg - 2716/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107633162_photo_181066670_box4.jpg - 2717/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107633162_photo_181066670_box5.jpg - 2718/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107669465_photo_181134703_box1.jpg - 2719/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107669465_photo_181134703_box2.jpg - 2720/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107669465_photo_181134703_box3.jpg - 2721/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107669465_photo_181134703_box4.jpg - 2722/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107669465_photo_181134729_box1.jpg - 2723/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107669465_photo_181134729_box2.jpg - 2724/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107669465_photo_181134729_box3.jpg - 2725/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107669465_photo_181134749_box1.jpg - 2726/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107669465_photo_181134749_box2.jpg - 2727/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107669465_photo_181134749_box3.jpg - 2728/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107672603_photo_181132721_box1.jpg - 2729/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107672603_photo_181132727_box1.jpg - 2730/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107672603_photo_181132736_box1.jpg - 2731/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107672603_photo_181132745_box1.jpg - 2732/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107672603_photo_181132752_box1.jpg - 2733/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107672603_photo_181132752_box2.jpg - 2734/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107672603_photo_181132752_box3.jpg - 2735/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107672603_photo_181132752_box4.jpg - 2736/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107672603_photo_181132752_box5.jpg - 2737/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107672603_photo_181132758_box1.jpg - 2738/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107672603_photo_181132762_box1.jpg - 2739/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107672603_photo_181132772_box1.jpg - 2740/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107672603_photo_181132772_box2.jpg - 2741/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107672603_photo_181132772_box3.jpg - 2742/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107672603_photo_181132780_box1.jpg - 2743/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107672613_photo_181135010_box1.jpg - 2744/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107672613_photo_181135010_box2.jpg - 2745/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107672613_photo_181135010_box3.jpg - 2746/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 49.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107672613_photo_181135010_box4.jpg - 2747/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107672613_photo_181135010_box5.jpg - 2748/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107710947_photo_181212067_box1.jpg - 2749/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107710947_photo_181212067_box2.jpg - 2750/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107710947_photo_181212067_box3.jpg - 2751/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107710947_photo_181212067_box4.jpg - 2752/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107710947_photo_181212067_box5.jpg - 2753/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107897956_photo_181558972_box1.jpg - 2754/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107897956_photo_181558972_box2.jpg - 2755/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181627564_box1.jpg - 2756/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181627564_box2.jpg - 2757/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181627564_box3.jpg - 2758/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181627564_box4.jpg - 2759/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181627564_box5.jpg - 2760/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181627571_box1.jpg - 2761/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181627571_box2.jpg - 2762/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181627571_box3.jpg - 2763/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181627571_box4.jpg - 2764/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181627576_box1.jpg - 2765/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181627576_box2.jpg - 2766/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181627576_box3.jpg - 2767/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181627576_box4.jpg - 2768/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181627576_box5.jpg - 2769/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181627582_box1.jpg - 2770/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181627582_box2.jpg - 2771/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181627582_box3.jpg - 2772/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181627582_box4.jpg - 2773/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181627587_box1.jpg - 2774/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181627587_box2.jpg - 2775/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181788834_box1.jpg - 2776/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181788834_box2.jpg - 2777/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181788834_box3.jpg - 2778/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181788834_box4.jpg - 2779/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107934433_photo_181788834_box5.jpg - 2780/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107935230_photo_181628995_box1.jpg - 2781/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107935230_photo_181628998_box1.jpg - 2782/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_107935735_photo_181629606_box1.jpg - 2783/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108019768_photo_181788002_box1.jpg - 2784/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108019768_photo_181788002_box2.jpg - 2785/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108019768_photo_181788002_box3.jpg - 2786/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108019768_photo_181788002_box4.jpg - 2787/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108019768_photo_181788002_box5.jpg - 2788/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 46.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108019768_photo_181788008_box1.jpg - 2789/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108019768_photo_181788008_box2.jpg - 2790/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108021398_photo_181790899_box1.jpg - 2791/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108021398_photo_181790906_box1.jpg - 2792/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108021398_photo_181790916_box1.jpg - 2793/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108021398_photo_181790916_box2.jpg - 2794/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108021398_photo_181790916_box3.jpg - 2795/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850772_box1.jpg - 2796/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850772_box2.jpg - 2797/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850772_box3.jpg - 2798/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850772_box4.jpg - 2799/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850772_box5.jpg - 2800/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850781_box1.jpg - 2801/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850781_box2.jpg - 2802/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850781_box3.jpg - 2803/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850781_box4.jpg - 2804/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850792_box1.jpg - 2805/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850792_box2.jpg - 2806/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850792_box3.jpg - 2807/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850792_box4.jpg - 2808/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850792_box5.jpg - 2809/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850802_box1.jpg - 2810/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850802_box2.jpg - 2811/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850802_box3.jpg - 2812/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850802_box4.jpg - 2813/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850802_box5.jpg - 2814/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850826_box1.jpg - 2815/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850826_box2.jpg - 2816/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850826_box3.jpg - 2817/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850826_box4.jpg - 2818/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850826_box5.jpg - 2819/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850840_box1.jpg - 2820/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850840_box2.jpg - 2821/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850840_box3.jpg - 2822/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850840_box4.jpg - 2823/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108054071_photo_181850840_box5.jpg - 2824/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108145344_photo_182024891_box1.jpg - 2825/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108145345_photo_182024911_box1.jpg - 2826/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108145345_photo_182024911_box2.jpg - 2827/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108145345_photo_182024911_box3.jpg - 2828/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108145345_photo_182024919_box1.jpg - 2829/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108145345_photo_182024919_box2.jpg - 2830/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108173967_photo_181850781_box1.jpg - 2831/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108173967_photo_181850781_box2.jpg - 2832/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108173967_photo_181850781_box3.jpg - 2833/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108173967_photo_181850792_box1.jpg - 2834/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108173967_photo_181850792_box2.jpg - 2835/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108173967_photo_181850792_box3.jpg - 2836/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108173967_photo_181850792_box4.jpg - 2837/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108173967_photo_181850792_box5.jpg - 2838/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108173967_photo_181850802_box1.jpg - 2839/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108173967_photo_181850802_box2.jpg - 2840/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108173967_photo_181850802_box3.jpg - 2841/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108188958_photo_182107689_box1.jpg - 2842/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108188958_photo_182107689_box2.jpg - 2843/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108188958_photo_182107689_box3.jpg - 2844/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108188958_photo_182107689_box4.jpg - 2845/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108188958_photo_182107689_box5.jpg - 2846/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108188958_photo_182107701_box1.jpg - 2847/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108188958_photo_182107701_box2.jpg - 2848/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108188958_photo_182107701_box3.jpg - 2849/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108189393_photo_182108336_box1.jpg - 2850/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108189393_photo_182108347_box1.jpg - 2851/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108189393_photo_182108347_box2.jpg - 2852/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108189393_photo_182108347_box3.jpg - 2853/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108211315_photo_182148223_box1.jpg - 2854/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302466_box1.jpg - 2855/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302466_box2.jpg - 2856/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302466_box3.jpg - 2857/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302470_box1.jpg - 2858/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302470_box2.jpg - 2859/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302476_box1.jpg - 2860/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302476_box2.jpg - 2861/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302476_box3.jpg - 2862/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302476_box4.jpg - 2863/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302476_box5.jpg - 2864/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302478_box1.jpg - 2865/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302478_box2.jpg - 2866/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302478_box3.jpg - 2867/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302478_box4.jpg - 2868/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 46.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302478_box5.jpg - 2869/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302481_box1.jpg - 2870/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302481_box2.jpg - 2871/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302481_box3.jpg - 2872/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302481_box4.jpg - 2873/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302483_box1.jpg - 2874/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302483_box2.jpg - 2875/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302483_box3.jpg - 2876/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302483_box4.jpg - 2877/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302484_box1.jpg - 2878/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302484_box2.jpg - 2879/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302484_box3.jpg - 2880/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302484_box4.jpg - 2881/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108292445_photo_182302484_box5.jpg - 2882/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108328630_photo_182367632_box1.jpg - 2883/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108390002_photo_182482707_box1.jpg - 2884/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108390002_photo_182482707_box2.jpg - 2885/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108390002_photo_182482707_box3.jpg - 2886/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108390002_photo_182482707_box4.jpg - 2887/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108390002_photo_182482707_box5.jpg - 2888/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108390002_photo_182482824_box1.jpg - 2889/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108390002_photo_182482824_box2.jpg - 2890/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108390002_photo_182482824_box3.jpg - 2891/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108390002_photo_182482824_box4.jpg - 2892/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108390002_photo_182482824_box5.jpg - 2893/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108405704_photo_182512501_box1.jpg - 2894/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108405704_photo_182512501_box2.jpg - 2895/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108405704_photo_182512501_box3.jpg - 2896/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 74.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108405704_photo_182512501_box4.jpg - 2897/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108405704_photo_182512501_box5.jpg - 2898/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108405704_photo_182512540_box1.jpg - 2899/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108405704_photo_182512540_box2.jpg - 2900/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108405704_photo_182512540_box3.jpg - 2901/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108405704_photo_182512540_box4.jpg - 2902/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108405704_photo_182512540_box5.jpg - 2903/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108405704_photo_182512546_box1.jpg - 2904/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108405704_photo_182512546_box2.jpg - 2905/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108405704_photo_182512546_box3.jpg - 2906/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108405704_photo_182513055_box1.jpg - 2907/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108405704_photo_182513055_box2.jpg - 2908/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108405704_photo_182513055_box3.jpg - 2909/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108405704_photo_182513055_box4.jpg - 2910/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 49.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108405704_photo_182513055_box5.jpg - 2911/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108406065_photo_182513673_box1.jpg - 2912/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108406065_photo_182513673_box2.jpg - 2913/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108406065_photo_182513685_box1.jpg - 2914/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108406065_photo_182513685_box2.jpg - 2915/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108406065_photo_182513860_box1.jpg - 2916/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108420548_photo_182541726_box1.jpg - 2917/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108420548_photo_182541758_box1.jpg - 2918/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108420548_photo_182541761_box1.jpg - 2919/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108420548_photo_182541761_box2.jpg - 2920/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108420548_photo_182541761_box3.jpg - 2921/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108420548_photo_182541764_box1.jpg - 2922/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108518030_photo_182714493_box1.jpg - 2923/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108518030_photo_182714493_box2.jpg - 2924/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108518030_photo_182714516_box1.jpg - 2925/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108518030_photo_182714516_box2.jpg - 2926/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108518030_photo_182714549_box1.jpg - 2927/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108518030_photo_182714549_box2.jpg - 2928/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108518030_photo_182714549_box3.jpg - 2929/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108574063_photo_182829861_box1.jpg - 2930/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.41images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108574063_photo_182829861_box2.jpg - 2931/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108574063_photo_182829861_box3.jpg - 2932/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108574063_photo_182829861_box4.jpg - 2933/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108574063_photo_182829861_box5.jpg - 2934/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108580930_photo_182842201_box1.jpg - 2935/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108580930_photo_182842201_box2.jpg - 2936/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108589548_photo_182860254_box1.jpg - 2937/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108589548_photo_182860258_box1.jpg - 2938/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108589548_photo_182860296_box1.jpg - 2939/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108589548_photo_182860296_box2.jpg - 2940/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108589548_photo_182860296_box3.jpg - 2941/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108589548_photo_182860296_box4.jpg - 2942/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108589548_photo_182860296_box5.jpg - 2943/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108589678_photo_182858172_box1.jpg - 2944/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108589678_photo_182858172_box2.jpg - 2945/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108623571_photo_182922030_box1.jpg - 2946/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108623571_photo_182922030_box2.jpg - 2947/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108623571_photo_182922043_box1.jpg - 2948/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108623571_photo_182922064_box1.jpg - 2949/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108623571_photo_182922064_box2.jpg - 2950/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108623571_photo_182922064_box3.jpg - 2951/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108623784_photo_182922295_box1.jpg - 2952/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108623784_photo_182922309_box1.jpg - 2953/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108623784_photo_182922309_box2.jpg - 2954/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108623784_photo_182922325_box1.jpg - 2955/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108671615_photo_183011822_box1.jpg - 2956/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108671615_photo_183011836_box1.jpg - 2957/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108671615_photo_183011895_box1.jpg - 2958/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108671615_photo_183012049_box1.jpg - 2959/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108671615_photo_183012049_box2.jpg - 2960/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108671615_photo_183012049_box3.jpg - 2961/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.60images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694734_photo_183046548_box1.jpg - 2962/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694734_photo_183046548_box2.jpg - 2963/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694738_photo_183050301_box1.jpg - 2964/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694738_photo_183050301_box2.jpg - 2965/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694738_photo_183050301_box3.jpg - 2966/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694738_photo_183050301_box4.jpg - 2967/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694738_photo_183050305_box1.jpg - 2968/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694738_photo_183050305_box2.jpg - 2969/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694738_photo_183050305_box3.jpg - 2970/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694738_photo_183054938_box1.jpg - 2971/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694738_photo_183054938_box2.jpg - 2972/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694743_photo_183053718_box1.jpg - 2973/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694743_photo_183053718_box2.jpg - 2974/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694743_photo_183053718_box3.jpg - 2975/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694743_photo_183053718_box4.jpg - 2976/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.41images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694743_photo_183053718_box5.jpg - 2977/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694744_photo_183053796_box1.jpg - 2978/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694744_photo_183053796_box2.jpg - 2979/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694744_photo_183053796_box3.jpg - 2980/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694744_photo_183053796_box4.jpg - 2981/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694744_photo_183053801_box1.jpg - 2982/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694744_photo_183053801_box2.jpg - 2983/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694744_photo_183053801_box3.jpg - 2984/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694748_photo_183054050_box1.jpg - 2985/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694748_photo_183054057_box1.jpg - 2986/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694748_photo_183054057_box2.jpg - 2987/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108694748_photo_183054057_box3.jpg - 2988/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730841_photo_183121244_box1.jpg - 2989/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730841_photo_183121244_box2.jpg - 2990/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730841_photo_183121245_box1.jpg - 2991/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730841_photo_183121245_box2.jpg - 2992/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730841_photo_183121253_box1.jpg - 2993/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730841_photo_183121253_box2.jpg - 2994/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730841_photo_183121253_box3.jpg - 2995/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730841_photo_183121289_box1.jpg - 2996/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730841_photo_183121293_box1.jpg - 2997/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730841_photo_183121293_box2.jpg - 2998/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730841_photo_183121293_box3.jpg - 2999/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730841_photo_183121310_box1.jpg - 3000/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730841_photo_183121310_box2.jpg - 3001/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730841_photo_183121310_box3.jpg - 3002/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_183121297_box1.jpg - 3003/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_183121297_box2.jpg - 3004/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_183121308_box1.jpg - 3005/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_183121308_box2.jpg - 3006/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_183121311_box1.jpg - 3007/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_183121311_box2.jpg - 3008/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_183121318_box1.jpg - 3009/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_183121357_box1.jpg - 3010/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_183121357_box2.jpg - 3011/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_183121357_box3.jpg - 3012/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_183121357_box4.jpg - 3013/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_183121367_box1.jpg - 3014/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_183121367_box2.jpg - 3015/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_184217523_box1.jpg - 3016/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_184217523_box2.jpg - 3017/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_184217523_box3.jpg - 3018/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_184217570_box1.jpg - 3019/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_184217570_box2.jpg - 3020/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_184217570_box3.jpg - 3021/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_184217581_box1.jpg - 3022/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.41images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_184217581_box2.jpg - 3023/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 74.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_184217581_box3.jpg - 3024/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_184217581_box4.jpg - 3025/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_184217614_box1.jpg - 3026/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_184217614_box2.jpg - 3027/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_184217614_box3.jpg - 3028/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_184217614_box4.jpg - 3029/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_184217614_box5.jpg - 3030/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_184217644_box1.jpg - 3031/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_184217644_box2.jpg - 3032/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108730842_photo_184217644_box3.jpg - 3033/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 46.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108740166_photo_183141976_box1.jpg - 3034/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108740166_photo_183141976_box2.jpg - 3035/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108788387_photo_183234436_box1.jpg - 3036/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108788387_photo_183234436_box2.jpg - 3037/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108788387_photo_183234436_box3.jpg - 3038/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108788387_photo_183234443_box1.jpg - 3039/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108788387_photo_183234443_box2.jpg - 3040/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108788387_photo_183234443_box3.jpg - 3041/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108788387_photo_183234443_box4.jpg - 3042/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.82images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108788387_photo_183234445_box1.jpg - 3043/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108788387_photo_183234445_box2.jpg - 3044/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108788387_photo_183234445_box3.jpg - 3045/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108791040_photo_183239582_box1.jpg - 3046/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108791040_photo_190597510_box1.jpg - 3047/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108791040_photo_190597510_box2.jpg - 3048/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108791040_photo_210034404_box1.jpg - 3049/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108791040_photo_210034404_box2.jpg - 3050/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108856878_photo_183362240_box1.jpg - 3051/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108856878_photo_201761181_box1.jpg - 3052/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108856878_photo_201761181_box2.jpg - 3053/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108856878_photo_201761181_box3.jpg - 3054/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108860079_photo_183367674_box1.jpg - 3055/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108860079_photo_183367674_box2.jpg - 3056/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.42images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108860079_photo_183367674_box3.jpg - 3057/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108860079_photo_183367678_box1.jpg - 3058/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108860079_photo_183367678_box2.jpg - 3059/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108860079_photo_183367678_box3.jpg - 3060/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108860079_photo_183367678_box4.jpg - 3061/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108860079_photo_183367678_box5.jpg - 3062/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108860079_photo_183367681_box1.jpg - 3063/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108860079_photo_183367681_box2.jpg - 3064/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108860132_photo_183367764_box1.jpg - 3065/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108860132_photo_183367764_box2.jpg - 3066/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108860132_photo_183367764_box3.jpg - 3067/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108860132_photo_183367764_box4.jpg - 3068/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_108860132_photo_183367764_box5.jpg - 3069/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10889049_photo_15296926_box1.jpg - 3070/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.62images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10889049_photo_15296926_box2.jpg - 3071/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109162518_photo_183930268_box1.jpg - 3072/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109162518_photo_183930277_box1.jpg - 3073/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109162518_photo_183930287_box1.jpg - 3074/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109162518_photo_183930295_box1.jpg - 3075/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109162520_photo_183930299_box1.jpg - 3076/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109162520_photo_183930299_box2.jpg - 3077/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109173676_photo_183953850_box1.jpg - 3078/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109174758_photo_183955803_box1.jpg - 3079/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109174758_photo_183955810_box1.jpg - 3080/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109174758_photo_183955810_box2.jpg - 3081/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 46.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109191340_photo_183986341_box1.jpg - 3082/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.41images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109191340_photo_183986341_box2.jpg - 3083/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109191340_photo_183986341_box3.jpg - 3084/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109226965_photo_184054028_box1.jpg - 3085/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109226965_photo_184054028_box2.jpg - 3086/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109226965_photo_184054028_box3.jpg - 3087/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109226965_photo_184054028_box4.jpg - 3088/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109226965_photo_184054028_box5.jpg - 3089/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109226965_photo_184054038_box1.jpg - 3090/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109226965_photo_184054038_box2.jpg - 3091/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109226965_photo_184054038_box3.jpg - 3092/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109226965_photo_184054038_box4.jpg - 3093/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109226965_photo_184054038_box5.jpg - 3094/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109287680_photo_184167677_box1.jpg - 3095/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109287680_photo_184167698_box1.jpg - 3096/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.17images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109299805_photo_184303044_box1.jpg - 3097/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109373625_photo_78371861_box1.jpg - 3098/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109373625_photo_78371861_box2.jpg - 3099/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109373625_photo_78371861_box3.jpg - 3100/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109373625_photo_78371861_box4.jpg - 3101/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109373625_photo_78371861_box5.jpg - 3102/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109373625_photo_78371893_box1.jpg - 3103/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109373625_photo_78371893_box2.jpg - 3104/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109373625_photo_78371893_box3.jpg - 3105/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109373625_photo_78371893_box4.jpg - 3106/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109373625_photo_78371893_box5.jpg - 3107/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393659_photo_184353737_box1.jpg - 3108/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393659_photo_184353737_box2.jpg - 3109/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393659_photo_184353737_box3.jpg - 3110/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393659_photo_184353775_box1.jpg - 3111/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393659_photo_184353802_box1.jpg - 3112/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393659_photo_184353802_box2.jpg - 3113/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393659_photo_184354478_box1.jpg - 3114/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393659_photo_184354478_box2.jpg - 3115/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393659_photo_184354478_box3.jpg - 3116/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393659_photo_184354478_box4.jpg - 3117/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.41images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393659_photo_184354478_box5.jpg - 3118/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393659_photo_184354503_box1.jpg - 3119/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393659_photo_184354503_box2.jpg - 3120/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393659_photo_184354503_box3.jpg - 3121/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393659_photo_184354511_box1.jpg - 3122/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393659_photo_184354511_box2.jpg - 3123/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393659_photo_184354511_box3.jpg - 3124/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393659_photo_184354511_box4.jpg - 3125/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393661_photo_184353766_box1.jpg - 3126/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393661_photo_184353766_box2.jpg - 3127/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393661_photo_184353766_box3.jpg - 3128/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393661_photo_184353776_box1.jpg - 3129/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393661_photo_184354449_box1.jpg - 3130/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393661_photo_184354449_box2.jpg - 3131/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 74.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393661_photo_184354449_box3.jpg - 3132/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 74.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393661_photo_184354449_box4.jpg - 3133/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 75.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393661_photo_184354449_box5.jpg - 3134/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109393661_photo_184354490_box1.jpg - 3135/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109439612_photo_184452868_box1.jpg - 3136/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109439612_photo_184452868_box2.jpg - 3137/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109439612_photo_184452868_box3.jpg - 3138/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109439612_photo_184452868_box4.jpg - 3139/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109439612_photo_184452868_box5.jpg - 3140/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109529518_photo_184620623_box1.jpg - 3141/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109529518_photo_184620623_box2.jpg - 3142/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109529518_photo_184620623_box3.jpg - 3143/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109529518_photo_184620623_box4.jpg - 3144/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109529518_photo_184620623_box5.jpg - 3145/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109529518_photo_184620636_box1.jpg - 3146/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109529518_photo_184620636_box2.jpg - 3147/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109529518_photo_184620636_box3.jpg - 3148/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109529518_photo_184620636_box4.jpg - 3149/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109529518_photo_184620636_box5.jpg - 3150/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109529518_photo_184621600_box1.jpg - 3151/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.44images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109529518_photo_184621600_box2.jpg - 3152/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109529518_photo_184621600_box3.jpg - 3153/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109529518_photo_184621600_box4.jpg - 3154/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109529518_photo_184621600_box5.jpg - 3155/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109529519_photo_184620638_box1.jpg - 3156/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109529519_photo_184620638_box2.jpg - 3157/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109529519_photo_184620638_box3.jpg - 3158/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109529519_photo_184620638_box4.jpg - 3159/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109529519_photo_184620638_box5.jpg - 3160/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10960412_photo_15423069_box1.jpg - 3161/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10960412_photo_15423069_box2.jpg - 3162/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.67images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10960412_photo_15423069_box3.jpg - 3163/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.31images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10960412_photo_15423069_box4.jpg - 3164/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 49.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10960412_photo_15423069_box5.jpg - 3165/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10962339_photo_15426580_box1.jpg - 3166/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10962339_photo_15426580_box2.jpg - 3167/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10962339_photo_15426580_box3.jpg - 3168/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10962339_photo_15426580_box4.jpg - 3169/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10962339_photo_15426580_box5.jpg - 3170/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10962339_photo_15426709_box1.jpg - 3171/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10962339_photo_15426844_box1.jpg - 3172/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10962339_photo_15426844_box2.jpg - 3173/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10962339_photo_15426844_box3.jpg - 3174/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10962339_photo_15426844_box4.jpg - 3175/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109707606_photo_184948396_box1.jpg - 3176/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109707606_photo_184948396_box2.jpg - 3177/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109707606_photo_184948396_box3.jpg - 3178/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109707606_photo_184948396_box4.jpg - 3179/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109707606_photo_184948396_box5.jpg - 3180/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109707606_photo_184948406_box1.jpg - 3181/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109707606_photo_184948406_box2.jpg - 3182/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109707606_photo_184948406_box3.jpg - 3183/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10973513_photo_15449139_box1.jpg - 3184/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10973513_photo_15449139_box2.jpg - 3185/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10973513_photo_15449139_box3.jpg - 3186/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10973513_photo_15449139_box4.jpg - 3187/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475731_box1.jpg - 3188/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475731_box2.jpg - 3189/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475731_box3.jpg - 3190/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475731_box4.jpg - 3191/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475731_box5.jpg - 3192/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475732_box1.jpg - 3193/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.22images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475732_box2.jpg - 3194/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475732_box3.jpg - 3195/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475732_box4.jpg - 3196/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475732_box5.jpg - 3197/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475735_box1.jpg - 3198/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475735_box2.jpg - 3199/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475735_box3.jpg - 3200/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 63.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475735_box4.jpg - 3201/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475735_box5.jpg - 3202/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.95images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475738_box1.jpg - 3203/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475738_box2.jpg - 3204/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 63.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475738_box3.jpg - 3205/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475738_box4.jpg - 3206/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475738_box5.jpg - 3207/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475742_box1.jpg - 3208/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475742_box2.jpg - 3209/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475742_box3.jpg - 3210/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475742_box4.jpg - 3211/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475742_box5.jpg - 3212/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475744_box1.jpg - 3213/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475744_box2.jpg - 3214/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475744_box3.jpg - 3215/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.54images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475744_box4.jpg - 3216/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475744_box5.jpg - 3217/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475745_box1.jpg - 3218/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475745_box2.jpg - 3219/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475745_box3.jpg - 3220/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475745_box4.jpg - 3221/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475745_box5.jpg - 3222/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475747_box1.jpg - 3223/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475747_box2.jpg - 3224/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475747_box3.jpg - 3225/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475747_box4.jpg - 3226/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_10986794_photo_15475747_box5.jpg - 3227/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109868064_photo_185250953_box1.jpg - 3228/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109868064_photo_185250953_box2.jpg - 3229/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109868064_photo_185250953_box3.jpg - 3230/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.66images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109868064_photo_185250972_box1.jpg - 3231/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109868064_photo_185250972_box2.jpg - 3232/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109868064_photo_185250972_box3.jpg - 3233/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109868064_photo_185250972_box4.jpg - 3234/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109868064_photo_185250972_box5.jpg - 3235/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109868064_photo_185250999_box1.jpg - 3236/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109868064_photo_185250999_box2.jpg - 3237/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109868064_photo_185250999_box3.jpg - 3238/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.85images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109868064_photo_185250999_box4.jpg - 3239/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109868064_photo_185250999_box5.jpg - 3240/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109870255_photo_185254510_box1.jpg - 3241/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109870255_photo_185254510_box2.jpg - 3242/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109870255_photo_185254510_box3.jpg - 3243/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109931801_photo_185364606_box1.jpg - 3244/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109931801_photo_185364606_box2.jpg - 3245/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109931801_photo_185364612_box1.jpg - 3246/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109931801_photo_185364612_box2.jpg - 3247/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109942332_photo_185388818_box1.jpg - 3248/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109942332_photo_185388818_box2.jpg - 3249/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109942332_photo_185388818_box3.jpg - 3250/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109942332_photo_185388818_box4.jpg - 3251/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109942332_photo_185388818_box5.jpg - 3252/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109942332_photo_185388836_box1.jpg - 3253/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109942332_photo_185388836_box2.jpg - 3254/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109942332_photo_185388836_box3.jpg - 3255/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109942332_photo_185388836_box4.jpg - 3256/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_109942332_photo_185388836_box5.jpg - 3257/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110011908_photo_185514771_box1.jpg - 3258/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.49images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110011908_photo_185514771_box2.jpg - 3259/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110011908_photo_185514771_box3.jpg - 3260/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110011908_photo_185514784_box1.jpg - 3261/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110011908_photo_185514784_box2.jpg - 3262/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110011908_photo_185514784_box3.jpg - 3263/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110011909_photo_185514771_box1.jpg - 3264/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.80images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110011909_photo_185514771_box2.jpg - 3265/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110011909_photo_185514771_box3.jpg - 3266/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.07images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110011909_photo_185514771_box4.jpg - 3267/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110011909_photo_185514771_box5.jpg - 3268/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110011909_photo_185514784_box1.jpg - 3269/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110011909_photo_185514784_box2.jpg - 3270/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.65images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110011909_photo_185514784_box3.jpg - 3271/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110011909_photo_185514784_box4.jpg - 3272/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110011909_photo_185514784_box5.jpg - 3273/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110019898_photo_185526656_box1.jpg - 3274/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110019898_photo_185527452_box1.jpg - 3275/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110019898_photo_185527452_box2.jpg - 3276/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110019898_photo_185527452_box3.jpg - 3277/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110019898_photo_185527457_box1.jpg - 3278/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110019898_photo_185527457_box2.jpg - 3279/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110019900_photo_185527728_box1.jpg - 3280/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.04images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523835_box1.jpg - 3281/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523835_box2.jpg - 3282/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523835_box3.jpg - 3283/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523835_box4.jpg - 3284/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523835_box5.jpg - 3285/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523872_box1.jpg - 3286/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.16images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523872_box2.jpg - 3287/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523872_box3.jpg - 3288/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523872_box4.jpg - 3289/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.73images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523872_box5.jpg - 3290/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.72images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523882_box1.jpg - 3291/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523882_box2.jpg - 3292/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523882_box3.jpg - 3293/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523882_box4.jpg - 3294/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523882_box5.jpg - 3295/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523912_box1.jpg - 3296/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523912_box2.jpg - 3297/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523912_box3.jpg - 3298/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523912_box4.jpg - 3299/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523912_box5.jpg - 3300/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523992_box1.jpg - 3301/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523992_box2.jpg - 3302/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523992_box3.jpg - 3303/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.27images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523992_box4.jpg - 3304/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022128_photo_185523992_box5.jpg - 3305/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 49.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524544_box1.jpg - 3306/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 49.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524544_box2.jpg - 3307/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524544_box3.jpg - 3308/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.94images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524544_box4.jpg - 3309/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524544_box5.jpg - 3310/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524557_box1.jpg - 3311/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524557_box2.jpg - 3312/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524557_box3.jpg - 3313/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.36images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524566_box1.jpg - 3314/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524566_box2.jpg - 3315/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524566_box3.jpg - 3316/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 51.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524566_box4.jpg - 3317/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524566_box5.jpg - 3318/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.34images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524618_box1.jpg - 3319/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.51images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524618_box2.jpg - 3320/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524618_box3.jpg - 3321/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 30.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524618_box4.jpg - 3322/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524618_box5.jpg - 3323/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524620_box1.jpg - 3324/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524620_box2.jpg - 3325/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.55images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524627_box1.jpg - 3326/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524627_box2.jpg - 3327/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524627_box3.jpg - 3328/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524627_box4.jpg - 3329/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.31images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524627_box5.jpg - 3330/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524735_box1.jpg - 3331/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524735_box2.jpg - 3332/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524735_box3.jpg - 3333/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524735_box4.jpg - 3334/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022141_photo_185524735_box5.jpg - 3335/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022179_photo_185526339_box1.jpg - 3336/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022179_photo_185526339_box2.jpg - 3337/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022181_photo_185526347_box1.jpg - 3338/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022181_photo_185526347_box2.jpg - 3339/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.59images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022181_photo_185526352_box1.jpg - 3340/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022182_photo_185526389_box1.jpg - 3341/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022182_photo_185526425_box1.jpg - 3342/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.75images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022182_photo_185526427_box1.jpg - 3343/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022185_photo_185526559_box1.jpg - 3344/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022185_photo_185526559_box2.jpg - 3345/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022185_photo_185526559_box3.jpg - 3346/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.48images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022185_photo_185526579_box1.jpg - 3347/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022185_photo_185526579_box2.jpg - 3348/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.76images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022185_photo_185526579_box3.jpg - 3349/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.58images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022185_photo_185526579_box4.jpg - 3350/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022185_photo_185526579_box5.jpg - 3351/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.97images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022187_photo_185526557_box1.jpg - 3352/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.43images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022187_photo_185526557_box2.jpg - 3353/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022187_photo_185526599_box1.jpg - 3354/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022187_photo_185526599_box2.jpg - 3355/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.78images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022187_photo_185526599_box3.jpg - 3356/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022187_photo_185526623_box1.jpg - 3357/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.33images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022187_photo_185526635_box1.jpg - 3358/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.87images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022187_photo_185526649_box1.jpg - 3359/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022187_photo_185526678_box1.jpg - 3360/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022187_photo_185526678_box2.jpg - 3361/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.91images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022187_photo_185526678_box3.jpg - 3362/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022187_photo_185526678_box4.jpg - 3363/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.70images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022187_photo_185526686_box1.jpg - 3364/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022187_photo_185526686_box2.jpg - 3365/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022187_photo_185526689_box1.jpg - 3366/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.47images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022187_photo_185526689_box2.jpg - 3367/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022188_photo_185526738_box1.jpg - 3368/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.61images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022188_photo_185526738_box2.jpg - 3369/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 34.50images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022188_photo_185526738_box3.jpg - 3370/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.45images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022188_photo_185526738_box4.jpg - 3371/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.01images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022188_photo_185526756_box1.jpg - 3372/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.38images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022188_photo_185526756_box2.jpg - 3373/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.11images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022188_photo_185526756_box3.jpg - 3374/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.95images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022188_photo_185526756_box4.jpg - 3375/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.19images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022188_photo_185526756_box5.jpg - 3376/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022194_photo_185526989_box1.jpg - 3377/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022194_photo_185526989_box2.jpg - 3378/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022194_photo_185526989_box3.jpg - 3379/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022194_photo_185527187_box1.jpg - 3380/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022194_photo_185527187_box2.jpg - 3381/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022194_photo_185527187_box3.jpg - 3382/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.14images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022194_photo_185527187_box4.jpg - 3383/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022194_photo_185527187_box5.jpg - 3384/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022194_photo_185527221_box1.jpg - 3385/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.69images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022194_photo_185527221_box2.jpg - 3386/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022194_photo_185527472_box1.jpg - 3387/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022194_photo_185527472_box2.jpg - 3388/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.12images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022194_photo_185527472_box3.jpg - 3389/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.20images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022194_photo_185527472_box4.jpg - 3390/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.09images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022194_photo_185527523_box1.jpg - 3391/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.71images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022194_photo_185527523_box2.jpg - 3392/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022194_photo_185527523_box3.jpg - 3393/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022194_photo_185527523_box4.jpg - 3394/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.26images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022197_photo_185527110_box1.jpg - 3395/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022197_photo_185527110_box2.jpg - 3396/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.05images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022197_photo_185527110_box3.jpg - 3397/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.29images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022197_photo_185527110_box4.jpg - 3398/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022197_photo_185527110_box5.jpg - 3399/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.90images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022197_photo_185527394_box1.jpg - 3400/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022197_photo_185527394_box2.jpg - 3401/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.00images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022197_photo_185527394_box3.jpg - 3402/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.32images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022197_photo_185527394_box4.jpg - 3403/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.99images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022197_photo_185527394_box5.jpg - 3404/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.96images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022197_photo_185527608_box1.jpg - 3405/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022197_photo_185527608_box2.jpg - 3406/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.30images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022197_photo_185527608_box3.jpg - 3407/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.93images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022197_photo_185527608_box4.jpg - 3408/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.53images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022197_photo_185527608_box5.jpg - 3409/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022198_photo_185527196_box1.jpg - 3410/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022198_photo_185527196_box2.jpg - 3411/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022198_photo_185527196_box3.jpg - 3412/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 46.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022198_photo_185527196_box4.jpg - 3413/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.83images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022198_photo_185527196_box5.jpg - 3414/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022198_photo_185527354_box1.jpg - 3415/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.74images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022198_photo_185527354_box2.jpg - 3416/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.64images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022198_photo_185527354_box3.jpg - 3417/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022198_photo_185527354_box4.jpg - 3418/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.08images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022198_photo_185527354_box5.jpg - 3419/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.23images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022198_photo_185527372_box1.jpg - 3420/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.86images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022198_photo_185527372_box2.jpg - 3421/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022198_photo_185527372_box3.jpg - 3422/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 37.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022198_photo_185527372_box4.jpg - 3423/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.39images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022198_photo_185527372_box5.jpg - 3424/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022198_photo_185527551_box1.jpg - 3425/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.57images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022198_photo_185527551_box2.jpg - 3426/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.52images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022198_photo_185527551_box3.jpg - 3427/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022198_photo_185527551_box4.jpg - 3428/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.95images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110022198_photo_185527551_box5.jpg - 3429/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.18images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110034694_photo_185556346_box1.jpg - 3430/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110034694_photo_185556346_box2.jpg - 3431/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.40images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110034694_photo_185556346_box3.jpg - 3432/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.28images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110034694_photo_185556346_box4.jpg - 3433/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.03images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110034694_photo_185556364_box1.jpg - 3434/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.13images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110034694_photo_185556364_box2.jpg - 3435/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.92images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110060807_photo_185603169_box1.jpg - 3436/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110060807_photo_185603169_box2.jpg - 3437/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.81images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110060807_photo_185603169_box3.jpg - 3438/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110060807_photo_185603169_box4.jpg - 3439/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110060807_photo_185603169_box5.jpg - 3440/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.35images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110061105_photo_185605398_box1.jpg - 3441/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.77images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110061105_photo_185605398_box2.jpg - 3442/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.89images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110061105_photo_185605398_box3.jpg - 3443/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 61.98images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110061105_photo_185605398_box4.jpg - 3444/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.10images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110061105_photo_185605398_box5.jpg - 3445/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.24images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110061105_photo_185605415_box1.jpg - 3446/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.63images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110061105_photo_185605415_box2.jpg - 3447/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.56images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110061105_photo_185605415_box3.jpg - 3448/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.79images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110061105_photo_185605415_box4.jpg - 3449/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.68images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110061105_photo_185605415_box5.jpg - 3450/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.84images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110061275_photo_185605762_box1.jpg - 3451/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.46images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110061275_photo_185605762_box2.jpg - 3452/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 67.25images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110061275_photo_185605762_box3.jpg - 3453/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110061275_photo_185605762_box4.jpg - 3454/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 40.02images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110061275_photo_185605780_box1.jpg - 3455/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.88images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110061275_photo_185605780_box2.jpg - 3456/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.15images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110061275_photo_185605780_box3.jpg - 3457/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.06images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110061275_photo_185605780_box4.jpg - 3458/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.37images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110061275_photo_185605780_box5.jpg - 3459/74746

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.21images/s]

✅ Processed /rs1/researchers/a/amallav/results/outputs_crop/obs_110162051_photo_185792696_box1.jpg - 3460/74746

  0%|                                                                                                                              | 0/1 [00:00<?, ?images/s]

KeyboardInterrupt:

In [9]:
pred_df = pd.read_csv(output_csv)
pred_df

,file_name,kingdom,phylum,class,order,family,genus,species_epithet,species,common_name,score,path,id
0,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Arthropoda,Insecta,Lepidoptera,Erebidae,Cerocala,contraria,Cerocala contraria,NaN,0.178396,/rs1/researchers/a/amallav/results/outputs_cro...,0
1,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Arthropoda,Insecta,Lepidoptera,Erebidae,Chrysorithrum,flavomaculata,Chrysorithrum flavomaculata,NaN,0.134323,/rs1/researchers/a/amallav/results/outputs_cro...,0
2,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Arthropoda,Insecta,Lepidoptera,Erebidae,Ulotrichopus,marmoratus,Ulotrichopus marmoratus,NaN,0.066452,/rs1/researchers/a/amallav/results/outputs_cro...,0
3,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Arthropoda,Insecta,Lepidoptera,Erebidae,Eudocima,divitiosa,Eudocima divitiosa,NaN,0.058108,/rs1/researchers/a/amallav/results/outputs_cro...,0
4,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Arthropoda,Insecta,Lepidoptera,Erebidae,Eudocima,colubra,Eudocima colubra,NaN,0.032328,/rs1/researchers/a/amallav/results/outputs_cro...,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
373725,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Chordata,Aves,Musophagiformes,Musophagidae,Tauraco,porphyreolophus,Tauraco porphyreolophus,Purple-crested Turaco,0.921519,/rs1/researchers/a/amallav/results/outputs_cro...,74745
373726,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Chordata,Aves,Musophagiformes,Musophagidae,Tauraco,hartlaubi,Tauraco hartlaubi,Hartlaub's Turaco,0.019476,/rs1/researchers/a/amallav/results/outputs_cro...,74745
373727,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Chordata,Aves,Musophagiformes,Musophagidae,Tauraco,erythrolophus,Tauraco erythrolophus,Red-crested Turaco,0.007151,/rs1/researchers/a/amallav/results/outputs_cro...,74745
373728,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Chordata,Aves,Musophagiformes,Musophagidae,Tauraco,fischeri,Tauraco fischeri,Fischer's turaco,0.005640,/rs1/researchers/a/amallav/results/outputs_cro...,74745
373729,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Chordata,Aves,Musophagiformes,Musophagidae,Tauraco,corythaix,Tauraco corythaix,Knysna turaco,0.004253,/rs1/researchers/a/amallav/results/outputs_cro...,74745

# Convert top-k predictions into one row per cropped image

In [10]:
assert "file_name" in pred_df.columns, "Expected 'file_name' in prediction output"
assert "score" in pred_df.columns, "Expected 'score' in prediction output"
assert "species" in pred_df.columns, "Expected 'species' in prediction output"

In [15]:
# pred_df

,file_name,kingdom,phylum,class,order,family,genus,species_epithet,species,common_name,score
0,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Echinodermata,Asteroidea,Valvatida,Odontasteridae,Odontaster,penicillatus,Odontaster penicillatus,,0.060668
1,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Echinodermata,Asteroidea,Valvatida,Goniasteridae,Ceramaster,japonicus,Ceramaster japonicus,Bat star,0.060482
2,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Echinodermata,Asteroidea,Valvatida,Goniasteridae,Stellaster,princeps,Stellaster princeps,,0.055059
3,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Echinodermata,Asteroidea,Valvatida,Asteropseidae,Dermasterias,imbricata,Dermasterias imbricata,,0.044492
4,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Echinodermata,Asteroidea,Paxillosida,Astropectinidae,Dipsacaster,pretiosus,Dipsacaster pretiosus,,0.042861
...,...,...,...,...,...,...,...,...,...,...,...
1585,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Chordata,Aves,Anseriformes,Anatidae,Bucephala,albeola,Bucephala albeola,Bufflehead,0.786600
1586,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Chordata,,Siluriformes,Ictaluridae,Ameiurus,nebulosus,Ameiurus nebulosus,Brown bullhead,0.006554
1587,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Chordata,,Siluriformes,Ictaluridae,Ameiurus,catus,Ameiurus catus,White catfish,0.005098
1588,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Chordata,,Anguilliformes,Anguillidae,Anguilla,rostrata,Anguilla rostrata,American eel,0.004807
1589,/rs1/researchers/a/amallav/results/outputs_cro...,Animalia,Chordata,,Clupeiformes,Clupeidae,Dorosoma,cepedianum,Dorosoma cepedianum,Gizzard shad,0.004745

In [17]:
summary_rows = []

for crop_path, group in pred_df.groupby("file_name", sort=False):
    group = group.sort_values("score", ascending=False).reset_index(drop=True) #This ensures highest-scoring prediction comes first.
    top1 = group.iloc[0]
    top2 = group.iloc[1]
    top3 = group.iloc[2]
    top4 = group.iloc[3]
    top5 = group.iloc[4]

    topk_records = group[["species", "common_name", "score"]].to_dict(orient="records") #keeps all top-k predictions, but only the most useful columns

    #summary row: one final record per crop, best prediction at top level and top-k stored as JSON
    row = {
        "crop_file_path": crop_path,
        "top1_species": top1.get("species"),
        "top2_species": top2.get("species"),
        "top3_species": top3.get("species"),
        "top4_species": top4.get("species"),
        "top5_species": top5.get("species"),
        "top1_common_name": top1.get("common_name"),
        "top1_score": top1.get("score"),
        "topk_predictions_json": json.dumps(topk_records, ensure_ascii=False),
    }
    summary_rows.append(row)

summary_df = pd.DataFrame(summary_rows)

final_df = crop_df.merge(summary_df, on="crop_file_path", how="left") #why left? keeps all crops from crop_df, even if somehow a prediction row is missing.

# final_df["low_confidence_flag"] = final_df["top1_score"] < 0.20

print("Final rows:", len(final_df))
final_df.head()

Final rows: 74746

,crop_file,crop_file_path,image_id,box_num,top1_species,top2_species,top3_species,top4_species,top5_species,top1_common_name,top1_score,topk_predictions_json
0,obs_10003229_photo_114145431_box1.jpg,/rs1/researchers/a/amallav/results/outputs_cro...,obs_10003229_photo_114145431,1,Cerocala contraria,Chrysorithrum flavomaculata,Ulotrichopus marmoratus,Eudocima divitiosa,Eudocima colubra,NaN,0.178396,"[{""species"": ""Cerocala contraria"", ""common_nam..."
1,obs_10003229_photo_114145431_box2.jpg,/rs1/researchers/a/amallav/results/outputs_cro...,obs_10003229_photo_114145431,2,Eudocima divitiosa,Eudocima colubra,Cerocala contraria,Eudocima jordani,Eudocima imperator,NaN,0.375307,"[{""species"": ""Eudocima divitiosa"", ""common_nam..."
2,obs_10003229_photo_114145431_box3.jpg,/rs1/researchers/a/amallav/results/outputs_cro...,obs_10003229_photo_114145431,3,Eudocima divitiosa,Eudocima jordani,Eudocima imperator,Eudocima colubra,Cerocala contraria,NaN,0.376554,"[{""species"": ""Eudocima divitiosa"", ""common_nam..."
3,obs_10003229_photo_114145431_box4.jpg,/rs1/researchers/a/amallav/results/outputs_cro...,obs_10003229_photo_114145431,4,Eudocima divitiosa,Cerocala contraria,Chrysorithrum flavomaculata,Eudocima colubra,Megistoclisma ribbei,NaN,0.316769,"[{""species"": ""Eudocima divitiosa"", ""common_nam..."
4,obs_10003229_photo_114145431_box5.jpg,/rs1/researchers/a/amallav/results/outputs_cro...,obs_10003229_photo_114145431,5,Eudocima divitiosa,Eudocima imperator,Ulotrichopus marmoratus,Chrysorithrum flavomaculata,Eudocima colubra,NaN,0.284782,"[{""species"": ""Eudocima divitiosa"", ""common_nam..."

In [ ]:
summary_rows = []

for crop_path, group in pred_df.groupby("file_name", sort=False):
    group = group.sort_values("score", ascending=False).reset_index(drop=True) #This ensures highest-scoring prediction comes first.
    top1 = group.iloc[0]
    top2 = group.iloc[1]
    top3 = group.iloc[2]
    top4 = group.iloc[3]
    top5 = group.iloc[4]

    topk_records = group[["species", "common_name", "score"]].to_dict(orient="records") #keeps all top-k predictions, but only the most useful columns

    #summary row: one final record per crop, best prediction at top level and top-k stored as JSON
    for i in range(5):
        no=i+1
        no=str(no)
        val="top"+no+"_species"
        sc="top"+no+"_score"
        cc="top"+no+"_common_name"
        row = {
            "crop_file_path": crop_path,
            # val:group.iloc[i].get("species"),
            "species": group.iloc[i].get("species"),
            # "top2_species": top2.get("species"),
            # "top3_species": top3.get("species"),
            # "top4_species": top4.get("species"),
            # "top5_species": top5.get("species"),
            "common_name": group.iloc[i].get("common_name"),
            "kingdom": group.iloc[i].get("kingdom"),
            "phylum": group.iloc[i].get("phylum"),
            "class": group.iloc[i].get("class"),
            "order": group.iloc[i].get("order"),
            "family": group.iloc[i].get("family"),
            "genus": group.iloc[i].get("genus"),
            "score": group.iloc[i].get("score"),
            "top_no":no,
            "topk_predictions_json": json.dumps(topk_records, ensure_ascii=False),
        }
        summary_rows.append(row)

summary_df = pd.DataFrame(summary_rows)

full_df = crop_df.merge(summary_df, on="crop_file_path", how="left") #why left? keeps all crops from crop_df, even if somehow a prediction row is missing.

# final_df["low_confidence_flag"] = final_df["top1_score"] < 0.20

print("Final rows:", len(full_df))
full_df.head()

# Save final output CSV

In [ ]:
OUT_CSV = OUTPUTS_BCCP_DIR / "bioclip_species_predictions.csv"
final_df.to_csv(OUT_CSV, index=False)
print("Saved:", OUT_CSV)

Saved: /rs1/researchers/a/amallav/results/outputs_bioclip_crop/bioclip_species_predictions_2.csv

In [ ]:
OUT_CSV = OUTPUTS_BCCP_DIR / "results_crop.csv"
full_df.to_csv(OUT_CSV, index=False)
print("Saved:", OUT_CSV)

Saved: /rs1/researchers/a/amallav/results/outputs_bioclip_crop/results_crop_2.csv