# Importing Libraries and Setup

In [22]:
import os

os.environ["HF_HOME"] = f"/rs1/researchers/a/amallav/models/hf_home"

os.environ["HF_HUB_CACHE"] = os.path.join(os.environ["HF_HOME"], "hub")
os.environ["HF_HUB_OFFLINE"] = "1"   # only after cache is populated

In [23]:
import json #Used later to store the top-k predictions as a JSON string in the final CSV
from pathlib import Path
import pandas as pd
import torch
from bioclip import TreeOfLifeClassifier, Rank #TreeOfLifeClassifier = the classifier that predicts biological taxa; Rank = tells the classifier what taxonomic level you want

In [24]:
# os.environ["PROJECT_DIR"] = "/rs1/researchers/a/amallav/"
# print(os.environ["PROJECT_DIR"])
# os.environ["OUTPUTS_DIR"] = "/rs1/researchers/a/amallav/results"
# print(os.environ["OUTPUTS_DIR"])
# os.environ["OUTPUTS_CP_DIR"] = "/rs1/researchers/a/amallav/results/outputs_crop"
# print(os.environ["OUTPUTS_CP_DIR"])
# os.environ["OUTPUTS_BCCP_DIR"] = "/rs1/researchers/a/amallav/results/outputs_bioclip_crop"
# print(os.environ["OUTPUTS_BCCP_DIR"])
# df = pd.read_csv("/rs1/researchers/a/amallav/results/outputs_crop/cropped_metadata.csv")
# # df["crop_file_path"][0]
# p = Path("/rs1/researchers/a/amallav/image_dataset/obs_341194952_photo_621071156.jpg")
# p.exists()

In [25]:
PROJECT_DIR = Path(os.environ.get("PROJECT_DIR", "/rs1/researchers/a/amallav/")).resolve()
OUTPUTS_DIR=Path(os.environ.get("OUTPUTS_DIR", "/rs1/researchers/a/amallav/results")).resolve()
IMAGE_DATASET_DIR = Path(os.getenv("IMAGE_DATASET_DIR", "/rs1/researchers/a/amallav/image_dataset")).resolve()

# OUTPUTS_CP_DIR = Path(os.environ.get("OUTPUTS_CP_DIR", OUTPUTS_DIR / "outputs_crop")).resolve()

OUTPUTS_BC_DIR = Path(os.environ.get("OUTPUTS_BC_DIR", OUTPUTS_DIR / "outputs_bioclip")).resolve()
OUTPUTS_BC_DIR.mkdir(parents=True, exist_ok=True)

# CROP_OUT = PROJECT_DIR / "outputs_crop"
META_CSV = OUTPUTS_DIR / "baseline_metadata.csv" #This is the metadata file that tells us what crop files exist.
OUT_CSV = OUTPUTS_BC_DIR / "bioclip_species_predictions.csv"
output_csv = OUTPUTS_BC_DIR / "predictions.csv"

print("PROJECT_DIR:", PROJECT_DIR)
print("OUTPUTS_DIR:", OUTPUTS_DIR, "| exists:", OUTPUTS_DIR.exists())
print("IMAGE_DATASET_DIR:", IMAGE_DATASET_DIR, "| exists:", IMAGE_DATASET_DIR.exists())
# print("OUTPUTS_CP_DIR:", OUTPUTS_CP_DIR, "| exists:", OUTPUTS_CP_DIR.exists())
print("OUTPUTS_BC_DIR:", OUTPUTS_BC_DIR, "| exists:", OUTPUTS_BC_DIR.exists())
print("META_CSV    :", META_CSV, "| exists:", META_CSV.exists())
print("OUT_CSV     :", OUT_CSV, "| exists:", OUT_CSV.exists())
print("output_csv     :", output_csv, "| exists:", output_csv.exists())

PROJECT_DIR: /rs1/researchers/a/amallav
OUTPUTS_DIR: /rs1/researchers/a/amallav/results | exists: True
IMAGE_DATASET_DIR: /rs1/researchers/a/amallav/image_dataset | exists: True
OUTPUTS_BC_DIR: /rs1/researchers/a/amallav/results/outputs_bioclip | exists: True
META_CSV    : /rs1/researchers/a/amallav/results/baseline_metadata.csv | exists: True
OUT_CSV     : /rs1/researchers/a/amallav/results/outputs_bioclip/bioclip_species_predictions.csv | exists: False
output_csv     : /rs1/researchers/a/amallav/results/outputs_bioclip/predictions.csv | exists: False

# Load Bioclip

In [26]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [27]:
# model_dir = "/share/ftrscape/{}/models/bioclip".format(__import__("os").environ["USER"])

In [28]:
MODEL_STR = "hf-hub:imageomics/bioclip-2"

TOP_K = 5 #top 5 species predictions for each image
BATCH_SIZE = 1 #This controls how many cropped images are processed at once. Might have to tune this parameter

classifier = TreeOfLifeClassifier(
    device=device,
    model_str=MODEL_STR,
)

print("Device   :", device)
print("Model    :", MODEL_STR)
print("Top-k    :", TOP_K)
print("Batch size:", BATCH_SIZE)

Device   : cuda
Model    : hf-hub:imageomics/bioclip-2
Top-k    : 5
Batch size: 1

# Load CSV

In [36]:
assert META_CSV.exists(), f"metadata.csv not found: {META_CSV}"

meta = pd.read_csv(META_CSV)
# meta
required_cols = {"image_path", "image_id"}
missing_cols = required_cols - set(meta.columns)
assert not missing_cols, f"metadata.csv is missing columns: {missing_cols}"

In [35]:
# meta

,image_id,image_path
0,obs_341194952_photo_621071156,/rs1/researchers/a/amallav/image_dataset/obs_3...
1,obs_341194952_photo_621071168,/rs1/researchers/a/amallav/image_dataset/obs_3...
2,obs_341194952_photo_621071177,/rs1/researchers/a/amallav/image_dataset/obs_3...
3,obs_341194952_photo_621071190,/rs1/researchers/a/amallav/image_dataset/obs_3...
4,obs_341194952_photo_621071213,/rs1/researchers/a/amallav/image_dataset/obs_3...
...,...,...
24802,obs_414645_photo_28352912,/rs1/researchers/a/amallav/image_dataset/obs_4...
24803,obs_338604_photo_421440,/rs1/researchers/a/amallav/image_dataset/obs_3...
24804,obs_338604_photo_421441,/rs1/researchers/a/amallav/image_dataset/obs_3...
24805,obs_338604_photo_421442,/rs1/researchers/a/amallav/image_dataset/obs_3...
24806,obs_338604_photo_421443,/rs1/researchers/a/amallav/image_dataset/obs_3...

In [37]:
# #converts paths into absolute paths.
# def resolve_path(p):
#     if pd.isna(p):
#         return None
#     p = str(p).strip()
#     if os.path.isabs(p):
#         return p
#     return str((PROJECT_DIR / p).resolve())

# meta["masked_crop_path"] = meta["masked_crop_path"].apply(resolve_path)

In [38]:
meta = meta[meta["image_path"].notna()].copy() #remove rows where crop path is missing
meta["crop_exists"] = meta["image_path"].apply(os.path.exists)

missing_count = (~meta["crop_exists"]).sum()
if missing_count > 0:
    print(f"Skipping {missing_count} rows because crop file does not exist.")

meta = meta[meta["crop_exists"]].copy()  #only rows where the crop file actually exists.

In [39]:
keep_cols = ["image_path", "image_id"]
if "box_num" in meta.columns:
    keep_cols.append("box_num")

org_df = meta[keep_cols].drop_duplicates(subset=["image_path"]).reset_index(drop=True) #creates a clean crop table without deduplicates

print("Total valid images:", len(org_df))
org_df.head()

Total valid images: 24807

,image_path,image_id
0,/rs1/researchers/a/amallav/image_dataset/obs_3...,obs_341194952_photo_621071156
1,/rs1/researchers/a/amallav/image_dataset/obs_3...,obs_341194952_photo_621071168
2,/rs1/researchers/a/amallav/image_dataset/obs_3...,obs_341194952_photo_621071177
3,/rs1/researchers/a/amallav/image_dataset/obs_3...,obs_341194952_photo_621071190
4,/rs1/researchers/a/amallav/image_dataset/obs_3...,obs_341194952_photo_621071213

# Run species classification on all cropped images

In [40]:
# test = classifier.predict(
#     images="/gpfs_common/share03/ftrscape/snair3/wew_notebooks/outputs_crop/obs_250956763_photo_448935283_box2_copy.JPG",
#     rank=Rank.SPECIES, #Predict at species level.
#     k=TOP_K, #Return the top 5 predictions for each image.
#     batch_size=BATCH_SIZE, #Process 1 image at a time.
# )
# test_df=pd.DataFrame(test)

# # print("Total prediction rows:", len(pred_df))
# test_df.head()

In [41]:
# crop_paths = crop_df["crop_file_path"].tolist() #Collect all crop image paths into a list.

# predictions = classifier.predict(
#     images=crop_paths, #Pass the cropped image files to the model.
#     rank=Rank.SPECIES, #Predict at species level.
#     k=TOP_K, #Return the top 5 predictions for each image.
#     batch_size=BATCH_SIZE, #Process 1 image at a time.
# )

# pred_df = pd.DataFrame(predictions) #Turns the prediction output into a table.

# print("Total prediction rows:", len(pred_df))
# pred_df.head()

In [ ]:



# Create CSV with header only once

if not os.path.exists(output_csv):
    empty_df = pd.DataFrame(columns=[
        "file_name",
        "kingdom",
        "phylum",
        "class",
        "order",
        "family",
        "genus",
        "species_epithet",
        "species",
        "common_name",
        "score",
        "path",
        "id"
    ])
    empty_df.to_csv(output_csv, index=False)


for idx, row in org_df.iterrows():
    image_path = row["image_path"]

    # Run prediction for ONE image
    prediction = classifier.predict(
        images=[image_path],           # single image
        rank=Rank.SPECIES,
        k=TOP_K,
        batch_size=1
    )

    # Convert to DataFrame
    pred_df = pd.DataFrame(prediction)

    # (Optional) keep track of source image
    pred_df["image_path"] = image_path
    pred_df["image_index"] = idx

    # Append to CSV (no header after first time)
    pred_df.to_csv(
        output_csv,
        mode="a",
        header=not os.path.getsize(output_csv),
        index=False
    )

    print(f"✅ Processed {image_path} - {idx + 1}/{len(org_df)}")

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.59images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_341194952_photo_621071156.jpg - 1/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.04images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_341194952_photo_621071168.jpg - 2/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.80images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_341194952_photo_621071177.jpg - 3/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.45images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_341194952_photo_621071190.jpg - 4/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.95images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_341194952_photo_621071213.jpg - 5/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.84images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_341067936_photo_620805844.jpg - 6/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.37images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_341067936_photo_620805858.jpg - 7/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.54images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_341067936_photo_620805991.jpg - 8/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.94images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_341060278_photo_547585371.jpg - 9/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.98images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_341060278_photo_547585422.jpg - 10/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.09images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_341060278_photo_547585471.jpg - 11/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.29images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_341060248_photo_547586114.jpg - 12/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.03images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_341011035_photo_620687628.jpg - 13/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.04images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_341011035_photo_620687643.jpg - 14/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.86images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_341011035_photo_620687668.jpg - 15/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.11images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_341011035_photo_620687694.jpg - 16/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.00images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_341011035_photo_620688018.jpg - 17/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.68images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_341011035_photo_620688038.jpg - 18/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.51images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340891948_photo_620443274.jpg - 19/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.71images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340848746_photo_620355031.jpg - 20/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.53images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340848514_photo_620354575.jpg - 21/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.14images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340848514_photo_620354582.jpg - 22/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.08images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340848497_photo_620354560.jpg - 23/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.32images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340825934_photo_620308797.jpg - 24/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.86images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340825934_photo_620308839.jpg - 25/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.63images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340722577_photo_620095837.jpg - 26/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.48images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340722576_photo_620095839.jpg - 27/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.50images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340542613_photo_619737737.jpg - 28/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.14images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340542613_photo_619737740.jpg - 29/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.49images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340542613_photo_619737753.jpg - 30/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.06images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340542613_photo_619737767.jpg - 31/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.98images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340542613_photo_619737775.jpg - 32/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.45images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340542613_photo_619737804.jpg - 33/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.14images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340542613_photo_619737829.jpg - 34/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.50images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340514310_photo_619679014.jpg - 35/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.96images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340514310_photo_619679035.jpg - 36/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.34images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340514310_photo_619679050.jpg - 37/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.48images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340514309_photo_619678757.jpg - 38/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.54images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340514309_photo_619678812.jpg - 39/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.62images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340514309_photo_619678833.jpg - 40/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.95images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340514309_photo_619678863.jpg - 41/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.75images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340514309_photo_619678889.jpg - 42/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.03images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340514309_photo_619678934.jpg - 43/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.44images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340433312_photo_619519266.jpg - 44/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.41images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340394115_photo_619968851.jpg - 45/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.47images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340368188_photo_619383348.jpg - 46/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.20images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340368188_photo_619383374.jpg - 47/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.73images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340364592_photo_619375042.jpg - 48/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.88images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340337865_photo_533753896.jpg - 49/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.18images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340337865_photo_533753923.jpg - 50/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.27images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340337865_photo_533753939.jpg - 51/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.66images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340337296_photo_536341964.jpg - 52/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.27images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340326194_photo_619295158.jpg - 53/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.47images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340326194_photo_619295139.jpg - 54/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.52images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340326194_photo_619295155.jpg - 55/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.77images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340326193_photo_619295159.jpg - 56/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.62images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340304697_photo_619256274.jpg - 57/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.08images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340304697_photo_619256243.jpg - 58/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.63images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340304697_photo_619256316.jpg - 59/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.84images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340271239_photo_619190263.jpg - 60/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.32images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340271239_photo_619190267.jpg - 61/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.40images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340271239_photo_619190268.jpg - 62/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.26images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340271239_photo_619190266.jpg - 63/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.00images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340271239_photo_619190273.jpg - 64/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.99images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340271186_photo_619190124.jpg - 65/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.76images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340271186_photo_619190122.jpg - 66/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.63images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340263466_photo_619175705.jpg - 67/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.51images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340263466_photo_619175707.jpg - 68/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.01images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340263466_photo_619175708.jpg - 69/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.05images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340261882_photo_619172320.jpg - 70/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.56images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340261882_photo_619172337.jpg - 71/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.42images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340261882_photo_619172349.jpg - 72/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.66images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340261882_photo_619172367.jpg - 73/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.34images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340261882_photo_619172382.jpg - 74/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.11images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340201729_photo_619048233.jpg - 75/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.87images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340201729_photo_619048235.jpg - 76/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.04images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340201729_photo_619048220.jpg - 77/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.44images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340201729_photo_619048218.jpg - 78/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.05images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340201729_photo_619048219.jpg - 79/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.04images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340178684_photo_619000728.jpg - 80/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.91images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340152977_photo_618950018.jpg - 81/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.84images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340152977_photo_618950022.jpg - 82/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.45images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340152977_photo_618950027.jpg - 83/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.34images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340152977_photo_618950016.jpg - 84/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.82images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340152756_photo_618949474.jpg - 85/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.45images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340152756_photo_618949476.jpg - 86/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.90images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340152756_photo_618949477.jpg - 87/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.18images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340152756_photo_618949482.jpg - 88/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.67images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340152756_photo_618949483.jpg - 89/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.16images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340147022_photo_618936132.jpg - 90/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.74images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340147022_photo_618936053.jpg - 91/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.96images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340147007_photo_618932618.jpg - 92/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.38images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340147007_photo_618932719.jpg - 93/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.79images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340147007_photo_618935941.jpg - 94/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.63images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340122341_photo_618887905.jpg - 95/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.22images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340115097_photo_618869552.jpg - 96/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.13images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340115097_photo_618869568.jpg - 97/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.37images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340115097_photo_618869590.jpg - 98/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.28images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340115097_photo_618869666.jpg - 99/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.39images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340114984_photo_618869552.jpg - 100/24807

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.81images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340114984_photo_618869568.jpg - 101/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.42images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340114984_photo_618869590.jpg - 102/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.33images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340114984_photo_618869666.jpg - 103/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.62images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340042963_photo_362323490.jpg - 104/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.78images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340035665_photo_618703136.jpg - 105/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.96images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340035665_photo_618703149.jpg - 106/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.33images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340035665_photo_618721897.jpg - 107/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.47images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340035133_photo_618702374.jpg - 108/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.60images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340035133_photo_618703442.jpg - 109/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.12images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340035133_photo_618703451.jpg - 110/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.12images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_340032293_photo_618696045.jpg - 111/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.35images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339993526_photo_618618071.jpg - 112/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.27images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339993293_photo_618617361.jpg - 113/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.50images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339990356_photo_618610964.jpg - 114/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.22images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339988554_photo_618607587.jpg - 115/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.80images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339988554_photo_618607588.jpg - 116/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.14images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339988554_photo_618607585.jpg - 117/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.76images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339965719_photo_618559388.jpg - 118/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.19images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339948123_photo_618523115.jpg - 119/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.39images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339948123_photo_618522651.jpg - 120/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.30images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339948123_photo_618522668.jpg - 121/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.99images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339948123_photo_618522675.jpg - 122/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.45images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339948123_photo_618522691.jpg - 123/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.80images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339948123_photo_618522723.jpg - 124/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.24images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339948123_photo_618522712.jpg - 125/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.38images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339948123_photo_618522729.jpg - 126/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.05images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339948123_photo_618522734.jpg - 127/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.68images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339948123_photo_618522748.jpg - 128/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.13images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339948077_photo_618522651.jpg - 129/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.33images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339948077_photo_618522668.jpg - 130/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.12images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339948077_photo_618522675.jpg - 131/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.15images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339948077_photo_618522691.jpg - 132/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.37images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339948077_photo_618522723.jpg - 133/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.07images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339948077_photo_618522712.jpg - 134/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.18images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339948077_photo_618522729.jpg - 135/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.45images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339948077_photo_618522734.jpg - 136/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.98images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339948077_photo_618522748.jpg - 137/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.73images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339945807_photo_618517819.jpg - 138/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.54images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339945807_photo_618517821.jpg - 139/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.73images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339945807_photo_618517882.jpg - 140/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.86images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339945807_photo_618517818.jpg - 141/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.64images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339945807_photo_618517883.jpg - 142/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.37images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339945807_photo_618517887.jpg - 143/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.99images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339945807_photo_618517926.jpg - 144/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.47images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339919588_photo_618465383.jpg - 145/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.74images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339919588_photo_618465375.jpg - 146/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.86images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339919588_photo_618465395.jpg - 147/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.82images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339919588_photo_618465374.jpg - 148/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.39images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339919588_photo_618465405.jpg - 149/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.52images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339919588_photo_618465393.jpg - 150/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.29images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339919588_photo_618465392.jpg - 151/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.74images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339908235_photo_618452115.jpg - 152/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.61images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339908235_photo_102541386.jpg - 153/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.10images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339799625_photo_505069588.jpg - 154/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.01images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339633540_photo_617877234.jpg - 155/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.86images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339632321_photo_570788975.jpg - 156/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.27images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339576790_photo_617769794.jpg - 157/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.94images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339530410_photo_617676213.jpg - 158/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.86images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339530410_photo_617676220.jpg - 159/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.66images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339484966_photo_41843755.jpg - 160/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.07images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339447471_photo_617505101.jpg - 161/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.00images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339447471_photo_617505099.jpg - 162/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.13images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339447471_photo_617505097.jpg - 163/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.70images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339447471_photo_617505098.jpg - 164/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.52images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339447471_photo_617505103.jpg - 165/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.13images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339447471_photo_617505091.jpg - 166/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.70images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339447471_photo_617505106.jpg - 167/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.67images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339413207_photo_617438781.jpg - 168/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.60images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339413207_photo_617438801.jpg - 169/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.96images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339413207_photo_617438818.jpg - 170/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.56images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339413099_photo_617438650.jpg - 171/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.40images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339413099_photo_617438676.jpg - 172/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.77images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339225579_photo_617048892.jpg - 173/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.33images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339225579_photo_617048909.jpg - 174/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.10images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339225579_photo_617048927.jpg - 175/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.37images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339225579_photo_617048944.jpg - 176/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.36images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339225579_photo_617048958.jpg - 177/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.39images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339225579_photo_617048966.jpg - 178/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.51images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339225579_photo_617048976.jpg - 179/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.85images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339225579_photo_617048983.jpg - 180/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.46images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339225579_photo_617048993.jpg - 181/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.28images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339225579_photo_617049006.jpg - 182/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.88images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339225579_photo_617049011.jpg - 183/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.67images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339197557_photo_616991445.jpg - 184/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.39images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339197557_photo_616991458.jpg - 185/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.68images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339197557_photo_616991463.jpg - 186/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.81images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339197557_photo_616991464.jpg - 187/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.39images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339189573_photo_348631255.jpg - 188/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.15images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339189573_photo_348631273.jpg - 189/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.07images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339187881_photo_351485161.jpg - 190/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.01images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339187881_photo_351485175.jpg - 191/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.45images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339173039_photo_616943579.jpg - 192/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.95images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339168613_photo_616917947.jpg - 193/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.69images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339168613_photo_616917952.jpg - 194/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.68images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339128282_photo_616850264.jpg - 195/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.95images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339128282_photo_616850260.jpg - 196/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.61images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339128282_photo_616850265.jpg - 197/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.25images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339128282_photo_616850268.jpg - 198/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.86images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339128191_photo_616850096.jpg - 199/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.53images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339128187_photo_616850080.jpg - 200/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.78images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339128163_photo_616849969.jpg - 201/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.87images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339094010_photo_8158662.jpg - 202/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.65images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339089145_photo_318924725.jpg - 203/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.21images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339047738_photo_616684663.jpg - 204/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.65images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339047738_photo_616684528.jpg - 205/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.35images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_339047738_photo_616684570.jpg - 206/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.52images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338960784_photo_616498857.jpg - 207/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.15images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338960783_photo_616498849.jpg - 208/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.16images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338960783_photo_616498854.jpg - 209/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.95images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338960783_photo_616498859.jpg - 210/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.37images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338960783_photo_616498864.jpg - 211/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.38images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338960783_photo_616498870.jpg - 212/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.92images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338955864_photo_616501761.jpg - 213/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.28images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338955864_photo_616501770.jpg - 214/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.65images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338955864_photo_616501787.jpg - 215/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.96images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338955864_photo_616501801.jpg - 216/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.96images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338955864_photo_616501819.jpg - 217/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.96images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338955864_photo_616501834.jpg - 218/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.92images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338949235_photo_616486878.jpg - 219/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.59images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338949235_photo_616486882.jpg - 220/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.50images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338949235_photo_616486933.jpg - 221/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.44images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338924205_photo_616388362.jpg - 222/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.78images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338924205_photo_616388461.jpg - 223/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.20images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338924205_photo_616388468.jpg - 224/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.34images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338848951_photo_616299653.jpg - 225/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.51images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338848951_photo_616299664.jpg - 226/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.20images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338848951_photo_616299665.jpg - 227/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.25images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338846557_photo_616294756.jpg - 228/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.65images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338846557_photo_616294748.jpg - 229/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.61images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338846557_photo_616294752.jpg - 230/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.30images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338845282_photo_616291894.jpg - 231/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.97images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338845282_photo_616291896.jpg - 232/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.82images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338838643_photo_616279463.jpg - 233/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.73images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338838643_photo_616279446.jpg - 234/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.85images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338838643_photo_616279458.jpg - 235/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.05images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338838643_photo_616279462.jpg - 236/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.62images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338838643_photo_616279461.jpg - 237/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.93images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338801663_photo_616201099.jpg - 238/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.84images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338801663_photo_616201100.jpg - 239/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.95images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338762379_photo_615667813.jpg - 240/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.66images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338762379_photo_615667817.jpg - 241/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.16images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338761023_photo_38491694.jpg - 242/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.51images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338761023_photo_38491685.jpg - 243/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.76images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338759072_photo_575448055.jpg - 244/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.49images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338755769_photo_616109251.jpg - 245/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.88images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338755768_photo_616109234.jpg - 246/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.27images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338755768_photo_616109225.jpg - 247/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.04images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338751788_photo_616101527.jpg - 248/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.99images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338745055_photo_616088352.jpg - 249/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.93images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338745055_photo_616088324.jpg - 250/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.41images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338745055_photo_616088344.jpg - 251/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.88images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338745055_photo_616088356.jpg - 252/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.88images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338721108_photo_616042969.jpg - 253/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.15images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338572816_photo_615752079.jpg - 254/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.31images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338572814_photo_615752082.jpg - 255/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.18images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338569655_photo_615747159.jpg - 256/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.68images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338562942_photo_335264472.jpg - 257/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.12images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338562942_photo_335264473.jpg - 258/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.76images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338562942_photo_335264477.jpg - 259/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.47images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338541959_photo_615693176.jpg - 260/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.00images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338541959_photo_615693180.jpg - 261/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.65images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338541959_photo_615693181.jpg - 262/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.33images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338491637_photo_615584999.jpg - 263/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.15images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338491629_photo_615582314.jpg - 264/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.16images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338491629_photo_615582333.jpg - 265/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.50images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338491629_photo_615582512.jpg - 266/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.82images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338486970_photo_615576074.jpg - 267/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.70images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338486970_photo_615576083.jpg - 268/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.45images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338486970_photo_615576099.jpg - 269/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.03images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338486790_photo_615575892.jpg - 270/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.60images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338486790_photo_615575908.jpg - 271/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.55images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338486790_photo_615575923.jpg - 272/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.78images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338486790_photo_615575941.jpg - 273/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.93images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338462037_photo_216865974.jpg - 274/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.93images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338453399_photo_30226879.jpg - 275/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.94images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338453399_photo_30226870.jpg - 276/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.96images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338431251_photo_615462622.jpg - 277/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.45images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338354236_photo_615281654.jpg - 278/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.85images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338354236_photo_615281660.jpg - 279/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.86images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338332901_photo_615254424.jpg - 280/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.43images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338332901_photo_615254434.jpg - 281/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.37images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338332901_photo_615254429.jpg - 282/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.18images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338332892_photo_615254395.jpg - 283/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.00images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338332892_photo_615254399.jpg - 284/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.61images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338332892_photo_615254401.jpg - 285/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.77images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338332892_photo_615254403.jpg - 286/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.51images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338332892_photo_615254388.jpg - 287/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.85images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338316962_photo_615221615.jpg - 288/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.49images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338262521_photo_615109527.jpg - 289/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.19images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338262521_photo_615109544.jpg - 290/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.52images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338262521_photo_615109556.jpg - 291/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.54images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338262521_photo_615109572.jpg - 292/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.14images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338262521_photo_615109586.jpg - 293/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.15images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338206231_photo_614993006.jpg - 294/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.01images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338206231_photo_614993009.jpg - 295/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.55images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338206231_photo_614993038.jpg - 296/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.77images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338206231_photo_614992980.jpg - 297/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.11images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338206231_photo_614993099.jpg - 298/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.80images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338175830_photo_614932794.jpg - 299/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.14images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338175830_photo_614932804.jpg - 300/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.03images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338175830_photo_614932814.jpg - 301/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.69images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338166165_photo_614909967.jpg - 302/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.38images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338166165_photo_614909969.jpg - 303/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.52images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338166164_photo_614909965.jpg - 304/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.28images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338165583_photo_614912191.jpg - 305/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.26images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338165583_photo_614912202.jpg - 306/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.27images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338165583_photo_614912201.jpg - 307/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.00images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338165541_photo_614911916.jpg - 308/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.83images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338069397_photo_614716384.jpg - 309/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.70images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338041950_photo_614659546.jpg - 310/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.37images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338034947_photo_614644071.jpg - 311/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.55images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338034774_photo_614643752.jpg - 312/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.99images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338031190_photo_505012971.jpg - 313/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.24images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338027874_photo_589517643.jpg - 314/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.91images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338027874_photo_589517346.jpg - 315/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.10images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338027874_photo_589517540.jpg - 316/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.35images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338027232_photo_592092217.jpg - 317/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.79images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338027232_photo_592092171.jpg - 318/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.07images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338027232_photo_592092194.jpg - 319/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.41images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338026678_photo_587138454.jpg - 320/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.20images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338026678_photo_587138430.jpg - 321/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.73images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338009233_photo_180025222.jpg - 322/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.56images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338007031_photo_614585735.jpg - 323/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.74images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_338007030_photo_614585734.jpg - 324/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.11images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337995289_photo_614561783.jpg - 325/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.64images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337995289_photo_614561780.jpg - 326/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.74images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337887939_photo_603842423.jpg - 327/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.39images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337885958_photo_614338019.jpg - 328/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.52images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337885958_photo_612671924.jpg - 329/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.07images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337885958_photo_612671929.jpg - 330/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.31images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337885801_photo_612291646.jpg - 331/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.35images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337861976_photo_614286119.jpg - 332/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.56images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337861976_photo_614286117.jpg - 333/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.30images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337861976_photo_614286116.jpg - 334/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.36images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337861974_photo_614285118.jpg - 335/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.07images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337861974_photo_614285115.jpg - 336/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.22images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337861974_photo_614285126.jpg - 337/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.35images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337861974_photo_614285131.jpg - 338/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.81images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337861974_photo_614285113.jpg - 339/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.56images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337760132_photo_614513782.jpg - 340/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.75images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337760132_photo_614081868.jpg - 341/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.05images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337760132_photo_614081898.jpg - 342/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.58images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337760132_photo_614081891.jpg - 343/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.11images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337760104_photo_614081797.jpg - 344/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.37images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337760104_photo_614081796.jpg - 345/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.42images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337760104_photo_614081790.jpg - 346/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.03images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337725484_photo_610341286.jpg - 347/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.27images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337725484_photo_610341288.jpg - 348/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.61images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337725484_photo_610341280.jpg - 349/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.86images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337725484_photo_610341281.jpg - 350/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.12images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337716094_photo_613987256.jpg - 351/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.71images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337716094_photo_613987304.jpg - 352/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.99images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337716082_photo_613987255.jpg - 353/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.56images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337716082_photo_613987268.jpg - 354/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.31images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337713466_photo_613982307.jpg - 355/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.76images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337713466_photo_614417603.jpg - 356/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.93images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337713466_photo_613982332.jpg - 357/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.68images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337713466_photo_613982355.jpg - 358/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.63images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337712499_photo_613972695.jpg - 359/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.25images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337712499_photo_613972699.jpg - 360/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.16images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337712493_photo_613972689.jpg - 361/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.87images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337712489_photo_613972674.jpg - 362/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.79images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337712489_photo_613972687.jpg - 363/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.79images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337712476_photo_613972515.jpg - 364/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.79images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337712476_photo_613972525.jpg - 365/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.78images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337712454_photo_613972414.jpg - 366/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.96images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337712393_photo_613972149.jpg - 367/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.00images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337712393_photo_613972144.jpg - 368/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.78images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337712375_photo_613972118.jpg - 369/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.52images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337712373_photo_613972118.jpg - 370/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.76images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337707313_photo_613969272.jpg - 371/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.73images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337707312_photo_613969254.jpg - 372/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.70images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337707312_photo_613969270.jpg - 373/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.79images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337705477_photo_613966472.jpg - 374/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.62images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337694352_photo_613944019.jpg - 375/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.74images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337694352_photo_613944024.jpg - 376/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.19images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337694352_photo_613944029.jpg - 377/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.16images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337681930_photo_613919430.jpg - 378/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.83images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337674147_photo_613904210.jpg - 379/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.82images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337674147_photo_613904529.jpg - 380/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.52images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337674147_photo_613904530.jpg - 381/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.50images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337664743_photo_613413164.jpg - 382/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.96images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337664743_photo_613413167.jpg - 383/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.72images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337664743_photo_613413168.jpg - 384/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.64images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337664743_photo_613413176.jpg - 385/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.20images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337664743_photo_613413198.jpg - 386/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.98images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337664743_photo_613413182.jpg - 387/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.14images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337664743_photo_613413201.jpg - 388/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.82images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337650530_photo_613853933.jpg - 389/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.91images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337650530_photo_613853942.jpg - 390/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.72images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337650530_photo_613853944.jpg - 391/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.95images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337650530_photo_613853945.jpg - 392/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.11images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337637954_photo_613832007.jpg - 393/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.46images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337637954_photo_613832008.jpg - 394/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.76images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337637954_photo_613831994.jpg - 395/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.07images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337636352_photo_613825244.jpg - 396/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.36images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337636352_photo_613825243.jpg - 397/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.22images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337636337_photo_613825185.jpg - 398/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.24images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337636334_photo_613825175.jpg - 399/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.87images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337632558_photo_613819528.jpg - 400/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.65images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337632558_photo_613819531.jpg - 401/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.38images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337632558_photo_613819526.jpg - 402/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.73images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337632558_photo_613819538.jpg - 403/24807

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.38images/s]

✅ Processed /rs1/researchers/a/amallav/image_dataset/obs_337632558_photo_613819539.jpg - 404/24807

  0%|                                                                                                                                         | 0/1 [00:00<?, ?images/s]

KeyboardInterrupt:

In [44]:
pred_df = pd.read_csv(output_csv)
pred_df

,file_name,kingdom,phylum,class,order,family,genus,species_epithet,species,common_name,score,path,id
0,/rs1/researchers/a/amallav/image_dataset/obs_3...,Animalia,Chordata,Mammalia,Rodentia,Geomyidae,Thomomys,Plesiothomomys potomacensis,Thomomys Plesiothomomys potomacensis,NaN,0.444246,/rs1/researchers/a/amallav/image_dataset/obs_3...,0
1,/rs1/researchers/a/amallav/image_dataset/obs_3...,Animalia,Chordata,NaN,Perciformes,Gobiidae,Gillichthys,mirabilis,Gillichthys mirabilis,Longjaw mudsucker,0.089155,/rs1/researchers/a/amallav/image_dataset/obs_3...,0
2,/rs1/researchers/a/amallav/image_dataset/obs_3...,Animalia,Chordata,Mammalia,Rodentia,Geomyidae,Thomomys,bottae,Thomomys bottae,Botta's pocket gopher,0.077021,/rs1/researchers/a/amallav/image_dataset/obs_3...,0
3,/rs1/researchers/a/amallav/image_dataset/obs_3...,Animalia,Chordata,NaN,Siluriformes,Clariidae,Clarias,batrachus,Clarias batrachus,Walking catfish,0.024569,/rs1/researchers/a/amallav/image_dataset/obs_3...,0
4,/rs1/researchers/a/amallav/image_dataset/obs_3...,Animalia,Chordata,Amphibia,Caudata,Ambystomatidae,Ambystoma,californiense,Ambystoma californiense,California tiger salamander,0.020836,/rs1/researchers/a/amallav/image_dataset/obs_3...,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020,/rs1/researchers/a/amallav/image_dataset/obs_3...,Plantae,Tracheophyta,Magnoliopsida,Asterales,Asteraceae,Silphium,perfoliatum,Silphium perfoliatum,Cup Plant,0.408247,/rs1/researchers/a/amallav/image_dataset/obs_3...,403
2021,/rs1/researchers/a/amallav/image_dataset/obs_3...,Animalia,Arthropoda,Insecta,Lepidoptera,Papilionidae,Papilio,glaucus,Papilio glaucus,Tiger swallowtail,0.240340,/rs1/researchers/a/amallav/image_dataset/obs_3...,403
2022,/rs1/researchers/a/amallav/image_dataset/obs_3...,Plantae,Tracheophyta,Magnoliopsida,Asterales,Asteraceae,Silphium,perplexum,Silphium perplexum,NaN,0.084591,/rs1/researchers/a/amallav/image_dataset/obs_3...,403
2023,/rs1/researchers/a/amallav/image_dataset/obs_3...,Plantae,Tracheophyta,Magnoliopsida,Asterales,Asteraceae,Silphium,integrifolium,Silphium integrifolium,Whole-leaf rosinweed,0.057766,/rs1/researchers/a/amallav/image_dataset/obs_3...,403
2024,/rs1/researchers/a/amallav/image_dataset/obs_3...,Plantae,Tracheophyta,Magnoliopsida,Asterales,Asteraceae,Silphium,dissectum,Silphium dissectum,NaN,0.039107,/rs1/researchers/a/amallav/image_dataset/obs_3...,403

# Convert top-k predictions into one row per cropped image

In [45]:
assert "file_name" in pred_df.columns, "Expected 'file_name' in prediction output"
assert "score" in pred_df.columns, "Expected 'score' in prediction output"
assert "species" in pred_df.columns, "Expected 'species' in prediction output"

In [46]:
# pred_df

In [ ]:
summary_rows = []

for image_path, group in pred_df.groupby("file_name", sort=False):
    group = group.sort_values("score", ascending=False).reset_index(drop=True) #This ensures highest-scoring prediction comes first.
    top1 = group.iloc[0]
    top2 = group.iloc[1]
    top3 = group.iloc[2]
    top4 = group.iloc[3]
    top5 = group.iloc[4]

    topk_records = group[["species", "common_name", "score"]].to_dict(orient="records") #keeps all top-k predictions, but only the most useful columns

    #summary row: one final record per crop, best prediction at top level and top-k stored as JSON
    row = {
        "image_path": image_path,
        "top1_species": top1.get("species"),
        "top2_species": top2.get("species"),
        "top3_species": top3.get("species"),
        "top4_species": top4.get("species"),
        "top5_species": top5.get("species"),
        "top1_common_name": top1.get("common_name"),
        "top1_score": top1.get("score"),
        "topk_predictions_json": json.dumps(topk_records, ensure_ascii=False),
    }
    summary_rows.append(row)

summary_df = pd.DataFrame(summary_rows)

final_df = org_df.merge(summary_df, on="image_path", how="left") #why left? keeps all crops from crop_df, even if somehow a prediction row is missing.

# final_df["low_confidence_flag"] = final_df["top1_score"] < 0.20

print("Final rows:", len(final_df))
final_df.head()

Final rows: 24807

,image_path,image_id,top1_species,top2_species,top3_species,top4_species,top5_species,top1_common_name,top1_score,topk_predictions_json
0,/rs1/researchers/a/amallav/image_dataset/obs_3...,obs_341194952_photo_621071156,Thomomys Plesiothomomys potomacensis,Thomomys Plesiothomomys potomacensis,Gillichthys mirabilis,Gillichthys mirabilis,Thomomys bottae,NaN,0.444246,"[{""species"": ""Thomomys Plesiothomomys potomace..."
1,/rs1/researchers/a/amallav/image_dataset/obs_3...,obs_341194952_photo_621071168,Thomomys Plesiothomomys potomacensis,Thomomys bottae,Ardea alba,Hypsopsetta guttulata,Ardea modesta,NaN,0.201480,"[{""species"": ""Thomomys Plesiothomomys potomace..."
2,/rs1/researchers/a/amallav/image_dataset/obs_3...,obs_341194952_photo_621071177,Ardea alba,Ardea modesta,Egretta thula,Egretta intermedia,Bubulcus ibis,Great Egret,0.674656,"[{""species"": ""Ardea alba"", ""common_name"": ""Gre..."
3,/rs1/researchers/a/amallav/image_dataset/obs_3...,obs_341194952_photo_621071190,Ardea modesta,Ardea alba,Egretta intermedia,Bubulcus ibis,Egretta thula,Great Egret,0.666560,"[{""species"": ""Ardea modesta"", ""common_name"": ""..."
4,/rs1/researchers/a/amallav/image_dataset/obs_3...,obs_341194952_photo_621071213,Ardea modesta,Ardea alba,Egretta intermedia,Egretta thula,Bubulcus ibis,Great Egret,0.618911,"[{""species"": ""Ardea modesta"", ""common_name"": ""..."

In [52]:
# final_df[final_df["top1_species"].isna()]

,image_path,image_id,top1_species,top2_species,top3_species,top4_species,top5_species,top1_common_name,top1_score,topk_predictions_json
404,/rs1/researchers/a/amallav/image_dataset/obs_3...,obs_337632555_photo_613819514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
405,/rs1/researchers/a/amallav/image_dataset/obs_3...,obs_337632541_photo_613819362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
406,/rs1/researchers/a/amallav/image_dataset/obs_3...,obs_337632541_photo_613819364,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
407,/rs1/researchers/a/amallav/image_dataset/obs_3...,obs_337632541_photo_613819379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
408,/rs1/researchers/a/amallav/image_dataset/obs_3...,obs_337613554_photo_613782306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
24802,/rs1/researchers/a/amallav/image_dataset/obs_4...,obs_414645_photo_28352912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24803,/rs1/researchers/a/amallav/image_dataset/obs_3...,obs_338604_photo_421440,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24804,/rs1/researchers/a/amallav/image_dataset/obs_3...,obs_338604_photo_421441,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24805,/rs1/researchers/a/amallav/image_dataset/obs_3...,obs_338604_photo_421442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24806,/rs1/researchers/a/amallav/image_dataset/obs_3...,obs_338604_photo_421443,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
summary_rows = []

for image_path, group in pred_df.groupby("file_name", sort=False):
    group = group.sort_values("score", ascending=False).reset_index(drop=True) #This ensures highest-scoring prediction comes first.
    top1 = group.iloc[0]
    top2 = group.iloc[1]
    top3 = group.iloc[2]
    top4 = group.iloc[3]
    top5 = group.iloc[4]

    topk_records = group[["species", "common_name", "score"]].to_dict(orient="records") #keeps all top-k predictions, but only the most useful columns

    #summary row: one final record per crop, best prediction at top level and top-k stored as JSON
    for i in range(5):
        no=i+1
        no=str(no)
        val="top"+no+"_species"
        sc="top"+no+"_score"
        cc="top"+no+"_common_name"
        row = {
            "image_path": image_path,
            # val:group.iloc[i].get("species"),
            "species": group.iloc[i].get("species"),
            # "top2_species": top2.get("species"),
            # "top3_species": top3.get("species"),
            # "top4_species": top4.get("species"),
            # "top5_species": top5.get("species"),
            "common_name": group.iloc[i].get("common_name"),
            "kingdom": group.iloc[i].get("kingdom"),
            "phylum": group.iloc[i].get("phylum"),
            "class": group.iloc[i].get("class"),
            "order": group.iloc[i].get("order"),
            "family": group.iloc[i].get("family"),
            "genus": group.iloc[i].get("genus"),
            "score": group.iloc[i].get("score"),
            "top_no":no,
            "topk_predictions_json": json.dumps(topk_records, ensure_ascii=False),
        }
        summary_rows.append(row)

summary_df = pd.DataFrame(summary_rows)

full_df = org_df.merge(summary_df, on="image_path", how="left") #why left? keeps all crops from crop_df, even if somehow a prediction row is missing.

# final_df["low_confidence_flag"] = final_df["top1_score"] < 0.20

print("Final rows:", len(full_df))
full_df.head()

Final rows: 26423

,image_path,image_id,species,common_name,kingdom,phylum,class,order,family,genus,score,top_no,topk_predictions_json
0,/rs1/researchers/a/amallav/image_dataset/obs_3...,obs_341194952_photo_621071156,Thomomys Plesiothomomys potomacensis,NaN,Animalia,Chordata,Mammalia,Rodentia,Geomyidae,Thomomys,0.444246,1,"[{""species"": ""Thomomys Plesiothomomys potomace..."
1,/rs1/researchers/a/amallav/image_dataset/obs_3...,obs_341194952_photo_621071156,Thomomys Plesiothomomys potomacensis,NaN,Animalia,Chordata,Mammalia,Rodentia,Geomyidae,Thomomys,0.444246,2,"[{""species"": ""Thomomys Plesiothomomys potomace..."
2,/rs1/researchers/a/amallav/image_dataset/obs_3...,obs_341194952_photo_621071156,Gillichthys mirabilis,Longjaw mudsucker,Animalia,Chordata,NaN,Perciformes,Gobiidae,Gillichthys,0.089155,3,"[{""species"": ""Thomomys Plesiothomomys potomace..."
3,/rs1/researchers/a/amallav/image_dataset/obs_3...,obs_341194952_photo_621071156,Gillichthys mirabilis,Longjaw mudsucker,Animalia,Chordata,NaN,Perciformes,Gobiidae,Gillichthys,0.089155,4,"[{""species"": ""Thomomys Plesiothomomys potomace..."
4,/rs1/researchers/a/amallav/image_dataset/obs_3...,obs_341194952_photo_621071156,Thomomys bottae,Botta's pocket gopher,Animalia,Chordata,Mammalia,Rodentia,Geomyidae,Thomomys,0.077021,5,"[{""species"": ""Thomomys Plesiothomomys potomace..."

# Save final output CSV

In [ ]:
OUT_CSV = OUTPUTS_BC_DIR / "bioclip_species_predictions_baseline.csv"
final_df.to_csv(OUT_CSV, index=False)
print("Saved:", OUT_CSV)

Saved: /rs1/researchers/a/amallav/results/outputs_bioclip_crop/bioclip_species_predictions_2.csv

In [ ]:
OUT_CSV = OUTPUTS_BC_DIR / "results_baseline.csv"
full_df.to_csv(OUT_CSV, index=False)
print("Saved:", OUT_CSV)

Saved: /rs1/researchers/a/amallav/results/outputs_bioclip_crop/results_crop_2.csv